### ISSUE TITLE
LUA erorr 1.9.36 Wotlk classic

### ISSUE THREAD

**Issue by GregoryGH** [AdiAddons/AdiBags#690] opened 2022-09-03 09:50 UTC
appear on login

1x AdiBags\core\EventHandlers.lua:44: Attempt to register unknown event "CURSOR_UPDATE"
[string "=[C]"]: in function `RegisterEvent'
[string "@AdiBags\core\EventHandlers.lua"]:44: in function `OnUsed'
[string "@LibSharedMedia-3.0-8020003\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:76: in function <...edia-3.0\CallbackHandler-1.0\CallbackHandler-1.0.lua:59>
[string "=(tail call)"]: ?

**Comment by festisio** [comment] 2022-09-03 14:57
Message: Interface\AddOns\AdiBags\core\EventHandlers.lua:44: Attempt to register unknown event "CURSOR_UPDATE"
Time: Sat Sep  3 15:56:53 2022
Count: 1
Stack: Interface\AddOns\AdiBags\core\EventHandlers.lua:44: Attempt to register unknown event "CURSOR_UPDATE"
[string "@Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua"]:761: in function <...Ons\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:717>
[string "=[C]"]: ?
[string "=[C]"]: in function `RegisterEvent'
[string "@Interface\AddOns\AdiBags\core\EventHandlers.lua"]:44: in function `OnUsed'
[string "@Interface\AddOns\AdiBags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:76: in function <...ags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:59>
[string "=(tail call)"]: ?

Locals: errMsg = "Interface\AddOns\AdiBags\core\EventHandlers.lua:44: Attempt to register unknown event "CURSOR_UPDATE""
isBugGrabber = nil
tsmErrMsg = nil
oldModule = nil
private = <table> {
 globalNameTranslation = <table> {
 }
 FormatErrorMessageSection = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:517
 ErrorHandler = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:134
 origErrorHandler = <function> defined @Interface\SharedXML\SharedBasicControls.lua:355
 hitInternalError = false
 CreateErrorFrame = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:536
 num = 0
 SanitizeString = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:510
 AddonBlockedHandler = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:502
 GetStackLevelInfo = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:344
 ParseLocals = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:396
 ignoreErrors = false
 errorReports = <table> {
 }
 IsTSMAddon = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:478
 localLinesTemp = <table> {
 }
 GetStackInfo = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:313
}
MAX_STACK_DEPTH = 50
OLD_TSM_MODULES = <table> {
 1 = "TradeSkillMaster_Accounting"
 2 = "TradeSkillMaster_AuctionDB"
 3 = "TradeSkillMaster_Auctioning"
 4 = "TradeSkillMaster_Crafting"
 5 = "TradeSkillMaster_Destroying"
 6 = "TradeSkillMaster_Mailing"
 7 = "TradeSkillMaster_Shopping"
 8 = "TradeSkillMaster_Vendoring"
 9 = "TradeSkillMaster_Warehousing"
}

**Comment by Cidan** [comment] 2022-09-03 15:30
Duplicate of #682. Curse took > a day for approvals for some reason, it's updated on Curse now. Alternatively, you can use WowUp to download updates sooner.

**Closed by Cidan** 2022-09-03 15:30 UTC
Labels: Bug, Pending
