### ISSUE TITLE
Everytime I open my bags I get an error.

### ISSUE THREAD

**Issue by lespaul5895** [AdiAddons/AdiBags#341] opened 2019-03-14 13:26 UTC
I'm getting an error every time I try to open my bags.  I have the latest version, so not sure what's going on here.
![adierror](https://user-images.githubusercontent.com/27864367/54360465-4a97fc00-463b-11e9-94f5-bcb2948273a4.jpg)

**Comment by SpareSimian** [comment] 2019-03-14 14:18
Duplicate of issue #332. Update to 1.9.14. (Post the version when you report a bug.)

**Comment by lespaul5895** [comment] 2019-03-14 15:10
> Duplicate of issue #332. Update to 1.9.14. (Post the version when you report a bug.)

I have version 1.9.14 and am still having this issue when I try to open my bags.

**Comment by Talyrius** [comment] 2019-03-14 17:21
If 1.9.14 were successfully installed, you wouldn't have received those errors. The Twitch app isn't infallible, so you can't always rely on it to do its job. I suggest you download and install the addon manually, on this occasion.

**Closed by Talyrius** 2019-03-14 17:21 UTC
