### ISSUE TITLE
Options in Adibags Themes Not Selectable

### ISSUE THREAD

**Issue by msromike** [AdiAddons/AdiBags#923] opened 2023-01-27 20:23 UTC
### Addon Version

v1,10.7

### World of Warcraft Version

Retail

### Describe the bug

Cannot modify themes, fonts, colors, alpha, etc.

![2023-01-27 14_20_34-World of Warcraft](https://user-images.githubusercontent.com/47092317/215189813-5433502a-c0dc-44a7-b5da-4e5cbcc88378.jpg)

### Steps to reproduce

1)  Disable all addons
2) start with fresh config
3) try to change background color of bag

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by Talyrius** [comment] 2023-01-29 22:44
This issue is a duplicate of #900. It was also [asked](https://discord.com/channels/1063213796845428876/1063213797633966122/1068630141300899920) and answered by the OP in Discord.

**Closed by Talyrius** 2023-01-29 22:44 UTC
Labels: Duplicate
