### ISSUE TITLE
Errors Adibags since 7.3 patch

### ISSUE THREAD

**Issue by Leinhilena** [AdiAddons/AdiBags#221] opened 2017-08-30 21:13 UTC
ok, when i log into wow, my adibags i open it up and nothing is there. everytime i open it i get a different error msg, here is 2 of those. 0000019761480b80 Interface\addons\adibags\containerframe.lua.424
another one ia 000002a213a1c0a0 and Interface\addons\adibags\containerframe.lua.409.
I uninstalled all and reinstalled hoping that would fix but it did not. Please help

**Comment by fmneto** [comment] 2017-08-30 21:23
The problem seems to be caused by a change in how the PlaySound function works in the WoW addon API.  That function is called in lines 409 and 421 of ContainerFrame.lua (inside the widgets folder). I'm not sure if that function is called somewhere else but commenting out those lines seems to suppress the issue for now.

**Comment by SpareSimian** [comment] 2017-08-30 21:40
Duplicate of closed #217

**Closed** 2017-08-30 22:27 UTC
Labels: duplicate
