### ISSUE TITLE
ContainerFrame nil error after loading screen

### ISSUE THREAD

**Issue by T3ll1nG** [AdiAddons/AdiBags#339] opened 2019-03-13 21:11 UTC
Hi,
I have this error consistent after every loading screen on the newest build.

[20:56] Error in AdiBags: Interface\FrameXML\ContainerFrame.lua:1426: attempt to index a nil value -- details: [Error 0000014B73D73690]
[20:56] Error in AdiBags: Interface\FrameXML\ContainerFrame.lua:1426: attempt to index a nil value -- details: [Error 0000014B73D73690]
[20:56] Error in AdiBags: Interface\FrameXML\ContainerFrame.lua:1426: attempt to index a nil value -- details: [Error 0000014B73D73690]
[20:56] Error in AdiBags: Interface\FrameXML\ContainerFrame.lua:1426: attempt to index a nil value -- details: [Error 0000014B73D73690]
[20:56] Error in AdiBags: Interface\FrameXML\ContainerFrame.lua:1426: attempt to index a nil value -- details: [Error 0000014B73D73690]
[20:56] Error in AdiBags: Interface\FrameXML\ContainerFrame.lua:1426: attempt to index a nil value -- details: [Error 0000014B73D73690]
[20:56] Interface\FrameXML\ContainerFrame.lua:1426: attempt to index a nil value
[20:56] Interface\FrameXML\ContainerFrame.lua:1426: in function `GetItemContextMatchResult'
Interface\FrameXML\ItemButtonTemplate.lua:214: in function `UpdateItemContextMatching'
Interface\FrameXML\ItemButtonTemplate.lua:190: in function <Interface\FrameXML\ItemButtonTemplate.lua:189>
[C]: in function `Show'
Interface\AddOns\AdiBags\core\Bags.lua:89: in function `Open'
Interface\AddOns\AdiBags\core\Hooks.lua:112: in function <Interface\AddOns\AdiBags\core\Hooks.lua:109>
(tail call): ?
(tail call): ?
[C]: in function `ToggleAllBags'
[string "OPENALLBAGS"]:1: in function <[string "OPENALLBAGS"]:1>
[20:56] self = AdiBagsItemButton66 {
 timeSinceUpgradeCheck = 0
 PostOnLoad = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:169
 BattlepayItemTexture = <unnamed> {
 }
 IconOverlay = <unnamed> {
 }
 BagStaticTop = <unnamed> {
 }
 GetItemContextMatchResult = <function> defined @Interface\FrameXML\ContainerFrame.lua:1425
 IconBorder = <unnamed> {
 }
 newitemglowAnim = <unnamed> {
 }
 icon = AdiBagsItemButton66IconTexture {
 }
 UpdateTooltip = <function> defined @Interface\FrameXML\ContainerFrame.lua:1347
 ExtendedOverlay = <unnamed> {
 }
 RegisterCallback = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:175
 itemContextChangedCallbackIsSet = false
 UnregisterCallback = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:182
 UpdateItemContextMatching = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:211
 itemContextMatchResult = 3
 NewItemTexture = <unnamed> {
 }
 Cooldown = AdiBagsItemButton66Cooldown {
 }
 bagFamily = 0
 count = 20
 CanIMogItOverlay = CIMIOverlayFrame_AdiBagsItemButton66 {
 }
 BagStaticBottom = <unnamed> {
 }
 ItemContextOverlay = <unnamed> {
 }
 PostOnShow = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:189
 flash = <unnamed> {
 }
 texture = 1045940
 itemId = 126936
 itemLink = "[Sugar-Crusted Fish Feast]"
 ExtendedSlot = <unnamed> {
 }
 ExtendedOverlay2 = <unnamed> {
 }
 hasItem = true
 IconTexture = AdiBagsItemButton66IconTexture {
 }
 JunkIcon = <unnamed> {
 }
 SetMatchesSearch = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:202
 UpdateItemContextOverlay = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:222
 slot = 17
 bag = 3
 NormalTexture = AdiBagsItemButton66NormalTexture {
 }
 Stock = AdiBagsItemButton66Stock {
 }
 IconQuestTexture = AdiBagsItemButton66IconQuestTexture {
 }
 itemContextChangedCallback = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:170
 0 = <userdata>
 Count = AdiBagsItemButton66Count {
 }
 PostOnHide = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:198
 flashAnim = <unnamed> {
 }
 GetMatchesSearch = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:207
 UpgradeIcon = <unnamed> {
 }
 searchOverlay = AdiBagsItemButton66SearchOverlay {
 }
}
(*temporary) = <function> defined @Interface\FrameXML\ItemUtil.lua:47
(*temporary) = <function> defined @Interface\FrameXML\ObjectAPI\ItemLocation.lua:9
(*temporary) = <table> {
 CreateFromBagAndSlot = <function> defined @Interface\FrameXML\ObjectAPI\ItemLocation.lua:9
 CreateFromEquipmentSlot = <function> defined @Interface\FrameXML\ObjectAPI\ItemLocation.lua:15
 CreateEmpty = <function> defined @Interface\FrameXML\ObjectAPI\ItemLocation.lua:4
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index a nil value"

**Comment by belechannas** [comment] 2019-03-14 04:24
Seeing the identical stack trace (with version 1.9.14).

Mine occurred when I opened my bags.  I haven't been able to make it happen reproducibly.

**Comment by SpareSimian** [comment] 2019-03-14 14:21
I'm also seeing this intermittently. I haven't yet determined any pattern. It's been low-frequency so I hadn't opened a bug.

**Comment by chuck-poulsen** [comment] 2019-03-14 16:48
I just had this pop up.  I was working on some cooking and I don't know exactly what I did, but the error popped up saying:
" Error in AdiBags: Interface\FrameXML\ContainerFrame.lua:1426: attempt to index a nil value -- details: [Error 0000016F7363A6F0] 
[12:46:42] Interface\FrameXML\ContainerFrame.lua:1426: attempt to index a nil value 
[12:46:42] Interface\FrameXML\ContainerFrame.lua:1426: in function `GetItemContextMatchResult'
Interface\FrameXML\ItemButtonTemplate.lua:214: in function `UpdateItemContextMatching'
Interface\FrameXML\ItemButtonTemplate.lua:190: in function <Interface\FrameXML\ItemButtonTemplate.lua:189>
[C]: in function `Show'
Interface\AddOns\AdiBags\core\Bags.lua:89: in function `Open'
Interface\AddOns\AdiBags\core\Hooks.lua:112: in function <Interface\AddOns\AdiBags\core\Hooks.lua:109>
(tail call): ?
(tail call): ?
[string "OPENALLBAGS"]:1: in function <[string "OPENALLBAGS"]:1> 
[12:46:42] self = AdiBagsItemButton63 {
 timeSinceUpgradeCheck = 0
 PostOnLoad = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:169
 BattlepayItemTexture = <unnamed> {
 }
 IconOverlay = <unnamed> {
 }
 BagStaticTop = <unnamed> {
 }
 GetItemContextMatchResult = <function> defined @Interface\FrameXML\ContainerFrame.lua:1425
 IconBorder = <unnamed> {
 }
 newitemglowAnim = <unnamed> {
 }
 icon = AdiBagsItemButton63IconTexture {
 }
 UpdateTooltip = <function> defined @Interface\FrameXML\ContainerFrame.lua:1347
 ExtendedOverlay = <unnamed> {
 }
 RegisterCallback = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:175
 UnregisterCallback = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:182
 UpdateItemContextMatching = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:211
 itemContextChangedCallbackIsSet = false
 NewItemTexture = <unnamed> {
 }
 Cooldown = AdiBagsItemButton63Cooldown {
 }
 bagFamily = 0
 itemContextMatchResult = 3
 count = 44
 BagStaticBottom = <unnamed> {
 }
 filterName = "Track new items"
 ItemContextOverlay = <unnamed> {
 }
 PostOnShow = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:189
 flash = <unnamed> {
 }
 ExtendedSlot = <unnamed> {
 }
 ExtendedOverlay2 = <unnamed> {
 }
 hasItem = false
 IconTexture = AdiBagsItemButton63IconTexture {
 }
 JunkIcon = <unnamed> {
 }
 SetMatchesSearch = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:202
 UpdateItemContextOverlay = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:222
 slot = 5
 bag = 1
 NormalTexture = AdiBagsItemButton63NormalTexture {
 }
 Stock = AdiBagsItemButton63Stock {
 }
 IconQuestTexture = AdiBagsItemButton63IconQuestTexture {
 }
 itemContextChangedCallback = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:170
 0 = <userdata>
 Count = AdiBagsItemButton63Count {
 }
 PostOnHide = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:198
 flashAnim = <unnamed> {
 }
 GetMatchesSearch = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:207
 UpgradeIcon = <unnamed> {
 }
 searchOverlay = AdiBagsItemButton63SearchOverlay {
 }
}
(*temporary) = <function> defined @Interface\FrameXML\ItemUtil.lua:47
(*temporary) = <function> defined @Interface\FrameXML\ObjectAPI\ItemLocation.lua:9
(*temporary) = <table> {
 CreateFromBagAndSlot = <function> defined @Interface\FrameXML\ObjectAPI\ItemLocation.lua:9
 CreateFromEquipmentSlot = <function> defined @Interface\FrameXML\ObjectAPI\ItemLocation.lua:15
 CreateEmpty = <function> defined @Interface\FrameXML\ObjectAPI\ItemLocation.lua:4
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index a nil value""

I hope this is helpful.  Thanks for the great mod!

**Comment by vicgrant** [comment] 2019-03-15 11:27
I can reproduce the error by having my bags open along with the auction house window, on toggling closed the equipped bags window the following error message appears 6 times per toggle off. I've also seen the same error when closing bags after using the scrapper.

Error in AdiBags: Interface\FrameXML\ContainerFrame.lua:1426: attempt to index a nil value -- details: [Error 0000019EDFACC8F0]
Error in AdiBags: Interface\FrameXML\ContainerFrame.lua:1426: attempt to index a nil value -- details: [Error 0000019EDFACC8F0]
Error in AdiBags: Interface\FrameXML\ContainerFrame.lua:1426: attempt to index a nil value -- details: [Error 0000019EDFACC8F0]
Error in AdiBags: Interface\FrameXML\ContainerFrame.lua:1426: attempt to index a nil value -- details: [Error 0000019EDFACC8F0]
Error in AdiBags: Interface\FrameXML\ContainerFrame.lua:1426: attempt to index a nil value -- details: [Error 0000019EDFACC8F0]
Error in AdiBags: Interface\FrameXML\ContainerFrame.lua:1426: attempt to index a nil value -- details: [Error 0000019EDFACC8F0]

**Comment by Txmarshall** [comment] 2019-03-15 14:40
Also experiencing these errors on current release (version 1.9.14-nolib). This release auto-installs with Twitch as current update. I reverted to (version 1.9.14) and I am not getting these errors. Thanks for all of the hard work developing and keeping this up when Blizzard decides to break things.

**Comment by SpareSimian** [comment] 2019-03-15 14:45
I saw the error today in my WoD garrison but it was random. I just now tried it at the AH and it's not happening. I'm using the 1.9.14 installed by Twitch yesterday. Since then Twitch has been broken. Their move to a desktop app seems to have badly broken their code.

**Comment by zerzhul** [comment] 2019-03-16 04:33
I can reproduce this error consistently by clicking the toggle equipped bag panel icon.

```
20x FrameXML\ContainerFrame.lua:1426: attempt to index a nil value
FrameXML\ContainerFrame.lua:1426: in function `GetItemContextMatchResult'
FrameXML\ItemButtonTemplate.lua:214: in function `UpdateItemContextMatching'
FrameXML\ItemButtonTemplate.lua:190: in function <FrameXML\ItemButtonTemplate.lua:189>
[C]: in function `SetShown'
AdiBags\widgets\ContainerFrame.lua:82: in function <AdiBags\widgets\ContainerFrame.lua:81>

Locals:
self = AdiBagsItemButton157 {
 timeSinceUpgradeCheck = 0
 PostOnLoad = <function> defined @FrameXML\ItemButtonTemplate.lua:169
 BattlepayItemTexture = <unnamed> {
 }
 IconOverlay = <unnamed> {
 }
 BagStaticTop = <unnamed> {
 }
 GetItemContextMatchResult = <function> defined @FrameXML\ContainerFrame.lua:1425
 IconBorder = <unnamed> {
 }
 newitemglowAnim = <unnamed> {
 }
 icon = AdiBagsItemButton157IconTexture {
 }
 UpdateTooltip = <function> defined @FrameXML\ContainerFrame.lua:1347
 ExtendedOverlay = <unnamed> {
 }
 RegisterCallback = <function> defined @FrameXML\ItemButtonTemplate.lua:175
 UnregisterCallback = <function> defined @FrameXML\ItemButtonTemplate.lua:182
 UpdateItemContextMatching = <function> defined @FrameXML\ItemButtonTemplate.lua:211
 NewItemTexture = <unnamed> {
 }
 Cooldown = AdiBagsItemButton157Cooldown {
 }
 bagFamily = 0
 itemContextChangedCallbackIsSet = false
 itemContextMatchResult = 3
 BagStaticBottom = <unnamed> {
 }
 count = 10
 ItemContextOverlay = <unnamed> {
 }
 PostOnShow = <function> defined @FrameXML\ItemButtonTemplate.lua:189
 flash = <unnamed> {
 }
 ExtendedSlot = <unnamed> {
 }
 ExtendedOverlay2 = <unnamed> {
 }
 hasItem = false
 IconTexture = AdiBagsItemButton157IconTexture {
 }
 JunkIcon = <unnamed> {
 }
 SetMatchesSearch = <function> defined @FrameXML\ItemButtonTemplate.lua:202
 UpdateItemContextOverlay = <function> defined @FrameXML\ItemButtonTemplate.lua:222
 slot = 11
 bag = 0
 NormalTexture = AdiBagsItemButton157NormalTexture {
 }
 Stock = AdiBagsItemButton157Stock {
 }
 IconQuestTexture = AdiBagsItemButton157IconQuestTexture {
 }
 itemContextChangedCallback = <function> defined @FrameXML\ItemButtonTemplate.lua:170
 0 = <userdata>
 Count = AdiBagsItemButton157Count {
 }
 PostOnHide = <function> defined @FrameXML\ItemButtonTemplate.lua:198
 flashAnim = <unnamed> {
 }
 GetMatchesSearch = <function> defined @FrameXML\ItemButtonTemplate.lua:207
 UpgradeIcon = <unnamed> {
 }
 searchOverlay = AdiBagsItemButton157SearchOverlay {
 }
}
(*temporary) = <function> defined @FrameXML\ItemUtil.lua:47
(*temporary) = <function> defined @FrameXML\ObjectAPI\ItemLocation.lua:9
(*temporary) = <table> {
 CreateFromBagAndSlot = <function> defined @FrameXML\ObjectAPI\ItemLocation.lua:9
 CreateFromEquipmentSlot = <function> defined @FrameXML\ObjectAPI\ItemLocation.lua:15
 CreateEmpty = <function> defined @FrameXML\ObjectAPI\ItemLocation.lua:4
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index a nil value"
```

**Comment by vanael** [comment] 2019-03-16 10:09
For me the same:
https://gyazo.com/4c9cb14584fda1cd210e71ddcba2a099

**Comment by bolerro** [comment] 2019-03-17 14:57
Similiar issue with nil value
`Interface\FrameXML\ContainerFrame.lua:1426: attempt to index a nil value 
Interface\FrameXML\ContainerFrame.lua:1426: in function `GetItemContextMatchResult'
Interface\FrameXML\ItemButtonTemplate.lua:214: in function `UpdateItemContextMatching'
Interface\FrameXML\ItemButtonTemplate.lua:190: in function <Interface\FrameXML\ItemButtonTemplate.lua:189>
[C]: in function `Show'
Interface\AddOns\AdiBags\core\Bags.lua:89: in function `Open'
Interface\AddOns\AdiBags\core\Hooks.lua:112: in function <Interface\AddOns\AdiBags\core\Hooks.lua:109>
(tail call): ?
(tail call): ?
[string "OPENALLBAGS"]:1: in function <[string "OPENALLBAGS"]:1> 
self = AdiBagsItemButton157 {
 timeSinceUpgradeCheck = 0
 PostOnLoad = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:169
 BattlepayItemTexture = <unnamed> {
 }
 IconOverlay = <unnamed> {
 }
 BagStaticTop = <unnamed> {
 }
 GetItemContextMatchResult = <function> defined @Interface\FrameXML\ContainerFrame.lua:1425
 IconBorder = <unnamed> {
 }
 newitemglowAnim = <unnamed> {
 }
 icon = AdiBagsItemButton157IconTexture {
 }
 UpdateTooltip = <function> defined @Interface\FrameXML\ContainerFrame.lua:1347
 ExtendedOverlay = <unnamed> {
 }
 RegisterCallback = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:175
 UnregisterCallback = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:182
 UpdateItemContextMatching = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:211
 itemContextChangedCallbackIsSet = false
 NewItemTexture = <unnamed> {
 }
 Cooldown = AdiBagsItemButton157Cooldown {
 }
 bagFamily = 0
 itemContextMatchResult = 3
 count = 1
 BagStaticBottom = <unnamed> {
 }
 filterName = "Track new items"
 ItemContextOverlay = <unnamed> {
 }
 PostOnShow = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:189
 flash = <unnamed> {
 }
 ExtendedSlot = <unnamed> {
 }
 ExtendedOverlay2 = <unnamed> {
 }
 hasItem = false
 IconTexture = AdiBagsItemButton157IconTexture {
 }
 JunkIcon = <unnamed> {
 }
 SetMatchesSearch = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:202
 UpdateItemContextOverlay = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:222
 slot = 18
 bag = 0
 NormalTexture = AdiBagsItemButton157NormalTexture {
 }
 Stock = AdiBagsItemButton157Stock {
 }
 IconQuestTexture = AdiBagsItemButton157IconQuestTexture {
 }
 itemContextChangedCallback = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:170
 0 = <userdata>
 Count = AdiBagsItemButton157Count {
 }
 PostOnHide = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:198
 flashAnim = <unnamed> {
 }
 GetMatchesSearch = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:207
 UpgradeIcon = <unnamed> {
 }
 searchOverlay = AdiBagsItemButton157SearchOverlay {
 }
}
(*temporary) = <function> defined @Interface\FrameXML\ItemUtil.lua:47
(*temporary) = <function> defined @Interface\FrameXML\ObjectAPI\ItemLocation.lua:9
(*temporary) = <table> {
 CreateFromBagAndSlot = <function> defined @Interface\FrameXML\ObjectAPI\ItemLocation.lua:9
 CreateFromEquipmentSlot = <function> defined @Interface\FrameXML\ObjectAPI\ItemLocation.lua:15
 CreateEmpty = <function> defined @Interface\FrameXML\ObjectAPI\ItemLocation.lua:4
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index a nil value"`

**Comment by belechannas** [comment] 2019-03-17 18:32
The error may be associated with changing the stacking of objects at merchants, bank, mailbox, etc.

I had been using the option "Items->At merchants...->Show every distinct item stacks [sic]".  I could reproducibly generate the error by opening and closing the bank, and then opening my bags.  The same occurred for the mailbox and merchants.  I noticed that the number of stacks in my bags was changing due to this setting. (To see this, you would need to have the same setting AND more than one stack of some stackable items in bags).

With it set to "Keep all stacks together" the error does not seem to occur in situations where it was 100% reproducible with the other setting.  Putting it back to "Show every distinct item stacks" causes the errors to return.

**Comment by belechannas** [comment] 2019-03-18 04:42
Setting the configuration option

Items->At merchants, bank, auction house->Keep all stacks together

seems to suppress the errors.

**Closed** 2019-03-18 15:19 UTC
Labels: Bug
