### ISSUE TITLE
Client crashes when I open bags and have 20-slot Soul Bag equipped

### ISSUE THREAD

**Issue by CharlesRandles** [AdiAddons/AdiBags#926] opened 2023-01-30 23:49 UTC
### Addon Version

v1.10.7

### World of Warcraft Version

Wrath

### Describe the bug

My warlock has a 20-slot soul bag equipped (yes, I know....)

On my Apple M1 Mac when I have AdiBags running, the client crashes instantly when I open my bags. This does not affect any other character.

I have not tried with enchanting, mining, or herding bags.

### Steps to reproduce

1) Get a warlock
2) Equip a 20 slot Soul Bag
3) Install Adibags
4) Open bags. BOOM!

Simple workaround - unequal pointless soul bag.

Thank you for your work on this great add-on!

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by Talyrius** [comment] 2023-01-31 00:00
This issue is a duplicate of #731 with the possible exception of it being the result of using a soul bag instead of an equipment set. Please confirm this is case and if so, tell us about it on issue #731.

Thanks.

**Closed by Talyrius** 2023-01-31 00:00 UTC
Labels: Duplicate
