### ISSUE TITLE
Recent Items Tab

### ISSUE THREAD

**Issue by odanion** [AdiAddons/AdiBags#32] opened 2015-01-14 09:42 UTC
Before the latest update (when you removed a lot of your code in favor of Blizzards code) new items went straight to there own category if new items filter was turned off. Now whether it is turned on or off every item that enters my bag first goes into a "recent items" tab and I would like to remove this as it is highly annoying. Is there a possibility of doing this? I have been using Adi bags since the start more or less and would hate to look for a new addon, but for whatever reason this is annoying me more than it probably should :p

**Comment by harl** [comment] 2015-01-28 13:53
Me too, I don't quite see what purpose the Recent section serves in contrast to the New Items section that was there before already. Is it supposedly Blizzard's embedded equivalent? Then it's a bad one and I'd recommend not to adhere to it so strictly.

Neither of them are saved between login sessions (which would make it much more useful to me).

I've gotten used to the New Items thing, as it made it a lot easier to spot items I had actually picked up a moment ago, so I suppose Recent items could be similarly helpful.
There are more items in the Recent section for some reason than there usually were in the New Items section - sometimes most of my inventory ends up in the Recent section, which pretty much nullifies its usefulness in my opinion.  Some items are randomly placed in sections other than Recent/New, though they actually were new, seemingly ignoring the priority assigned to the New Items section in the settings.
(For me, it's Gear sets -> Manual -> Quest -> Junk -> New -> Equipment -> Items, and I'd prefer if none of the items that are part of a category higher than New would ever end up in Recent).

Please, as it seems your plans may be to just replace New with Recent, consider making it an optional filter altogether so it can be either disabled or at least respects the filtering priorities.

Also, the following may be related to the whole Recent Items thing as well.
It doesn't remove or shrink sections when items are shown as Recent and makes the whole Bags frame look odd and a bit confusing.
http://postimg.org/image/vw4vh6i8t/

And sometimes it goes all wonko
http://postimg.org/image/w7mbtxyot/
Note the top of that image is the top of my screen and items are displayed outside the visible area, which shouldn't happen, ever, unless there was a hidden setting to restrict the frame's width.

**Comment by Adirelle** [comment] 2015-01-28 18:28
The "Recent items" section *is not* handled by a filter. It is a buffer for the item buttons that have been added, moved or changed since the last time the bag was refreshed. When the bag is refreshed, the buffer is emptied and the items are properly dispatched. You can also click on the "recent items" header to force this. 

This section also automatically receive items marked as new, which you can reset by clicking on the "N" button. I should remove the "new items" as a filter and only keep it to highlight the items. This is planned.

There is still an issue where all the items are moved to the recent item tab. Though it happens often for some users (and almost never for me), I cannot reproduce it reliably so I have hard time fixing it.

**Comment by Cidan** [comment] 2016-07-26 01:56
This issue has been fixed. Items will appear in the "Recent Items" header only while shopping. As soon as you walk away/close the bag, items will sort into their proper groups.

**Closed by Cidan** 2016-07-26 01:56 UTC
