### ISSUE TITLE
Emblems of Heroism and additional currency

### ISSUE THREAD

**Issue by KonstantinosKoubetsos** [AdiAddons/AdiBags#716] opened 2022-10-14 17:13 UTC
They don't show in Adibags or I haven't figured out how to make them show up.

**Comment by SpareSimian** [comment] 2022-10-14 20:36
Is it a currency or an inventory item? Does it show up in the config panel under Plugins/Currency? (I'm not playing WotLK so can't check.)

https://www.wowhead.com/wotlk/item=40752/emblem-of-heroism#comments

**Comment by KonstantinosKoubetsos** [comment] 2022-10-15 15:57
Is is a currency. When you inspect your character details on the right, there's a tab called "Currency" that has additional currency types in it. You can click those and select to show on inventory even without addons.
In the plugins section there's not any option for it.

**Comment by SpareSimian** [comment] 2022-10-15 19:16
I looked at the AdiBags source code and it uses [C_Currency.GetCurrencyListInfo](https://wowpedia.fandom.com/wiki/API_C_CurrencyInfo.GetCurrencyListInfo) to get its currency list. So this smells like a Blizzard bug. I looked through my addons to see if any others use it and I see it's used in Altoholic. You might load that and see if it's also missing the Emblem of Heroism.

**Comment by david-driscoll** [comment] 2022-11-03 11:13
`GetCurrencyListInfo(index)`  and `GetCurrencyListSize()` to get the number of available ones.

**Comment by jelmerj** [comment] 2022-11-28 18:40
duplicate of #707

**Closed** 2022-11-30 09:20 UTC
Labels: Duplicate
