### ISSUE TITLE
Accessing the reagent bank generates an error and items in the bank are not shown

### ISSUE THREAD

**Issue by Kream** [AdiAddons/AdiBags#726] opened 2022-10-26 18:06 UTC
NOTE: Bugs can sometimes be caused by conflicts with other addons. Please disable all other addons and try to reproduce your issue. You must answer below that you have tried disabling all your addons before this bug is accepted. If you have not tried disabling all your addons, your bug will be closed.

**Describe the bug**
Attempting to access the reagent bank generates an error and items in the bank are not shown. This may be related to [Issue 725](https://github.com/AdiAddons/AdiBags/issues/725). 

**To Reproduce**
1. Interact with the banker
2. Click on the R button to access the reagent bank

**Expected behavior**
Items in the reagent bank are shown correctly and without any error

**Screenshots**
**Reagent Bank interface after clicking on R**:

<img width="467" alt="image" src="https://user-images.githubusercontent.com/738161/198101717-2e28a838-1128-4947-a0dc-bd0665572987.png">

**Reagent Bank interface after closing the error pane:**
<img width="374" alt="image" src="https://user-images.githubusercontent.com/738161/198101834-f5a73e10-3067-495b-88b8-478d02043ad4.png">

**Reagent Bank after closing and reopening** 
<img width="279" alt="image" src="https://user-images.githubusercontent.com/738161/198101987-20ce8ceb-fdcb-4861-a8b0-098a32e02290.png">

**World of Warcraft Release and Version (Retail 9.2.7, etc)**
 - Retail 10.0.0 (46313) 

**AdiBags Version**
- v1.9.39

**Have you tried disabling all your other addons to ensure only this addon causes the issue?**
 - Yes 

**Additional context**

**Comment by Cidan** [comment] 2022-10-26 19:36
Thanks for the bug report -- I'll take a look at this tonight and get a fix out ASAP.

**Comment by Cidan** [comment] 2022-10-27 00:23
I can't reproduce this, but I did fix the bug that caused the error message. Can you check and see if the new release (.40) fixes this for you?

**Comment by shawngmc** [comment] 2022-10-27 02:17
I'm not the original poster, but was having the same issue with the reagent bank.

Moving to the beta channel and getting .40 appears to have fixed it.

I might be filing a separate bug about a bank issue - if AdiBags bank handling is disabled, you can't open the bank bags.

**Comment by chilblane** [comment] 2022-10-28 20:22
I'm seeing this error in .41. Or something like it.

Opening the bank produces the following:
```
98x Interface/AddOns/AdiBags/widgets/ItemButton.lua:325: attempt to call method 'UpdateCooldown' (a nil value)
[string "@Interface/AddOns/AdiBags/widgets/ItemButton.lua"]:325: in function `Update'
[string "@Interface/AddOns/AdiBags/widgets/ItemButton.lua"]:303: in function `FullUpdate'
[string "@Interface/AddOns/AdiBags/widgets/ItemButton.lua"]:268: in function <Interface/AddOns/AdiBags/widgets/ItemButton.lua:256>
[string "=[C]"]: in function `Show'
[string "@Interface/AddOns/AdiBags/widgets/ContainerFrame.lua"]:1034: in function `PrepareSections'
[string "@Interface/AddOns/AdiBags/widgets/ContainerFrame.lua"]:1155: in function `FullUpdate'
[string "@Interface/AddOns/AdiBags/widgets/ContainerFrame.lua"]:599: in function <Interface/AddOns/AdiBags/widgets/ContainerFrame.lua:585>
[string "=[C]"]: ?
[string "@Interface/AddOns/AdiBags/core/Utility.lua"]:100: in function <Interface/AddOns/AdiBags/core/Utility.lua:92>
[string "@Interface/AddOns/AdiBags/widgets/LayeredRegion.lua"]:119: in function <Interface/AddOns/AdiBags/widgets/LayeredRegion.lua:108>

Locals:
self = AdiBagsBankItemButton28 {
 0 = <userdata>
 bag = -1
 IconOverlay2 = Texture {
 }
 OnUpdateItemContextMatching = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:632
 inventorySlot = 91
 IconOverlay = Texture {
 }
 itemId = 138727
 SetAlpha = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:616
 section = AdiBagsSection21 {
 }
 filterName = "Item category"
 IconBorder = Texture {
 }
 bagFamily = 0
 GetItemLocation = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:604
 icon = AdiBagsBankItemButton28IconTexture {
 }
 container = AdiBagsContainer2 {
 }
 SetItemButtonTexture = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:655
 acquired = true
 UpdateTooltip = <function> defined @Interface/FrameXML/BankFrame.lua:59
 GetBagID = <function> defined @Interface/FrameXML/BankFrame.lua:151
 SetItem = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:538
 texture = 134808
 showMatchHighlight = true
 OnItemContextChanged = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:404
 itemLink = "|cff0070dd|Hitem:138727::::::::60:251:::::::::|h[Potion of Defiance]|h|r"
 SetItemButtonQuality = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:643
 count = 6
 UpdateItemContextMatching = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:444
 SetItemSource = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:522
 SetItemButtonCount = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:608
 Cooldown = AdiBagsBankItemButton28Cooldown {
 }
 SetItemInternal = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:543
 IconTexture = AdiBagsBankItemButton28IconTexture {
 }
 UpdateCraftedProfessionsQualityShown = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:455
 itemContextMatchResult = 3
 NormalTexture = AdiBagsBankItemButton28NormalTexture {
 }
 GetItemButtonBackgroundTexture = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:663
 ItemContextOverlay = Texture {
 }
 PostOnShow = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:408
 UpdateItemContextOverlayTextures = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:493
 GetItemID = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:585
 GetItemButtonCount = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:612
 PostOnHide = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:417
 RegisterBagButtonUpdateItemContextMatching = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:638
 IconQuestTexture = Texture {
 }
 hasItem = true
 GetItemContextOverlayMode = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:465
 SetBagID = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:624
 searchOverlay = AdiBagsBankItemButton28SearchOverlay {
 }
 SetMatchesSearch = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:435
 UpdateItemContextOverlay = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:482
 slot = 28
 GetItemButtonIconTexture = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:659
 GetItemLink = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:600
 PostOnEvent = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:421
 GetItemInfo = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:569
 SetItemButtonTextureVertexColor = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:651
 Stock = AdiBagsBankItemButton28Stock {
 }
 Count = AdiBagsBankItemButton28Count {
 }
 SetItemLocation = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:526
 GetItem = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:596
 GetMatchesSearch = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:440
 SetItemButtonBorderVertexColor = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:647
 Reset = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:504
}
icon = AdiBagsBankItemButton28IconTexture {
 0 = <userdata>
}
tag = nil
(*temporary) = nil
(*tempor
```

It cuts off there.

Swapping to reagent bank mode produces the original visual bug above and triggers the same error. I did notice that when I swapped back I got a different error about TooltipInfo.lua. (The bank view was similarly visually bugged. Closing the bank and reopening it fixed the visuals.)

**Comment by Cidan** [comment] 2022-10-28 20:26
Fixed -- sorry, Blizzard made an undocumented change to this API, and it's difficult to track all these down individually.

Pushing .42 shortly.

**Closed by Cidan** 2022-10-28 20:26 UTC
Labels: Bug, Pending
