### ISSUE TITLE
[Feature]: Item Quality 

### ISSUE THREAD

**Issue by Jaidy88** [AdiAddons/AdiBags#856] opened 2022-12-15 07:05 UTC
### Describe the feature

Unfortunately, my English is very poor, so I don't understand the post from https://github.com/AdiAddons/AdiBags/pull/701 (https://github.com/AdiAddons/AdiBags/pull/701). What and where should I change something?

It would be really great if you could see the quality level directly in the bag and not have to hover over it with the mouse.

### Describe the implementation

Like this

![image](https://user-images.githubusercontent.com/47262722/207794791-bdeafdb4-6f01-458b-a0eb-d6b37c9610e7.png)

**Comment by Talyrius** [comment] 2022-12-15 12:22
This is a duplicate of issue #840.

**Closed by Talyrius** 2022-12-15 12:22 UTC
Labels: Duplicate
