### ISSUE TITLE
Doesnt show any content in the bags

### ISSUE THREAD

**Issue by Zesenzes** [AdiAddons/AdiBags#220] opened 2017-08-30 20:43 UTC
AdiBags doesnt show anything in my bags, since 7.3 update.

**Comment by Leinhilena** [comment] 2017-08-30 21:08
ok, when i log into wow, my adibags i open it up and nothing is there. everytime i open it i get a different error msg, here is 2 of those. 0000019761480b80 Interface\addons\adibags\containerframe.lua.424
another one ia 000002a213a1c0a0 and Interface\addons\adibags\containerframe.lua.409.
I uninstalled all and reinstalled hoping that would fix but it did not. Please help

**Comment by bcool78** [comment] 2017-08-30 21:14
I have the same issue.  Please let me know if you need logs, screenshots or whatever.

**Comment by fmneto** [comment] 2017-08-30 21:23
The problem seems to be caused by a change in how the PlaySound function works in the WoW addon API.  That function is called in lines 409 and 421 of ContainerFrame.lua (inside the widgets folder). I'm not sure if that function is called somewhere else but commenting out those lines seems to suppress the issue for now.

**Comment by aggietallboy** [comment] 2017-08-30 21:29
Line 297 can use it on a right click
Line 351 uses it if you have not unlocked the reagent bank -- I commented 351 as well

**Comment by SpareSimian** [comment] 2017-08-30 21:39
Duplicate of closed #217

**Closed** 2017-08-30 22:27 UTC
Labels: duplicate
