### ISSUE TITLE
AdiBags doesn't open at all bags

### ISSUE THREAD

**Issue by raikoug** [AdiAddons/AdiBags#797] opened 2022-11-20 16:18 UTC
### Addon Version

1.9.46

### World of Warcraft Version

Retail

### Describe the bug

Enabling AdiBags doesn't let me open bags at all.
AdiBags is the only addon loaded now.
These the errors:

```
3x AdiBags/core/Utility.lua:334: Usage: GetItemSubClassInfo(itemClassID, itemSubClassID)
[string "=[C]"]: in function `GetItemSubClassInfo'
[string "@AdiBags/core/Utility.lua"]:334: in main chunk
 
Locals:
(*temporary) = nil
(*temporary) = 0
```

```
3x AdiBags/widgets/ContainerFrame.lua:783: Usage: GetItemClassInfo(itemClassID)
[string "=[C]"]: in function `GetItemClassInfo'
[string "@AdiBags/widgets/ContainerFrame.lua"]:783: in main chunk

Locals:
(*temporary) = nil
```

```
3x AdiBags/modules/FilterOverride.lua:57: Usage: GetItemSubClassInfo(itemClassID, itemSubClassID)
[string "=[C]"]: in function `GetItemSubClassInfo'
[string "@AdiBags/modules/FilterOverride.lua"]:57: in main chunk

Locals:
(*temporary) = nil
(*temporary) = 0
```

```
3x AdiBags/modules/Junk.lua:50: Usage: GetItemSubClassInfo(itemClassID, itemSubClassID)
[string "=[C]"]: in function `GetItemSubClassInfo'
[string "@AdiBags/modules/Junk.lua"]:50: in main chunk

Locals:
(*temporary) = nil
(*temporary) = 0
```

```
3x AdiBags/core/DefaultFilters.lua:44: Usage: GetItemClassInfo(itemClassID)
[string "=[C]"]: in function `GetItemClassInfo'
[string "@AdiBags/core/DefaultFilters.lua"]:44: in function `SetupDefaultFilters'
[string "@AdiBags/core/Filters.lua"]:65: in function `InitializeFilters'
[string "@AdiBags/core/Core.lua"]:97: in function <AdiBags/core/Core.lua:81>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@AdiBags/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <...ceAdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@AdiBags/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:494: in function `InitializeAddon'
[string "@AdiBags/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:619: in function <...ceAdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:611>
```

```
17x AdiBags/core/Layout.lua:62: attempt to index field 'anchor' (a nil value)
[string "@AdiBags/core/Layout.lua"]:62: in function <AdiBags/core/Layout.lua:61>
[string "@AdiBags/core/Layout.lua"]:111: in function `LayoutBags'
[string "@AdiBags/core/Layout.lua"]:130: in function `UpdatePositionMode'
[string "@AdiBags/core/Core.lua"]:179: in function <AdiBags/core/Core.lua:122>
[string "=[C]"]: ?
[string "@AdiBags/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <...ceAdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@AdiBags/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@AdiBags/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:626: in function <...ceAdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:611>
```

```
3x AdiBags/modules/TooltipInfo.lua:55: GameTooltip doesn't have a "OnTooltipSetItem" script
[string "=[C]"]: in function `HookScript'
[string "@AdiBags/modules/TooltipInfo.lua"]:55: in function <AdiBags/modules/TooltipInfo.lua:53>
[string "=[C]"]: ?
[string "@AdiBags/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <...ceAdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@AdiBags/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@AdiBags/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:536: in function `EnableAddon'
[string "@AdiBags/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:626: in function <...ceAdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:611>
```

```
3x AdiBags/core/Utility.lua:1 (null)
3x AdiBags/widgets/ContainerFrame.lua:1 (null)
3x AdiBags/modules/FilterOverride.lua:1 (null)
3x AdiBags/modules/Junk.lua:1 (null)
3x Interface\FrameXML\Bindings.xml:1 AdiBags/core/Utility.lua:1 (null)
3x Interface\FrameXML\Bindings.xml:1 AdiBags/widgets/ContainerFrame.lua:1 (null)
3x Interface\FrameXML\Bindings.xml:1 AdiBags/modules/FilterOverride.lua:1 (null)
3x Interface\FrameXML\Bindings.xml:1 AdiBags/modules/Junk.lua:1 (null)
```

```
4x AdiBags/modules/DataSource.lua:123: attempt to call upvalue 'GetContainerNumSlots' (a nil value)
[string "@AdiBags/modules/DataSource.lua"]:123: in function <AdiBags/modules/DataSource.lua:119>
[string "@AdiBags/modules/DataSource.lua"]:152: in function `Update'
[string "@AdiBags/modules/DataSource.lua"]:78: in function <AdiBags/modules/DataSource.lua:70>
[string "=[C]"]: ?
[string "@AdiBags/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <...ceAdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@AdiBags/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@AdiBags/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:536: in function `EnableAddon'
[string "@AdiBags/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:626: in function <...ceAdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:611>
```

And clicking the bag:

```
12x AdiBags/widgets/BagSlots.lua:227: attempt to call upvalue 'ContainerIDToInventoryID' (a nil value)
[string "=(tail call)"]: ?
[string "@AdiBags/core/OO.lua"]:60: in function `Create'
[string "@AdiBags/widgets/BagSlots.lua"]:464: in function `CreateBagSlotPanel'
[string "@AdiBags/widgets/ContainerFrame.lua"]:172: in function <AdiBags/widgets/ContainerFrame.lua:98>
[string "=[C]"]: ?
[string "@AdiBags/core/Utility.lua"]:100: in function <AdiBags/core/Utility.lua:92>
[string "@AdiBags/core/OO.lua"]:60: in function <AdiBags/core/OO.lua:52>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "@AdiBags/core/Bags.lua"]:129: in function `GetFrame'
[string "@AdiBags/core/Bags.lua"]:83: in function `Open'
[string "@AdiBags/core/Bags.lua"]:119: in function <AdiBags/core/Bags.lua:115>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "@FrameXML/MainMenuBarBagButtons.lua"]:76: in function <FrameXML/MainMenuBarBagButtons.lua:66>
[string "=[C]"]: ?
```

```
3x AdiBags/widgets/Section.lua:130: attempt to call upvalue 'BuildSectionKey' (a nil value)
[string "=(tail call)"]: ?
[string "@AdiBags/core/OO.lua"]:155: in function <AdiBags/core/OO.lua:142>
[string "=(tail call)"]: ?
[string "@AdiBags/widgets/ContainerFrame.lua"]:226: in function <AdiBags/widgets/ContainerFrame.lua:98>
[string "=[C]"]: ?
[string "@AdiBags/core/Utility.lua"]:100: in function <AdiBags/core/Utility.lua:92>
[string "@AdiBags/core/OO.lua"]:60: in function <AdiBags/core/OO.lua:52>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "@AdiBags/core/Bags.lua"]:129: in function `GetFrame'
[string "@AdiBags/core/Bags.lua"]:83: in function `Open'
[string "@AdiBags/core/Bags.lua"]:119: in function <AdiBags/core/Bags.lua:115>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "@FrameXML/MainMenuBarBagButtons.lua"]:76: in function <FrameXML/MainMenuBarBagButtons.lua:66>
[string "=[C]"]: ?
```

```
3x AdiBags/widgets/ContainerFrame.lua:264: Usage: RegisterMessage("eventname", "methodname"): self was not a table?
[string "=(tail call)"]: ?
[string "@AdiBags/core/OO.lua"]:60: in function <AdiBags/core/OO.lua:52>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "@AdiBags/core/Bags.lua"]:129: in function `GetFrame'
[string "@AdiBags/core/Bags.lua"]:83: in function `Open'
[string "@AdiBags/core/Bags.lua"]:119: in function <AdiBags/core/Bags.lua:115>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "@FrameXML/MainMenuBarBagButtons.lua"]:76: in function <FrameXML/MainMenuBarBagButtons.lua:66>
[string "=[C]"]: ?
```

```
8x AdiBags/widgets/ContainerFrame.lua:638: attempt to call upvalue 'GetContainerNumSlots' (a nil value)
[string "@AdiBags/widgets/ContainerFrame.lua"]:638: in function `UpdateContent'
[string "@AdiBags/widgets/ContainerFrame.lua"]:481: in function `RefreshContents'
[string "@AdiBags/widgets/ContainerFrame.lua"]:468: in function `ResumeUpdates'
[string "@AdiBags/widgets/ContainerFrame.lua"]:451: in function <AdiBags/widgets/ContainerFrame.lua:443>
[string "=[C]"]: in function `Show'
[string "@AdiBags/core/Bags.lua"]:89: in function `Open'
[string "@AdiBags/core/Bags.lua"]:119: in function <AdiBags/core/Bags.lua:115>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "@FrameXML/MainMenuBarBagButtons.lua"]:76: in function <FrameXML/MainMenuBarBagButtons.lua:66>
[string "=[C]"]: ?

Locals:
self = AdiBagsContainer1 {
 0 = <userdata>
 firstLoad = true
 HeaderLeftRegion = AdiBagsSimpleLayeredRegion1 {
 }
 isBank = false
 OnBackdropLoaded = <function> defined @SharedXML/Backdrop.lua:152
 GetBackdropColor = <function> defined @SharedXML/Backdrop.lua:390
 SetBackdropBorderColor = <function> defined @SharedXML/Backdrop.lua:422
 BagSlotButton = CheckButton {
 }
 BottomLeftRegion = AdiBagsSimpleLayeredRegion3 {
 }
 sameChanged = <table> {
 }
 forceLayout = true
 isReagentBank = false
 ApplyBackdrop = <function> defined @SharedXML/Backdrop.lua:294
 SetBackdrop = <function> defined @SharedXML/Backdrop.lua:329
 ClearBackdrop = <function> defined @SharedXML/Backdrop.lua:282
 paused = false
 GetBackdropBorderColor = <function> defined @SharedXML/Backdrop.lua:409
 GetBackdrop = <function> defined @SharedXML/Backdrop.lua:347
 Center = Texture {
 }
 RightEdge = Texture {
 }
 LeftEdge = Texture {
 }
 content = <table> {
 }
 BottomEdge = Texture {
 }
 removed = <table> {
 }
 Anchor = AdiBagsBagAnchor1 {
 }
 itemGUIDtoItem = <table> {
 }
 sections = <table> {
 }
 BottomRightCorner = Texture {
 }
 changed = <table> {
 }
 added = <table> {
 }
 ToSortSection = AdiBagsSection1 {
 }
 BottomLeftCorner = Texture {
 }
 stacks = <table> {
 }
 SetupTextureCoordinates = <function> defined @SharedXML/Backdrop.lua:214
 OnBackdropSizeChanged = <function> defined @SharedXML/Backdrop.lua:182
 HasBackdropInfo = <function> defined @SharedXML/Backdrop.lua:278
 TopRightCorner = Texture {
 }
 TopLeftCorner = Texture {
 }
 backdropInfo = <table> {
 }
 dirtyLayout = true
 GetEdgeSize = <function> defined @SharedXML/Backdrop.lua:188
 Content = Frame {
 }
 buttons = <table> {
 }
 TopEdge = Texture {
 }
 HeaderRightRegion = AdiBagsSimpleLayeredRegion2 {
 }
 BottomRightRegion = AdiBagsSimpleLayeredRegion4 {
 }
 widgets = <table> {
 }
 SetBorderBlendMode = <function> defined @SharedXML/Backdrop.lua:266
 CloseButton = Button {
 }
 Title = AdiBagsContainer1Title {
 }
 bagObject = <table> {
 }
 SetupPieceVisuals = <function> defined @SharedXML/Backdrop.lua:246
 SetBackdropColor = <function> defined @SharedXML/Backdrop.lua:399
 BagSlotPanel = AdiBagsContainer1Bags {
 }
 name = "Backpack"
}
bag = 1
added = <table> {
}
removed = <table> {
}
changed = <table> {
}
sameChanged = <table> {
}
content = <table> {
 size = 0
}
(*temporary) = nil
(*temporary) = 1
(*temporary) = "attempt to call upvalue 'GetContainerNumSlots' (a nil value)"
GetContainerNumSlots = nil
GetContainerNumFreeSlots = nil
GetContainerItemID = nil
GetContainerItemLink = nil
addon = <table> {
 AcquireItemButton = <function> defined @AdiBags/widgets/ItemButton.lua:173
 FAMILY_TAGS = <table> {
 }
 UpdateFilters = <function> defined @AdiBags/core/Filters.lua:83
 SecureHook = <function> defined @AdiBags/libs/AceHook-3.0/AceHook-3.0.lua:335
 GetInteractingWindow = <function> defined @AdiBags/core/Core.lua:440
 ConfigChanged = <function> defined @AdiBags/core/Core.lua:360
 SetDefaultModulePrototype = <function> defined @AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:405
 Filter = <function> defined @AdiBags/core/Filters.lua:144
 IsEnabled = <function> defined @AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:447
 Reconfigure = <function> defined @AdiBags/core/Core.lua:190
 SetupTooltip = <function> defined @AdiBags/core/Utility.lua:125
 RegisterMessage = <function> defined @AdiBags/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:90
 UnregisterMessage = <function> defined @AdiBags/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:153
 hooks = <table> {
 }
 GetDistinctItemID = <function> defined @AdiBags/core/Utility.lua:301
 CreateFont = <function> defined @AdiBags/core/Fonts.lua:122
 isClassic = false
 db = <table> {
 }
 OpenOpti
```

```
18x AdiBags/core/Layout.lua:62: attempt to index field 'anchor' (a nil value)
[string "@AdiBags/core/Layout.lua"]:62: in function <AdiBags/core/Layout.lua:61>
[string "@AdiBags/core/Layout.lua"]:111: in function `LayoutBags'
[string "@AdiBags/core/Layout.lua"]:130: in function `UpdatePositionMode'
[string "@AdiBags/core/Core.lua"]:179: in function <AdiBags/core/Core.lua:122>
[string "=[C]"]: ?
[string "@AdiBags/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <...ceAdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@AdiBags/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@AdiBags/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:626: in function <...ceAdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:611>
```

```
8x AdiBags/widgets/ContainerFrame.lua:599: attempt to call method 'FullUpdate' (a nil value)
[string "=(tail call)"]: ?
[string "@AdiBags/widgets/LayeredRegion.lua"]:119: in function <AdiBags/widgets/LayeredRegion.lua:108>
```

### Steps to reproduce

Install AdiBags via curseforge

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by Cidan** [comment] 2022-11-20 17:20
Duplicate of #782

**Closed by Cidan** 2022-11-20 17:20 UTC
Labels: Bug, Pending
