### ISSUE TITLE
Bag sections containing gear sets

### ISSUE THREAD

**Issue by Stefen74** [AdiAddons/AdiBags#698] opened 2022-09-07 15:49 UTC
NOTE: Bugs can sometimes be caused by conflicts with other addons. Please disable all other addons and try to reproduce your issue. You must answer below that you have tried disabling all your addons before this bug is accepted. If you have not tried disabling all your addons, your bug will be closed.

**Describe the bug**
 - Adibags used to put bag items in separate "groups" which were named after different gear sets that they were used in. As seen on the first attached screen shot I have a few gear sets which are controlled by Outfitter. On a second screen shot you can see my bags which although contain all the items for a "Illidan Fire Resistance" set and a "Mitigation" set, they are all in one section called "Armor", trinkets and rings are all in "Jewellery", and weapons are in "Weapon".

**Expected behaviour**
 - Separate bag sections containing all the items for different gear sets.

**World of Warcraft Release and Version (Retail 9.2.7, etc)**
 - WotLK pre-patch version 3.4.0 (45435)

**AdiBags Version**
- v1.9.37

**Have you tried disabling all your other addons to ensure only this addon causes the issue?**
 - Yes

**Additional context**
 - Off the bat, this could easily be a setting that I've missed and it just needs enabling, but I've never had to, and I cannot find anything in the settings that would suggest it needs enabling. Other than that, I guess there is a chance this could be an Outfitter issue? Other than a few "fan fixes" it has been redundant and falling apart for years now, to the point where it's not really useable anymore. Still, this used to work up until WotLK pre-patch, and as surprisingly there's no other addons that look after gear sets (recommendations gratefully accepted), other than Itemrack which is also horribly broken and that rubbish built in Equipment Manager thing, I'm kind of stuck with Outfitter for a bit, and hence the bug report :)

I hope this makes sense? If not, let me know and I'll try to explain it a bit better, I used to have screen shots that showed my bags with different gear sets as as bag sections, but for the life of me I can't find them anymore :(

![image](https://user-images.githubusercontent.com/78644640/188920140-5105dc95-c714-4cd6-ae63-cef6efa1f2d4.png)

![image](https://user-images.githubusercontent.com/78644640/188920000-61b7c7eb-958f-4a48-8907-e1eaf8e0f7c7.png)

**Comment by Cidan** [comment] 2022-09-07 15:58
Duplicate of #685 -- this has been fixed and will be released in the next version.

**Closed by Cidan** 2022-09-07 15:58 UTC
Labels: Bug, Pending

**Comment by Stefen74** [comment] 2022-09-07 16:00
Thank you Cidan :)
