### ISSUE TITLE
Cannot right-click to deposit to Reagent Bank

### ISSUE THREAD

**Issue by corveroth** [AdiAddons/AdiBags#829] opened 2022-11-28 08:39 UTC
### Addon Version

1.9.47

### World of Warcraft Version

Retail

### Describe the bug

Right-clicking items in the character inventory always deposits them to the main bank, even if the bank frame is currently showing the reagent bank instead.

### Steps to reproduce

1. Open bank.
2. Click 'R' to switch to the Reagent Bank.
3. Right-click any individual item or any AdiBags header in the character inventory.
4. The selected item(s) are deposited into the main bank.

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by Talyrius** [comment] 2022-11-28 12:00
The latest version is [v1.9.48](https://github.com/AdiAddons/AdiBags/releases), not v1.9.47.

**Comment by Cidan** [comment] 2022-11-28 19:45
Confirmed this is happening in .49 as well. I'll take a look at this.

**Comment by MechaZao** [comment] 2022-12-01 18:46
adding onto this, I *can* right click into reagent bank, but *only* if the item is in an actual (not reagent) bag. The Reagent Bank and the Reagent Bag will not interact with each other, whether by the Deposit button or right clicking.

**Comment by Cidan** [comment] 2023-01-06 00:09
This is fixed in the next release, the bug was due to the reagent bank bag state being improperly held when the bank was closed, resulting in you visually seeing the reagent bank bag, but the game actually having the regular bank bag open behind the scenes. Thus, all deposits would go to the regular bank bag.

Note, there is no way to force a reagent to deposit directly to the reagent bank bag from the regular bank bag window without significant work that would probably break the addon due to the new bag taint in Dragonflight.

**Closed** 2023-01-06 01:28 UTC
Labels: Bug, Pending
