### ISSUE TITLE
Bags still closing when consuming item/selling/transferring item.

### ISSUE THREAD

**Issue by lingasharira** [AdiAddons/AdiBags#800] opened 2022-11-21 23:55 UTC
### Addon Version

v1.9.47

### World of Warcraft Version

Retail

### Describe the bug

When consuming an item or trying to sell an item (say at a vendor or on a mount) the bag interface just closes automatically. 

It also does this when depositing just one item in the bank. 

I have tried this with other addons enabled and with all addons except Adibags and it's config loader enabled. 

### Steps to reproduce

1. Try consuming an item or putting an item in the bank and/or selling an item at a vendor/mount.

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by Cidan** [comment] 2022-11-22 00:23
I'm not able to reproduce this using just the base release addon (without the community patches off of GitHub). Does this happen with .47 without any other patches?

**Comment by Nujitsu** [comment] 2022-11-22 00:54
> I'm not able to reproduce this using just the base release addon (without the community patches off of GitHub). Does this happen with .47 without any other patches?

Hi Cidan - I was able to reproduce this with withdrawing and depositing an item from/to the bank.
Also occurs when using consumables from the bag (oil, sharpening stone, agi potion).
And when selling an item to a vendor.

I am using the latest build release, and I even made sure to remove Adibags and Adibags_Config and reinstall from Curse just to be safe.

**Comment by Cidan** [comment] 2022-11-22 01:12
>  seems to be the tooltip for when you have a profession tool slot available (Blizzard's tooltip).

Can you take a screenshot of the tooltip you are talking about so I can be clear as to what you're referring to?

**Comment by lingasharira** [comment] 2022-11-22 01:37
![Wow_22_11_2022_01-36-50](https://user-images.githubusercontent.com/36503897/203195689-bb8ecb14-7d95-440d-9a25-c0f9e9c3ca08.png)

**Comment by Deznait** [comment] 2022-11-22 09:26
Hey! that fixed it for me too! Thanks for your comments, it was kind of frustating

**Comment by Gradris** [comment] 2022-11-22 23:10
Hey Cidan,

I've been able to reproduce a similar error when taking items out of the mailbox or putting items up on the AH.  Bags will just close when doing this.  I'm on version .48

**Comment by uncyspam** [comment] 2022-11-22 23:24
> able to reproduce a similar error when taking items out of the mailbox or putting items up on the AH. Bags will just close when doing this. I'm on version .48

Thanks, I can confirm this fixes the issue for me, except where I have two profession items (two mining picks in this case)
I suspect this maybe a blizz issue however, as the addon isn't throwing any errors when this occurs.

**Comment by khorne99** [comment] 2022-11-23 21:15
I was having the same problem, with only Adibags and ACP (addon control panel).  I did not have the problem with only ACP.  I did not have the problem with Arkinventory and ACP. I didn't see any profession tooltips (but that may have been dismissed in a prior session).  
I had NO tools in any of profession slots.
After putting my fishing pole in its slot the bags stopped auto closing.
After removing the fishing pole from its slot the bags no longer auto closed, even after reloading the UI, and even after exiting WoW completely and logging back in.

Thanks to those who figured out the workaround!

**Comment by MechaZao** [comment] 2022-11-25 03:02
I don't have this issue and can't reproduce it myself, but I have a friend that has the problem exactly as described.

none of my attempts at troubleshooting it for him helped -

tried reinstalling, clearing saved variables for it, running adibags on its own, disabling various settings, and tried putting profession tools in their slot. Nothing helped

the only way I was able to get it working for him was to have him completely delete adibags and saved variables for it and replace them with a zipped copy of my own addon/saved variables

it is now working perfectly for him

I'm not sure exactly why that worked, but when he installs adibags via curse it bugs out but when I do its fine.

**Comment by paultreny** [comment] 2022-11-25 04:51
> Putting my fishing rod into the tool slot in the Fising Journal fixed the bags closing bug for me :)
> 
> I can also remove it again without the bug reappearing again. So i think its save to assume it has something to do with the tooltip

Adding a fishing pole immediately fixed the issue for me as well, thanks!

**Comment by frenkye** [comment] 2022-11-27 16:18
Can confirm all proffesion items does it. After equiping crafting items the bags stop closing after using consumable, moving item, etc.

**Comment by Chipinators** [comment] 2022-11-28 16:56
Can also confirm profession equipment is the issue. Had the fishing artifact in my bags and had the auto-close issue. Moved it into my fishing profession equipment slot and it immediately fixed it without needing to relog or anything.

**Comment by Cidan** [comment] 2022-11-28 19:57
Hi everyone,

No matter which way I slice it, I simply can't reproduce this issue across multiple characters of various levels and professions. I have made a few updates to the addon since this has been reported. Can someone try to reproduce with .49, released this morning?

Thanks!

**Comment by Chipinators** [comment] 2022-11-28 20:32
My apologies I should have mentioned I was on .48

Just downloaded .49 and that seems to have fixed the issue for me.

**Comment by WaitEat** [comment] 2022-11-29 11:24
Hi downloaded .49 , issue persists, auto close every time I disenchant an item.

**Comment by thematrixincendies** [comment] 2022-11-30 11:48
Workaround for elvui users: display the bag bar (you can just show one bag and make it very small). Maybe elvui successfully hides the bag pop-ups when the bag bar is enabled?

**Comment by Lamuse1** [comment] 2022-11-30 21:45
I can confirm it is still happening with .50 as well.

**Comment by hellenisticfaun** [comment] 2022-12-01 18:10
> I can confirm it is still happening with .50 as well. I can also confirm that disabling the addon, then equipping my fishing pole to the profession has stopped it and was not getting the tooltip pop up saying about right clicking the item to open the profession window up.

I can also confirm this error & it's fix. I'm using ElvUI, so I disabled all addons & got the notification that I had a profession item to equip (my fishing pole). Once I equipped my fishing pole & turned all addons back on, no more issues!

**Comment by BastardoX** [comment] 2022-12-02 02:14
Thank you very much, I have the latest version (1.9.50) It helped to take the profession items out of the bag, so put them on. That fixed my problem.

**Comment by BourgeoisM** [comment] 2022-12-06 13:09
> Hi downloaded .49 , issue persists, auto close every time I disenchant an item.



Do you have Sorting configured for bags ? (Default Blizzard Ui, right click on bags and assign a sorting category to each bag)
As i think of the problem it may be linked !

I also have an issue of closing bags which is not the same, but it need more testing before i create an issue.

**Comment by NaZaRKIN123** [comment] 2022-12-07 22:20
still reproducible. I'm on .50

**Comment by TonyDeplanque** [comment] 2022-12-08 17:08
same problem here with the last version

**Comment by pendragon925** [comment] 2022-12-10 05:30
can confirm it's still happening .50
Equipping my grey profession items (Mining Pick, Jeweler's Toolset) did solve the issue. Just as an added note the issue also happened to ElvUI Bags when I tried disabling Adibags before equipping the profession items.

**Comment by SpareSimian** [comment] 2022-12-10 05:45
What screen resolution or window size do you use when you see the problem? I have yet to see it with no profession items equipped but I run in a window on a 4k screen and the window is about 2/3 the size of the display. My AdiBags frame is perhaps 1/3 the window width with 4 30-slot bags mostly full and separate sections for each subcategory and wearable slot.

**Comment by Cidan** [comment] 2022-12-10 19:16
Hi everyone,

I think I have a fix for this, and will be pushing out a fix in .51 soon.

Thanks!

**Comment by kurukis** [comment] 2022-12-23 04:52
> Putting my fishing rod into the tool slot in the Fising Journal fixed the bags closing bug for me :)
> 
> I can also remove it again without the bug reappearing again. So i think its save to assume it has something to do with the tooltip

Thanks for this, this did the trick for me :) Using .50.

**Closed** 2023-01-05 00:11 UTC
Labels: Bug, Fixed/Implemented
