### ISSUE TITLE
Pawn's upgrade arrow not shown when using Adibags

### ISSUE THREAD

**Issue by Mrhgb** [AdiAddons/AdiBags#167] opened 2017-03-09 23:43 UTC
Usually Pawn will put a green up arrow on items that are an upgrade for you but after switching to Adibags I no longer get this, could you please make your addon compatible with Pawn?

**Comment by Zarggg** [comment] 2017-03-11 04:55
@Adirelle has been absent for a while, but a solution has been posted in issue #156 if you're willing to edit the LUA files yourself.

**Comment by Talyrius** [comment] 2017-03-31 17:34
This is a duplicate of #151.

**Closed by Talyrius** 2017-03-31 17:34 UTC
Labels: duplicate
