### ISSUE TITLE
Game freezing and crashing when I click the sort button

### ISSUE THREAD

**Issue by kelisikelly** [AdiAddons/AdiBags#159] opened 2017-01-24 23:07 UTC
I have just installed this addon, and I like it, but whenever I click the sort button, it crashes my game and totally resets all of my settings upon restart of the game client.

How can I fix this so that it saves my settings and does not crash?

Thanks

**Comment by Blazernut** [comment] 2017-01-28 14:29
I've been having the same problem since installing the addon in patch 7.1

**Comment by gi2k15** [comment] 2017-02-05 18:06
Same here too.

**Comment by lorddev** [comment] 2017-03-09 01:35
I have this issue as well.

**Comment by josephtylerbrowning** [comment] 2017-03-14 16:03
+1 same issue as gi2k15 mentioned.

**Comment by Talyrius** [comment] 2017-03-31 17:47
Duplicate of #137.

**Closed by Talyrius** 2017-03-31 17:47 UTC
Labels: duplicate
