### ISSUE TITLE
Bags won't open. 10.2

### ISSUE THREAD

**Issue by TylerHelsel** [AdiAddons/AdiBags#793] opened 2022-11-19 15:09 UTC
### Addon Version

1.9.46

### World of Warcraft Version

Retail

### Describe the bug

Pressing B does not open the bags, nor does clicking on the Bag UI icon. I have tried wit my normal addons activated and no addons except for AdiBags activated. I also cannot access the configuration menu by typing "/adibags", I can only access it via the Addon menu. 

1x Interface/AddOns/AdiBags/widgets/ContainerFrame.lua:599: attempt to call method 'FullUpdate' (a nil value)
[string "=(tail call)"]: ?
[string "@Interface/AddOns/AdiBags/widgets/LayeredRegion.lua"]:119: in function <Interface/AddOns/AdiBags/widgets/LayeredRegion.lua:108>

### Steps to reproduce

Attempt to open bags via hotkey or manually clicking the bag icon. 

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by SpareSimian** [comment] 2022-11-19 15:49
Duplicate of bug #782.

**Comment by trebleta** [comment] 2022-11-19 19:12
Same

**Comment by Cidan** [comment] 2022-11-20 00:15
Duplicate of #782

**Closed** 2022-11-20 00:15 UTC
Labels: Bug, Pending
