### ISSUE TITLE
Adibags stops working on 10.0.2.46259 (WOW DragonFlight Beta)

### ISSUE THREAD

**Issue by jillaya** [AdiAddons/AdiBags#744] opened 2022-10-29 06:48 UTC
Game version: 10.0.2.46259 (WOW DF Beta)

Addon version: AdiBags-v1.9.44.zip

Description: It works perfectly on Pre-patch live (10.0.0), but maybe Blizzard changes something between Pre-patch and Beta, AdiBags stops working on Beta, and I'm afraid when live goes to 10.0.2, the same issue will happen.

I only enable AdiBags and AdiBags Configuration, when I open my bag, the UI looks like this (my bag is not empty:
![image](https://user-images.githubusercontent.com/17285473/198817865-7feafd69-9fff-4d10-afe3-febeb54baca7.png)

_(There are 16 Lua Errors right after I login (without opening bag), I guess they are not important but if anyone would like to see them, I can update.)_

And there are 6 Lua Errors:

**#1** 
Message: Interface/AddOns/AdiBags/modules/DataSource.lua:123: attempt to call upvalue 'GetContainerNumSlots' (a nil value)
Time: Fri Oct 28 23:42:26 2022
Count: 1
Stack: Interface/AddOns/AdiBags/modules/DataSource.lua:123: attempt to call upvalue 'GetContainerNumSlots' (a nil value)
[string "@Interface/AddOns/AdiBags/modules/DataSource.lua"]:152: in function <Interface/AddOns/AdiBags/modules/DataSource.lua:151>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "@Interface/AddOns/AdiBags/core/EventHandlers.lua"]:81: in function <Interface/AddOns/AdiBags/core/EventHandlers.lua:78>

**#2**
Message: Interface/AddOns/AdiBags/widgets/BagSlots.lua:227: attempt to call upvalue 'ContainerIDToInventoryID' (a nil value)
Time: Fri Oct 28 23:42:36 2022
Count: 4
Stack: Interface/AddOns/AdiBags/widgets/BagSlots.lua:227: attempt to call upvalue 'ContainerIDToInventoryID' (a nil value)
[string "=(tail call)"]: ?
[string "@Interface/AddOns/AdiBags/core/OO.lua"]:60: in function `Create'
[string "@Interface/AddOns/AdiBags/widgets/BagSlots.lua"]:464: in function `CreateBagSlotPanel'
[string "@Interface/AddOns/AdiBags/widgets/ContainerFrame.lua"]:172: in function <Interface/AddOns/AdiBags/widgets/ContainerFrame.lua:98>
[string "=[C]"]: ?
[string "@Interface/AddOns/AdiBags/core/Utility.lua"]:100: in function <Interface/AddOns/AdiBags/core/Utility.lua:92>
[string "@Interface/AddOns/AdiBags/core/OO.lua"]:60: in function <Interface/AddOns/AdiBags/core/OO.lua:52>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "@Interface/AddOns/AdiBags/core/Bags.lua"]:129: in function `GetFrame'
[string "@Interface/AddOns/AdiBags/core/Bags.lua"]:83: in function `Open'
[string "@Interface/AddOns/AdiBags/core/Bags.lua"]:119: in function <Interface/AddOns/AdiBags/core/Bags.lua:115>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "@Interface/FrameXML/MainMenuBarBagButtons.lua"]:76: in function <Interface/FrameXML/MainMenuBarBagButtons.lua:66>
[string "=[C]"]: ?

**#3**
Message: Interface/AddOns/AdiBags/widgets/Section.lua:130: attempt to call upvalue 'BuildSectionKey' (a nil value)
Time: Fri Oct 28 23:42:36 2022
Count: 1
Stack: Interface/AddOns/AdiBags/widgets/Section.lua:130: attempt to call upvalue 'BuildSectionKey' (a nil value)
[string "=(tail call)"]: ?
[string "@Interface/AddOns/AdiBags/core/OO.lua"]:155: in function <Interface/AddOns/AdiBags/core/OO.lua:142>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/AdiBags/widgets/ContainerFrame.lua"]:226: in function <Interface/AddOns/AdiBags/widgets/ContainerFrame.lua:98>
[string "=[C]"]: ?
[string "@Interface/AddOns/AdiBags/core/Utility.lua"]:100: in function <Interface/AddOns/AdiBags/core/Utility.lua:92>
[string "@Interface/AddOns/AdiBags/core/OO.lua"]:60: in function <Interface/AddOns/AdiBags/core/OO.lua:52>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "@Interface/AddOns/AdiBags/core/Bags.lua"]:129: in function `GetFrame'
[string "@Interface/AddOns/AdiBags/core/Bags.lua"]:83: in function `Open'
[string "@Interface/AddOns/AdiBags/core/Bags.lua"]:119: in function <Interface/AddOns/AdiBags/core/Bags.lua:115>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "@Interface/FrameXML/MainMenuBarBagButtons.lua"]:76: in function <Interface/FrameXML/MainMenuBarBagButtons.lua:66>
[string "=[C]"]: ?

**#4**
Message: Interface/AddOns/AdiBags/widgets/ContainerFrame.lua:264: Usage: RegisterMessage("eventname", "methodname"): self was not a table?
Time: Fri Oct 28 23:42:36 2022
Count: 1
Stack: Interface/AddOns/AdiBags/widgets/ContainerFrame.lua:264: Usage: RegisterMessage("eventname", "methodname"): self was not a table?
[string "=(tail call)"]: ?
[string "@Interface/AddOns/AdiBags/core/OO.lua"]:60: in function <Interface/AddOns/AdiBags/core/OO.lua:52>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "@Interface/AddOns/AdiBags/core/Bags.lua"]:129: in function `GetFrame'
[string "@Interface/AddOns/AdiBags/core/Bags.lua"]:83: in function `Open'
[string "@Interface/AddOns/AdiBags/core/Bags.lua"]:119: in function <Interface/AddOns/AdiBags/core/Bags.lua:115>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "@Interface/FrameXML/MainMenuBarBagButtons.lua"]:76: in function <Interface/FrameXML/MainMenuBarBagButtons.lua:66>
[string "=[C]"]: ?

**#5** 
Message: Interface/AddOns/AdiBags/widgets/ContainerFrame.lua:638: attempt to call upvalue 'GetContainerNumSlots' (a nil value)
Time: Fri Oct 28 23:42:36 2022
Count: 1
Stack: Interface/AddOns/AdiBags/widgets/ContainerFrame.lua:638: attempt to call upvalue 'GetContainerNumSlots' (a nil value)
[string "@Interface/AddOns/AdiBags/widgets/ContainerFrame.lua"]:638: in function `UpdateContent'
[string "@Interface/AddOns/AdiBags/widgets/ContainerFrame.lua"]:481: in function `RefreshContents'
[string "@Interface/AddOns/AdiBags/widgets/ContainerFrame.lua"]:468: in function `ResumeUpdates'
[string "@Interface/AddOns/AdiBags/widgets/ContainerFrame.lua"]:451: in function <Interface/AddOns/AdiBags/widgets/ContainerFrame.lua:443>
[string "=[C]"]: in function `Show'
[string "@Interface/AddOns/AdiBags/core/Bags.lua"]:89: in function `Open'
[string "@Interface/AddOns/AdiBags/core/Bags.lua"]:119: in function <Interface/AddOns/AdiBags/core/Bags.lua:115>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "@Interface/FrameXML/MainMenuBarBagButtons.lua"]:76: in function <Interface/FrameXML/MainMenuBarBagButtons.lua:66>
[string "=[C]"]: ?

Locals: self = AdiBagsContainer1 {
 0 = <userdata>
 firstLoad = true
 HeaderLeftRegion = AdiBagsSimpleLayeredRegion1 {
 }
 isBank = false
 OnBackdropLoaded = <function> defined @Interface/SharedXML/Backdrop.lua:152
 GetBackdropColor = <function> defined @Interface/SharedXML/Backdrop.lua:390
 SetBackdropBorderColor = <function> defined @Interface/SharedXML/Backdrop.lua:422
 BagSlotButton = CheckButton {
 }
 BottomLeftRegion = AdiBagsSimpleLayeredRegion3 {
 }
 sameChanged = <table> {
 }
 forceLayout = true
 isReagentBank = false
 ApplyBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:294
 SetBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:329
 ClearBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:282
 paused = false
 GetBackdropBorderColor = <function> defined @Interface/SharedXML/Backdrop.lua:409
 GetBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:347
 Center = Texture {
 }
 RightEdge = Texture {
 }
 LeftEdge = Texture {
 }
 content = <table> {
 }
 BottomEdge = Texture {
 }
 removed = <table> {
 }
 Anchor = AdiBagsBagAnchor1 {
 }
 itemGUIDtoItem = <table> {
 }
 sections = <table> {
 }
 BottomRightCorner = Texture {
 }
 changed = <table> {
 }
 added = <table> {
 }
 ToSortSection = AdiBagsSection1 {
 }
 BottomLeftCorner = Texture {
 }
 stacks = <table> {
 }
 SetupTextureCoordinates = <function> defined @Interface/SharedXML/Backdrop.lua:214
 OnBackdropSizeChanged = <function> defined @Interface/SharedXML/Backdrop.lua:182
 HasBackdropInfo = <function> defined @Interface/SharedXML/Backdrop.lua:278
 TopRightCorner = Texture {
 }
 TopLeftCorner = Texture {
 }
 backdropInfo = <table> {
 }
 dirtyLayout = true
 GetEdgeSize = <function> defined @Interface/SharedXML/Backdrop.lua:188
 Content = Frame {
 }
 buttons = <table> {
 }
 TopEdge = Texture {
 }
 HeaderRightRegion = AdiBagsSimpleLayeredRegion2 {
 }
 BottomRightRegion = AdiBagsSimpleLayeredRegion4 {
 }
 widgets = <table> {
 }
 SetBorderBlendMode = <function> defined @Interface/SharedXML/Backdrop.lua:266
 CloseButton = Button {
 }
 Title = AdiBagsContainer1Title {
 }
 bagObject = <table> {
 }
 SetupPieceVisuals = <function> defined @Interface/SharedXML/Backdrop.lua:246
 SetBackdropColor = <function> defined @Interface/SharedXML/Backdrop.lua:399
 BagSlotPanel = AdiBagsContainer1Bags {
 }
 name = "Backpack"
}
bag = 1
added = <table> {
}
removed = <table> {
}
changed = <table> {
}
sameChanged = <table> {
}
content = <table> {
 size = 0
}
(*temporary) = nil
(*temporary) = 1
(*temporary) = "attempt to call upvalue 'GetContainerNumSlots' (a nil value)"
GetContainerNumSlots = nil
GetContainerNumFreeSlots = nil
GetContainerItemID = nil
GetContainerItemLink = nil
addon = <table> {
 AcquireItemButton = <function> defined @Interface/AddOns/AdiBags/widgets/ItemButton.lua:173
 FAMILY_TAGS = <table> {
 }
 UpdateFilter

**#6**
Message: Interface/AddOns/AdiBags/widgets/ContainerFrame.lua:599: attempt to call method 'FullUpdate' (a nil value)
Time: Fri Oct 28 23:42:36 2022
Count: 1
Stack: Interface/AddOns/AdiBags/widgets/ContainerFrame.lua:599: attempt to call method 'FullUpdate' (a nil value)
[string "=(tail call)"]: ?
[string "@Interface/AddOns/AdiBags/widgets/LayeredRegion.lua"]:119: in function <Interface/AddOns/AdiBags/widgets/LayeredRegion.lua:108>

**Comment by Cidan** [comment] 2022-10-29 06:58
Duplicate of #732

**Closed by Cidan** 2022-10-29 06:58 UTC
Labels: Bug, Pending
