### ISSUE TITLE
ItemLevel.lua:466: bad argument #1 to 'unpack' (table expected, got nil)

### ISSUE THREAD

**Issue by gameowen** [AdiAddons/AdiBags#834] opened 2022-11-29 16:59 UTC
### Addon Version

v1.9.49

### World of Warcraft Version

Retail

### Describe the bug

Message: Interface/AddOns/AdiBags/modules/ItemLevel.lua:466: bad argument #1 to 'unpack' (table expected, got nil)
Time: Wed Nov 30 00:53:27 2022
Count: 2
Stack: Interface/AddOns/AdiBags/modules/ItemLevel.lua:466: bad argument #1 to 'unpack' (table expected, got nil)
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "@Interface/AddOns/AdiBags/modules/ItemLevel.lua"]:466: in function `?'
[string "@Interface/AddOns/AdiBags/modules/ItemLevel.lua"]:170: in function `UpdateButton_Retail'
[string "@Interface/AddOns/AdiBags/modules/ItemLevel.lua"]:131: in function `?'
[string "@Interface/AddOns/AdiBags/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:119: in function <...ags/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Interface/AddOns/AdiBags/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:29: in function <...ags/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:25>
[string "@Interface/AddOns/AdiBags/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:64: in function `SendMessage'
[string "@Interface/AddOns/AdiBags/widgets/ItemButton.lua"]:348: in function `Update'
[string "@Interface/AddOns/AdiBags/widgets/ItemButton.lua"]:315: in function `FullUpdate'
[string "@Interface/AddOns/AdiBags/widgets/ItemButton.lua"]:273: in function <Interface/AddOns/AdiBags/widgets/ItemButton.lua:261>
[string "=[C]"]: in function `Show'
[string "@Interface/AddOns/AdiBags/core/Bags.lua"]:96: in function `Open'
[string "@Interface/AddOns/AdiBags/core/Hooks.lua"]:115: in function <Interface/AddOns/AdiBags/core/Hooks.lua:112>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "OPENALLBAGS"]:1: in function <[string "OPENALLBAGS"]:1>

Locals: <none>

### Steps to reproduce

1. Open the bug
2. got the error message

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by Discobuble** [comment] 2022-11-29 18:17
Having the same issue

**Comment by husskhash** [comment] 2022-11-29 18:46
same here

**Comment by nulian** [comment] 2022-11-29 18:53
ilvl range is missing you can add this to itemlvl.lua at line 349.
```
[70] = { 300, 425 },
```

**Comment by jacho981** [comment] 2022-11-29 19:16
same

```
1520x AdiBags/modules/ItemLevel.lua:466: bad argument #1 to 'unpack' (table expected, got nil)
[string "=[C]"]: ?
[string "@AdiBags/modules/ItemLevel.lua"]:466: in function `?'
[string "@AdiBags/modules/ItemLevel.lua"]:170: in function `UpdateButton_Retail'
[string "@AdiBags/modules/ItemLevel.lua"]:131: in function `?'
[string "@LibSharedMedia-3.0-8020003/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:119: in function <...edia-3.0/CallbackHandler-1.0/CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@LibSharedMedia-3.0-8020003/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:29: in function <...edia-3.0/CallbackHandler-1.0/CallbackHandler-1.0.lua:25>
[string "@LibSharedMedia-3.0-8020003/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:64: in function `SendMessage'
[string "@AdiBags/widgets/ItemButton.lua"]:348: in function `Update'
[string "@AdiBags/widgets/ItemButton.lua"]:315: in function `FullUpdate'
[string "@AdiBags/widgets/ItemButton.lua"]:273: in function <AdiBags/widgets/ItemButton.lua:261>
[string "=[C]"]: in function `Show'
[string "@AdiBags/core/Bags.lua"]:96: in function `Open'
[string "@AdiBags/core/Hooks.lua"]:115: in function <AdiBags/core/Hooks.lua:112>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "OPENALLBAGS"]:1: in function <[string "OPENALLBAGS"]:1>
```

**Comment by Cidan** [comment] 2022-11-29 20:51
Fixed in .50, which is going out as we speak -- check the release page in a few minutes, and curse, et al a bit after that.

Thanks!

**Closed by Cidan** 2022-11-29 20:51 UTC
Labels: Bug, Pending

**Comment by Talyrius** [comment] 2022-11-30 09:15
Duplicate of #818.
