### ISSUE TITLE
Bank Bags - Reagent Bag Not Opening

### ISSUE THREAD

**Issue by GirlPlays** [AdiAddons/AdiBags#961] opened 2023-05-22 00:32 UTC
### Addon Version

10.10.10

### World of Warcraft Version

Retail

### Describe the bug

When I open bank bags, then try to swap to reagent bag, it does not switch to reagent bag. 
Then when I close the bank, I can no longer hit escape to open game menu. 
When I hit escape, the menu does not open. 

### Steps to reproduce

1. Open bank
2. Select R to switch to Reagent bag 
3. Does not switch
4. Close bank
5. Can no longer open game menu with escape

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by GirlPlays** [comment] 2023-05-22 00:33
Correction: v1.10.10

**Comment by Cidan** [comment] 2023-05-22 00:35
I can't reproduce this in 1.10.10 (it was a bug in 1.10.9). Do you have buggrabber/bugsack installed?

**Comment by GirlPlays** [comment] 2023-05-22 00:36
I do not. Where can I pick it up?

**Comment by Cidan** [comment] 2023-05-22 00:38
https://www.curseforge.com/wow/addons/bug-grabber
https://www.curseforge.com/wow/addons/bugsack

Also double check that you have 1.10.10 and you've restarted WoW after installing.

**Comment by GirlPlays** [comment] 2023-05-22 00:39
I just closed wow.
uninstalled 
made sure the folders in the addons were gone
reinstalled adibags
loaded wow 

and got a Lua Warning

Message: Interface\FrameXML\Bindings.xml:1 Error loading WTF/Account/ACCOUNTNAME/SavedVariables/AdiBags.lua
Time: Sun May 21 19:38:14 2023
Count: 1

**Comment by Cidan** [comment] 2023-05-22 00:41
This is an odd issue -- your actual settings file is corrupted, which is hosted outside the addon folder. Can you move that file elsewhere and try again?

**Comment by GirlPlays** [comment] 2023-05-22 00:42
Sure. Which file specifically?

**Comment by Cidan** [comment] 2023-05-22 00:44
The one in that error message:

`WTF/Account/ACCOUNTNAME/SavedVariables/AdiBags.lua`, which should be in your WoW retail folder. This file is the configuration file that is generated by the WoW client, and holds all your AdiBags settings. By deleting it, you will lose your settings. I am not sure why the game is reporting it as corrupted.

**Comment by GirlPlays** [comment] 2023-05-22 00:45
I have a back up saved from yesterday before the error occurred. I will delete that folder then paste my backup to see if that works.

**Comment by GirlPlays** [comment] 2023-05-22 00:49
The bank is allowing me to swap between the main bags and reagent bags, but it is still interfering
 with the game menu; escape no longer works after I go into the bank

**Comment by GirlPlays** [comment] 2023-05-22 00:49
so deleting my folder and pasting an old backup has not resolved :/

**Comment by Cidan** [comment] 2023-05-22 00:50
Hm, alright, let me check a few things. Sit tight.

**Comment by GirlPlays** [comment] 2023-05-22 01:26
not sure if it helps, but reloading the UI seems to fix the issue, but as soon as I open the bank again, escape no longer opens the menu again :/

Also, when I first open the bank, it never sorts the items and puts a large portion of them into the MISC section. But when I hit "Sort" it then fixes the issue, but it is not doing it automatically either.

**Comment by Cidan** [comment] 2023-05-22 01:52
Alright, fixed in 1.10.11, which is going out now. This will fix the escape window issue, as it was sometimes triggering and sometimes not.

The items not being in categories is a known issue that is unrelated, and is something that will take considerable effort to fix -- we'll get to this in a future update.

Thanks for your report!

**Closed by Cidan** 2023-05-22 01:52 UTC
Labels: Bug, Pending
