### ISSUE TITLE
can't open bag

### ISSUE THREAD

**Issue by muturama** [AdiAddons/AdiBags#337] opened 2019-03-13 18:27 UTC
i caan't open my bag 
![e36d4549d6331891467c166b97bda416](https://user-images.githubusercontent.com/48529991/54304721-0c142a00-45c6-11e9-817d-eac1d272dfd8.png)

**Comment by SpareSimian** [comment] 2019-03-13 18:44
Duplicate of (fixed) bug #332. Download the new version.

**Closed** 2019-03-13 18:46 UTC
Labels: Invalid
