### ISSUE TITLE
Sorting by "quality and item level" not working?

### ISSUE THREAD

**Issue by kdubato** [AdiAddons/AdiBags#256] opened 2018-01-01 17:20 UTC
I noticed that when I switched the sort order to "Quality and item level", it doesn't actually sort each section by item level when all items are of the same quality.

The following screenshot shows three highlighted sections, all with the same quality, but not sorted by item level ... Unless I'm missing something?

![image](https://user-images.githubusercontent.com/987601/34469488-ad75db0c-eee5-11e7-8692-0830170adca8.png)

**Comment by Talyrius** [comment] 2018-01-01 18:11
Duplicate of #140.

**Closed by Talyrius** 2018-01-01 18:11 UTC
Labels: Duplicate
