### ISSUE TITLE
Error on load, reload

### ISSUE THREAD

**Issue by timwayne** [AdiAddons/AdiBags#315] opened 2018-11-13 02:25 UTC
Error

Date: 2018-11-12 18:21:50
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\AdiBags\core\Filters.lua line 126:
   Usage: NewModule(name, [prototype, [lib, lib, lib, ...]): 'name' - Module 'Bound' already exists.
Debug:
   [C]: ?
   ...ce\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:270: NewModule()
   AdiBags\core\Filters.lua:126: RegisterFilter()
   AdiBags_Bound\AdiBags_Bound.lua:52: in main chunk
Locals:
(*temporary) = "Usage: NewModule(name, [prototype, [lib, lib, lib, ...]): 'name' - Module 'Bound' already exists."

AddOns:
  Swatter, v8.0.6162 (SwimmingSeadragon)
  AdiBags, vv1.9.11
  AdiBagsArchaeology, v8.0-release1
  AdiBagsArmourType, vv1.0
  AdiBagsArtifactWeapons, v1.0
  AdiBagsAzeriteGear, v0.2
  AdiBagsBattlePetItems, vv1.0.0
  AdiBagsBoEBoA, vv1.5
  AdiBagsBound, vv1.1
  BlizRuntimeLib_enUS v8.0.1.80000 <none>
  (ck=13a)

---------------------------------------------

Date: 2018-11-12 18:21:50
ID: 2
Error occured in: Global
Count: 1
Message: ..\AddOns\AdiBags\core\Filters.lua line 126:
   Usage: NewModule(name, [prototype, [lib, lib, lib, ...]): 'name' - Module 'Legion' already exists.
Debug:
   [C]: ?
   ...ce\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:270: NewModule()
   AdiBags\core\Filters.lua:126: RegisterFilter()
   AdiBags_Legion\AdiBags_Legion.lua:121: in main chunk
Locals:
(*temporary) = "Usage: NewModule(name, [prototype, [lib, lib, lib, ...]): 'name' - Module 'Legion' already exists."

AddOns:
  Swatter, v8.0.6162 (SwimmingSeadragon)
  AdiBags, vv1.9.11
  AdiBagsArchaeology, v8.0-release1
  AdiBagsArmourType, vv1.0
  AdiBagsArtifactWeapons, v1.0
  AdiBagsAzeriteGear, v0.2
  AdiBagsBattlePetItems, vv1.0.0
  AdiBagsBoEBoA, vv1.5
  AdiBagsBound, vv1.1
  AdiBagsByExpansion, v1.0.0
  AdiBagsByExpansionBfA, v1.0.0
  AdiBagsByExpansionCata, v1.0.0
  AdiBagsByExpansionLegion, v1.0.0
  AdiBagsByExpansionMoP, v1.0.0
  AdiBagsByExpansionTBC, v1.0.0
  AdiBagsByExpansionWoD, v1.0.0
  AdiBagsByExpansionWoW, v1.0.0
  AdiBagsByExpansionWrath, v1.0.0
  AdiBagsExpansionTradeGoods, v1.2
  AdiBagsGarrison, vv1.6
  AdiBagsHearthstones, v7.3-release1
  AdiBagsHerbalism, vv0.1
  AdiBagsLegion, vv1.6
  BlizRuntimeLib_enUS v8.0.1.80000 <none>
  (ck=2ef)

---------------------------------------------
Date: 2018-11-12 18:21:50
ID: 3
Error occured in: Global
Count: 1
Message: ..\AddOns\AdiBags\core\Filters.lua line 128:
   Usage: NewModule(name, [prototype, [lib, lib, lib, ...]): 'name' - Module 'Legion' already exists.
Debug:
   [C]: ?
   ...ce\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:270: NewModule()
   AdiBags\core\Filters.lua:128: RegisterFilter()
   ...ns\AdiBags_Legion_Filters\AdiBags_Legion_Filters.lua:65: in main chunk
Locals:
(*temporary) = "Usage: NewModule(name, [prototype, [lib, lib, lib, ...]): 'name' - Module 'Legion' already exists."

AddOns:
  Swatter, v8.0.6162 (SwimmingSeadragon)
  AdiBags, vv1.9.11
  AdiBagsArchaeology, v8.0-release1
  AdiBagsArmourType, vv1.0
  AdiBagsArtifactWeapons, v1.0
  AdiBagsAzeriteGear, v0.2
  AdiBagsBattlePetItems, vv1.0.0
  AdiBagsBoEBoA, vv1.5
  AdiBagsBound, vv1.1
  AdiBagsByExpansion, v1.0.0
  AdiBagsByExpansionBfA, v1.0.0
  AdiBagsByExpansionCata, v1.0.0
  AdiBagsByExpansionLegion, v1.0.0
  AdiBagsByExpansionMoP, v1.0.0
  AdiBagsByExpansionTBC, v1.0.0
  AdiBagsByExpansionWoD, v1.0.0
  AdiBagsByExpansionWoW, v1.0.0
  AdiBagsByExpansionWrath, v1.0.0
  AdiBagsExpansionTradeGoods, v1.2
  AdiBagsGarrison, vv1.6
  AdiBagsHearthstones, v7.3-release1
  AdiBagsHerbalism, vv0.1
  AdiBagsLegion, vv1.6
  AdiBagsLegionFilters, v1.6.9
  BlizRuntimeLib_enUS v8.0.1.80000 <none>
  (ck=30e)

---------------------------------------------
Date: 2018-11-12 18:24:57
ID: 4
Error occured in: Global
Count: 1
Message: ..\AddOns\_NPCScan.Overlay\Overlay.lua line 701:
   attempt to call field 'SetMapByID' (a nil value)
Debug:
   (tail call): ?
   _NPCScan.Overlay\Overlay.lua:701: ?()
   ...ags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119:
      ...ags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119
   [C]: ?
   ...ags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:29:
      ...ags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25
   ...ags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:64: Fire()
   ...AddOns\AskMrRobot\Libs\AceEvent-3.0\AceEvent-3.0.lua:120:
      ...AddOns\AskMrRobot\Libs\AceEvent-3.0\AceEvent-3.0.lua:119
Locals:
None
AddOns:
  Swatter, v8.0.6162 (SwimmingSeadragon)
  NPCScanOverlay, v7.3.0.1
  AdiBags, vv1.9.11
  AdiBagsArchaeology, v8.0-release1
  AdiBagsArmourType, vv1.0
  AdiBagsArtifactWeapons, v1.0
  AdiBagsAzeriteGear, v0.2
  AdiBagsBattlePetItems, vv1.0.0
  AdiBagsBoEBoA, vv1.5
  AdiBagsBound, vv1.1
  AdiBagsByExpansion, v1.0.0
  AdiBagsByExpansionBfA, v1.0.0
  AdiBagsByExpansionCata, v1.0.0
  AdiBagsByExpansionLegion, v1.0.0
  AdiBagsByExpansionMoP, v1.0.0
  AdiBagsByExpansionTBC, v1.0.0
  AdiBagsByExpansionWoD, v1.0.0
  AdiBagsByExpansionWoW, v1.0.0
  AdiBagsByExpansionWrath, v1.0.0
  AdiBagsExpansionTradeGoods, v1.2
  AdiBagsfishing, v2.0
  AdiBagsGarrison, vv1.6
  AdiBagsHearthstones, v7.3-release1
  AdiBagsHerbalism, vv0.1
  AdiBagsLegion, vv1.6
  AdiBagsLegionFilters, v1.6.9
  AdiBagslootboxes, v0.8-7.3-release
  AdiBagsLowlevel, v0.3
  AdiBagsOutfitter, vv1.5.2
  AdiBagsPT3Filter, vv1.4.2
  AdiBagsRevelry, v0.9k
  AdiBagsTackleBox, v1.0.2
  AdiBagsTSM, v0.4
  AdiBagsTSMAuctions, vv1.0
  AllTheThings, v1.7.4
  AskMrRobot, v67
  AucAdvanced, v8.0.6122 (SwimmingSeadragon)
  AucFilterBasic, v8.0.6149 (SwimmingSeadragon)
  AucStatHistogram, v8.0.6151 (SwimmingSeadragon)
  AucStatiLevel, v8.0.6155 (SwimmingSeadragon)
  AucStatPurchased, v8.0.6152 (SwimmingSeadragon)
  AucStatSimple, v8.0.6153 (SwimmingSeadragon)
  AucStatStdDev, v8.0.6154 (SwimmingSeadragon)
  AucUtilFixAH, v8.0.6156 (SwimmingSeadragon)
  Auctionator, v5.0.5
  Bartender4, v4.8.1
  BeanCounter, v8.0.6157 (SwimmingSeadragon)
  BrokerCloth, v1.7
  BrokerWallet, v8.0.1
  CaerdonSpecBroker, vv0.1.0
  CaerdonWardrobe, vv2.1.3
  Chatter, v1.5.8
  Coordinates, v2.03
  DBMCore, v8.0.15
  DBMDefaultSkin, v
  DBMInterrupts, v7.3.0
  DBMStatusBarTimers, v
  DBMVPEnglishfemale, v8.0.6
  DBMVPVEM, v8.0.5
  GreenWall, v1.9.8
  GTFO, v4.46.9
  LookingForGroup, vr1560
  LookingForGroupBindings, vr1560
  LookingForGroupBroker, vr1560
  LookingForGroupEvent, vr1560
  LookingForGroupHook, vr1560
  LookingForGroupIcon, vr1560
  LookingForGroupSF, vr1560
  MageNuggets, v6.1.1
  MageNuggetsCooldownMonitor, v6.0.2
  MageNuggetsStatMonitor, v6.0.2
  NPCScan, v8.0.1.13
  Outfitter, v5.21
  Overachiever, v1.0.4
  OverachieverCache, v1.0.4
  Pawn, v2.2.31
  PetTracker, v8.0.6
  PetTrackerBreeds, v8.0.6
  PetTrackerSwitcher, v8.0.6
  PetTrackerUpgrades, v8.0.6
  Postal, vv3.6.0
  RaidAchievement, v
  Skada, v1.7.5
  SlideBar, v8.0.6160 (SwimmingSeadragon)
  Stubby, v8.0.6161 (SwimmingSeadragon)
  Titan, v5.14.12.80000
  TitanBag, v5.14.12.80000
  TitanClock, v5.14.12.80000
  TitanGold, v5.14.12.80000
  TitanJewelcrafting, v4.0.001
  TitanLocation, v5.14.12.80000
  TitanLootType, v5.14.12.80000
  TitanPerformance, v5.14.12.80000
  TitanRepair, v5.14.12.80000
  TitanTailoring, v4.0.001
  TitanVolume, v5.14.12.80000
  TitanXP, v5.14.12.80000
  TomTom, vv80001-1.0.2
  TradeSkillMaster, vv4.5.2
  TradeSkillMasterAppHelper, vv4.0
  BlizRuntimeLib_enUS v8.0.1.80000 <none>
  (ck=b8c)

---------------------------------------------

**Comment by Talyrius** [comment] 2018-11-13 04:33
This error is due to conflicting module names being used by other AdiBags addons. I suggest you remove one of them.

Duplicate of #51.

**Closed by Talyrius** 2018-11-13 04:33 UTC
Labels: Duplicate
