### ISSUE TITLE
Issue with GetBagID

### ISSUE THREAD

**Issue by zaldor30** [AdiAddons/AdiBags#728] opened 2022-10-27 01:30 UTC
NOTE: Bugs can sometimes be caused by conflicts with other addons. Please disable all other addons and try to reproduce your issue. You must answer below that you have tried disabling all your addons before this bug is accepted. If you have not tried disabling all your addons, your bug will be closed.

**Describe the bug**
When actively pulling items form the bag onto my bars or moving my mouse over my bags quickly I get an error referring to GetBagID.

**To Reproduce**
See description

**Expected behavior**

**Error Message**
145x Interface/FrameXML/ContainerFrame.lua:1579: attempt to index a nil value
[string "@Interface/FrameXML/ContainerFrame.lua"]:1579: in function `GetBagID'
[string "@Interface/FrameXML/ContainerFrame.lua"]:1700: in function `?'
[string "@Interface/AddOns/AdiBags/libs/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:119: in function <...ags/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Interface/AddOns/AdiBags/libs/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:29: in function <...ags/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:25>
[string "@Interface/AddOns/AdiBags/libs/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:64: in function <...ags/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:59>
[string "=(tail call)"]: ?

**World of Warcraft Release and Version (Retail 9.2.7, etc)**
 - Pre-patch 10.0

**AdiBags Version**
- v1.9.39

**Have you tried disabling all your other addons to ensure only this addon causes the issue?**
 - Yes

**Additional context**

**Comment by chilblane** [comment] 2022-10-27 02:47
seeing this as well in 1.9.40

**Comment by Cidan** [comment] 2022-10-27 03:29
Hm, I'm having a hard time reproducing this one -- are there specific items you might have that would cause this?

**Comment by zaldor30** [comment] 2022-10-27 03:56
Sorry, I am not sure exactly which causes it, unfortunately it seems kind of random.  If I hazard a guess, it would be an update routine, where it is scanning my bag.  The act of picking up and placing itself does not seem to cause, but after UNIT_INVENTORY_CHANGED or BAG_UPDATE, since my mouse could be far away from the ADIBag UI.

Attaching a photo of my inventory:
![Wow_BrDZxABJpQ](https://user-images.githubusercontent.com/68781399/198187697-d946b326-1862-4f25-a747-632baf71ca61.png)

**Comment by zaldor30** [comment] 2022-10-27 03:58
Just happened to occur when I mounted my Grand Expedition Yak.  Did not click on vendor, literally just mounted it.

**Comment by Cidan** [comment] 2022-10-27 05:54
Weird! Okay, let me keep digging. I just fixed another bug that happens in a callback. I'll keep you updated.

**Comment by Cidan** [comment] 2022-10-27 06:00
Oh, actually, can you try .40 and see if it fixes it for you? I made a change that may have fixed this temporarily.

**Comment by zaldor30** [comment] 2022-10-27 06:11
May have fixed it.  Give me a bit to test it, but I can mount without issue now.

**Comment by raigoh** [comment] 2022-10-27 08:32
have same issue
![image](https://user-images.githubusercontent.com/115791459/198233462-674da0a7-f2f1-40e2-90e9-3f3c169734eb.png)

**Comment by chilblane** [comment] 2022-10-27 18:41
I'm getting that exact error @raigoh posted in .40

**Comment by Cidan** [comment] 2022-10-27 18:43
Darn, okay, back to the drawing board. I'll keep digging a bit more tonight and try to replicate the issue. Thanks!

**Comment by chilblane** [comment] 2022-10-27 19:31
For what it's worth, I don't know exactly what triggers it. My best guess is vendoring.

**Comment by wa11facer** [comment] 2022-10-27 20:49
For what it's worth, I can reliably replicate this issue toggling the "Equipped bags" panel. First I activate it, to see the bags, then I toggle it off and then always the error pops up.

**Comment by chilblane** [comment] 2022-10-27 21:32
I hearthed from Korthia to Heart of the Forest and now the ContainerFrame error is going off about every 5 seconds

**Comment by juntereiner** [comment] 2022-10-27 23:51
Is this related to the fact that we have now 5 additionnal bags maximum and adibags only display 4 ?

**Comment by zaldor30** [comment] 2022-10-28 00:33
Just got the error again selling a 213 mission table item to vendor on Grand Yak inside Sanctum.

**Comment by zaldor30** [comment] 2022-10-28 00:34
Now the bug is spamming itself after closing the vendor

**Comment by chilblane** [comment] 2022-10-28 00:47
After opening and closing enough bag/vendor windows, I get the error every time I mount

**Comment by Cidan** [comment] 2022-10-28 04:38
I finally got this to trigger! Thank you everyone -- opening and closing the extended bag view where you see individual bags caused it to trigger. I'll get a fix ASAP.

**Comment by glassleo** [comment] 2022-10-28 07:11
I suddenly started getting spammed by this in the middle of a dungeon, after opening my bags in combat a few times. Did not click the extended bag view. Maybe something is breaking in combat? I had it happen once again in the same dungeon after a /reload but afterwards I wasn't able to reproduce it on training dummies.

**Comment by Cidan** [comment] 2022-10-28 17:08
Okay! I've got the fix in #735 -- I can no longer trigger the bug. I'm going to look over some other bugs really quickly and see if I can't get them in, but otherwise, expect a release in a few minutes, manually from here, and on Curse whenever they decide to approve the update :)

Just a heads up to everyone here, Blizzard is about to completely change the bag/container API in very significant ways for 10.0.2, and it does not look like they are giving us a PTR to test this patch on. This addon will completely and totally break on release for 10.0.2, and may take a bit to fix as the changes are significant.

**Comment by mLgz0rn** [comment] 2022-10-29 02:31
I know you closed this issue, but i'm getting another error related to GetBagID
I'm on version 1.9.43.
As you can see its being spammed alot
`1090x Interface/FrameXML/ContainerFrame.lua:1579: attempt to index a nil value
[string "@Interface/FrameXML/ContainerFrame.lua"]:1579: in function `GetBagID'
[string "@Interface/FrameXML/ContainerFrame.lua"]:1700: in function `UpdateCooldown'
[string "@Interface/AddOns/AdiBags/widgets/ItemButton.lua"]:381: in function `?'
[string "@Interface/AddOns/Ace3/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:114: in function <...Ons/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:114>
[string "=[C]"]: ?
[string "@Interface/AddOns/Ace3/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:24: in function <...Ons/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:20>
[string "@Interface/AddOns/Ace3/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:59: in function <...Ons/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:54>
[string "=(tail call)"]: ?`

**Comment by Cidan** [comment] 2022-10-29 02:32
Wow, okay, let me check on this. This looks like a different error -- do you know how you triggered it?

**Comment by Cidan** [comment] 2022-10-29 02:33
Also, what version of WoW? Retail?

**Comment by mLgz0rn** [comment] 2022-10-29 02:33
> Wow, okay, let me check on this. This looks like a different error -- do you know how you triggered it?

I have no idea, it happens after a while, when questing.
And yea it's retail

**Comment by Cidan** [comment] 2022-10-29 03:28
I think I found the root cause, but Blizzard's update made this a frustrating thing to fix. Blizzard has locked down item usage for bags, and when I "fix" this in the correct way, the item buttons become protected, and can no longer be clicked in your inventory.

I think the only way I can fix this is through a really, really ugly hack, which also bypasses the protections Blizzard put in place for 10.0.0. I am unsure if the protections were added by accident, or if there is a bug in their implementation. If it's the latter, it's likely any patch I do right now will break in a future update, which will probably manifest in items not being able to be right clicked to be used from bags.

Sorry about this folks, this is super frustrating for everyone. It does feel like Blizzard somewhat rushed these changes, but they are a black box and don't actively communicate with the addon author community.

I'm going to work on the hack tonight and push another fix -- I'll update this bug with more information when I work through it.

Thanks!

**Comment by glassleo** [comment] 2022-10-29 03:34
It seems like other bag addons have the same issue too. I briedly tried out Sorted (and hated it) and the same bug was present there.

**Comment by mLgz0rn** [comment] 2022-10-29 03:35
> I think I found the root cause, but Blizzard's update made this a frustrating thing to fix. Blizzard has locked down item usage for bags, and when I "fix" this in the correct way, the item buttons become protected, and can no longer be clicked in your inventory.
> 
> I think the only way I can fix this is through a really, really ugly hack, which also bypasses the protections Blizzard put in place for 10.0.0. I am unsure if the protections were added by accident, or if there is a bug in their implementation. If it's the latter, it's likely any patch I do right now will break in a future update, which will probably manifest in items not being able to be right clicked to be used from bags.
> 
> Sorry about this folks, this is super frustrating for everyone. It does feel like Blizzard somewhat rushed these changes, but they are a black box and don't actively communicate with the addon author community.
> 
> I'm going to work on the hack tonight and push another fix -- I'll update this bug with more information when I work through it.
> 
> Thanks!

Awesome!
Thanks for the great work!

**Comment by Cidan** [comment] 2022-10-29 04:01
Okay, I've got a check for the condition that fails in Blizzard's code in AdiBags code, and if that condition is met, we gracefully handle it.

I am not 100% certain what will happen when the bug triggers, as I am unable to cause this error to trigger, but I'm fairly certain (famous last words!) this will at least stop the error spam. Worst case, cooldowns may not show on some items until you toggle your bag.

Sorry folks, as soon as 10.0.2 comes out (which will literally break this addon entirely, all over again, see [here](https://wowpedia.fandom.com/wiki/Patch_10.0.2/API_changes) for more information), I'll revisit this and try to make sure this bug is fixed properly.

New release, .44, will be out shortly

Thanks!

**Closed** 2023-01-07 00:02 UTC
Labels: Bug, Pending
