### ISSUE TITLE
With every single motion using the bag, the bag is still closes.

### ISSUE THREAD

**Issue by Koreanuser0** [AdiAddons/AdiBags#843] opened 2022-12-05 18:23 UTC
### Addon Version

v1.9.50

### World of Warcraft Version

Retail

### Describe the bug

Hello, I am a Korean user who likes AdiBags Addon. I am not good at English, so I ask for your understanding with the help of the translation function.

Like #800
Bags still closing when consuming item/selling/transferring item.
The same symptoms still exist

### Steps to reproduce

Try consuming items, putting items in a bank, or selling items in a merchant/mount.

If you delete all add-ons and install only AdiBags add-ons in the ui original state, the symptoms are the same

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by Cidan** [comment] 2022-12-05 18:24
Duplicate of #800

**Closed by Cidan** 2022-12-05 18:24 UTC
Labels: Bug, Pending
