### ISSUE TITLE
Reoccurring Lua Error upon sigin

### ISSUE THREAD

**Issue by kdubato** [AdiAddons/AdiBags#281] opened 2018-07-28 14:06 UTC
Sorry if this has already been reported, or if it's not okay to create my own issue ... but just thought I'd share.

I keep getting the following every time I login

---------------------------------

**Date:** 2018-07-28 08:58:48
**ID:** 1
**Error occured in:** Global
**Count:** 1

**Message:** 
..\AddOns\AdiBags\core\Filters.lua line 128:
   Usage: NewModule(name, [prototype, [lib, lib, lib, ...]): 'name' - Module 'Legion' already exists.

**Debug:**
[C]: ?
   ...ce\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:270: NewModule()
   AdiBags\core\Filters.lua:128: RegisterFilter()
   ...ns\AdiBags_Legion_Filters\AdiBags_Legion_Filters.lua:65: in main chunk

**Locals:**
(*temporary) = "Usage: NewModule(name, [prototype, [lib, lib, lib, ...]): 'name' - Module 'Legion' already exists."

**AddOns:**
Swatter, v7.3.1 (<%codename%>)
  AdiBags, vv1.9.9
  AdiBagsArchaeology, v7.3-release7
  AdiBagsArtifactWeapons, v1.0
  AdiBagsBoEBoA, vv1.5
  AdiBagsHearthstones, v7.3-release1
  AdiBagsLegion, vv1.6
  AdiBagsLegionFilters, v1.6.9
  LibItemUpgradeInfo10, vRelease-80000-30 70200
  BlizRuntimeLib_enUS v8.0.1.80000 <none>
  (ck=143)

**Comment by Talyrius** [comment] 2018-07-29 00:13
This error is due to conflicting module names being used by other AdiBags addons. I suggest you remove one of them.

Duplicate of #51.

**Closed by Talyrius** 2018-07-29 00:13 UTC
Labels: Duplicate
