### ISSUE TITLE
Hearthstones are not junk

### ISSUE THREAD

**Issue by oldbuster** [AdiAddons/AdiBags#112] opened 2016-09-05 10:13 UTC
I have all of my hearthstones whitelisted yet they all appear in the junk section

**Comment by D4n13le** [comment] 2016-09-06 18:09
I've only had this issue with the Dalaran Hearthstone, but it's easily solved by dragging the hearthstone and dropping it in your prefered section.

**Comment by Talyrius** [comment] 2016-09-28 02:13
This is a duplicate of #109 and was already fixed via 0aac3e8. It's available for download [here](https://www.wowace.com/addons/adibags/files/).

**Closed by Talyrius** 2016-09-28 02:13 UTC
Labels: duplicate
