### ISSUE TITLE
Old items added to "recent items"

### ISSUE THREAD

**Issue by Meilinn** [AdiAddons/AdiBags#665] opened 2022-08-26 07:41 UTC
Since the last update, all my bank items are grouped together in the "recent items" category. It happens with bags too but get fixed doing a relog, but no the bank. It happens with all my characters, bank and regent bank. Some items have been sitting in the bank for years, I didn't move them, the are not recent. Thank you
![Screenshot_85](https://user-images.githubusercontent.com/1574497/186849661-d83374ef-afdd-4e19-8d76-763f5e3ac827.png)
![Screenshot_84](https://user-images.githubusercontent.com/1574497/186849667-ff18e8e2-6ebb-4fbb-a648-91debee6092c.png)

**Comment by ZINK-ZINK** [comment] 2022-08-26 08:27
I came to report this too, but you beat me to it. The newest version from the Curseforge Updater is bugged. Every time there is a bag refresh event AdiBags seems to think either EVERYTHING in your bags is "New" or it only affects items that have both a Manual Category in adibags plus an 'automatic' Category like Gear Sets. 
![AdiBags Bug](https://user-images.githubusercontent.com/96964163/186858436-05945606-2493-474c-9bbd-ddd1766454b7.png)

**Comment by ZINK-ZINK** [comment] 2022-08-26 11:54
I don't know if I'm just pointless spamming or if all this info is useful, but on version 1.9.32 the same bug finally happened just as bad, but it took way longer than .33 to start happening. So in .32 the bug seemed to start and then .33 made it WAY worse. I was crafting etc fine until I got my AH purchases from the mail and this happened (.32)
![AdiBags Bug 2](https://user-images.githubusercontent.com/96964163/186897866-d8e2ac21-e805-4b42-8ec3-f06623e15178.png)

**Comment by Cidan** [comment] 2022-08-26 14:28
Thanks for the reports everyone!

This bug was caused by a change we made to detect when items were wrapped. Previously, there was no way to uniquely identify items in WoW, as each item did not have a unique, global ID. We had to try to detect when an item was wrapped by checking for texture changes, but didn't consider what would happen when multiple texture changes happen at once (such as add multiple items from the bank, then hitting sort).

This change has been reverted in v1.9.34, which should be live in a few minutes after this post.

There's a new API Blizzard released in BfA that makes this possible, https://wowpedia.fandom.com/wiki/API_C_Item.GetItemGUID. I'm going to keep this bug open in order to track a proper implementation of new items as it applies to wrapping paper, etc.

Thanks again, and sorry about this!

**Comment by ZINK-ZINK** [comment] 2022-08-27 01:58
Thanks for the explanation, I have a really hard time with coding and math, but I LOVE the "logic" behind coding. I need a game-like coding framework like in The Zero Theorem lol. 

FWIW consider rethinking your 'requirements' for New Items. It sounds like it would be very easy to implement it in such a way that if I picked up extras of an item that I was already carrying that those would never trigger as NEW. If I'm understanding you right then what you think of as a bug/bad thing would be a FEATURE to me. Personally it drives me crazy having half my bag flashing at me just cause I hit my TSM RESTOCK button, or picked up 8/20 of some weekly grind item. 

I would vastly prefer it if the only items that acted as NEW were ONLY items that I had zero copies of in my bags already, like PLEASE add that option lol! I'm not OCD, but I do feel "compelled" to create "order" so I am constantly hitting "N" to make all the flashing stop, but I don't want to turn NEW ITEMS off entirely because it makes it much easier to find that new Battle Pet or Quest Item etc that I just picked up. Basically I use NEW flashing to help me identify items that "do not belong". 

While I'm here I may as well hit you with my other long-term feature requests too.
- Feature Requests:
- Manual Min & Max gear item level ranges, and the option to pick our own 'peak and valley' colors that the item level colors gradient through automatically. Having 298 Gear show as white item level annoys me, let me just input the range myself so we aren't reliant on addon updates each tier. 
- Add the option to Force an Item or Category into a certain spot relative to the bag window that overrides the automatic Priority. Like let me Force all Items that are both Miscellaneous and New to the absolute bottom of the bag window; or let me Force Manual Sorting Items to their own isolated area. Basically, I heavily use manual sorting and when I pick up some random Item it often gets lost in the middle of my bags, it would be easy to find if I left it flashing as NEW, but like I said that triggers me so I have to Sort then hunt for the Junk when I make it to a vendor.
- Max Bag Height has never seemed to work very well. It would be cool to set a HARD screen area limit for each bag window and have adibags re-Scale itself to take up near-exactly the screen area I set, no matter how full or empty my bags are. So like if my bags are half full like normal it scales to 100% size, but if I go to the bank and fill my bags to the brim then they scale to ~70% so the windows fit nicely. BAG-MAGEDDON every time I visit the bank with full bags is pretty funny, but it's a bit much for a AH Goblin power-user. 
- I don't know how to really communicate this last request. The Category Priorities just don't really do it for me. They aren't the worst way to implement that functionality and I still super appreciate them, but it has always felt like I was fighting against it. Like my personal setup is a whole mess of 100 Item large Manual Categories + custom Auto-Sorting rules + plugins like TSM_Categories_for_AdiBags_Plugin. To get the functionality I wanted I had to create a rats-nest of overriding settings and conflicting/contradictory categories. I would LOVE a more elegant solution, but that would be a major code-rewrite for you.

Thanks a ton for AdiBags. The QoL you have provided is very underappreciated. <3

_ZINK

**Comment by Cidan** [comment] 2022-08-27 02:24
Thanks for the thoughtful reply!

> I would vastly prefer it if the only items that acted as NEW were ONLY items that I had zero copies of in my bags already,

This is only partly up to us, at least currently. Blizzard implements an API that we call, that tells us when an item is "new" -- it's Blizzard that decides what's new and what isn't, not us. That being said, with the changes I made in another branch earlier today, it should be possible to side step Blizzard's definition of new. I've been testing it on and off all day, and it works great. The downside is, it only works on retail, because Blizzard did not back port some specific changes to classic servers. Womp womp.

One annoying bug that I've fixed, which I've seen before, is when items sometimes flash for no reason, either in the bank or in your bags. I had a really good case where I could reproduce that bug over and over, and managed to completely eliminate it. That'll be out in the next version.

> While I'm here I may as well hit you with my other long-term feature requests too.

Would you be willing to open individual issues for each of your feature requests? One request per issue, though I can't promise they'll be implemented. At the very least, we can discuss the ramifications of each issue independently.

The new version should be out shortly with a better new item tracking on retail -- I'm just waiting for either Wrath PTR to come back up, or pre-patch to hit, so I can do some final testing.

Thanks!

**Comment by ZINK-ZINK** [comment] 2022-08-27 02:29
OH! I forgot a very important feature request! Automatic "Container" Category please! ATM I am manually adding every Paragon Cache, Callings Box, Patterns Within Patterns Box, etc etc to my Manual "BOXES" Category in the Quest Item Section; so that openable containers are always on top. 

That seems like a reasonably easy API check: isContainer=true; then setPriority100 ...or something like that, IDK, I can't do math or code lol

**Comment by ZINK-ZINK** [comment] 2022-08-27 02:38
> Would you be willing to open individual issues for each of your feature requests? One request per issue, though I can't promise they'll be implemented. At the very least, we can discuss the ramifications of each issue independently.

I'm VERY lazy, but ok, you deserve that much at least for saving me dozens, maybe hundreds of hours over the years.

**Closed** 2022-08-27 15:38 UTC
