### ISSUE TITLE
Pressing B - Lua Error Adibags/core/hooks.lua - Masque?

### ISSUE THREAD

**Issue by Pheeve** [AdiAddons/AdiBags#847] opened 2022-12-07 05:58 UTC
### Addon Version

v1.9.50

### World of Warcraft Version

Retail

### Describe the bug

When i press B or open up bags it just spits out the following error. It just happens randomly

4x AdiBags/modules/CurrencyFrame.lua:257: attempt to index local 'cell' (a nil value)
[string "=[C]"]: ?
[string "@Masque/Libs/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:24: in function <...que/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:20>
[string "@Masque/Libs/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:59: in function `SendMessage'
[string "@AdiBags/core/Bags.lua"]:138: in function `GetFrame'
[string "@AdiBags/core/Bags.lua"]:90: in function `Open'
[string "@AdiBags/core/Hooks.lua"]:115: in function <AdiBags/core/Hooks.lua:112>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "OPENALLBAGS"]:1: in function <[string "OPENALLBAGS"]:1>

### Steps to reproduce

Open Bag after reset, open bag on vendor. 
its...always 100% on first load in, but i can then press B over and over and its not an issue.

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by Pheeve** [comment] 2022-12-07 05:59
Sorry forgot to add, what i dont get is what is Masque doing in Adibags anyway...i don't have a module to do a setting there

**Comment by Talyrius** [comment] 2022-12-07 07:49
This issue is a duplicate of #824.

> Sorry forgot to add, what i dont get is what is Masque doing in Adibags anyway...i don't have a module to do a setting there

As many addons do, they simply make use of a shared a library—specifically CallbackHandler-1.0 in this case.

**Closed by Talyrius** 2022-12-07 07:49 UTC
Labels: Duplicate
