### ISSUE TITLE
LUA Error

### ISSUE THREAD

**Issue by Runkel79** [AdiAddons/AdiBags#687] opened 2022-09-03 05:39 UTC
**Describe the bug**
LUA Error on Load since yesterdays patch:

42x AdiBags\core\EventHandlers.lua:44: Attempt to register unknown event "CURSOR_UPDATE"
[string "=[C]"]: in function `RegisterEvent'
[string "@AdiBags\core\EventHandlers.lua"]:44: in function `OnUsed'
[string "@Scrap\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:76: in function <...rap\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:59>
[string "=(tail call)"]: ?

Locals:
(*temporary) = <unnamed> {
 0 = <userdata>
}
(*temporary) = "CURSOR_UPDATE"

**To Reproduce**
1. Enter World
2. See error

**World of Warcraft Release and Version (Retail 9.2.7, etc)**
 - WOTLK classic

**AdiBags Version**
- AdiBags-v1.9.36

**Have you tried disabling all your other addons to ensure only this addon causes the issue?**
 - Yes

**Comment by ihme** [comment] 2022-09-03 07:14
I am experiencing the same error.

```
2x AdiBags\core\EventHandlers.lua:44: Attempt to register unknown event "CURSOR_UPDATE"
[string "=[C]"]: in function `RegisterEvent'
[string "@AdiBags\core\EventHandlers.lua"]:44: in function `OnUsed'
[string "@AdiBags\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:76: in function <...ags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:59>
[string "=(tail call)"]: ?

Locals:
(*temporary) = <unnamed> {
 0 = <userdata>
}
(*temporary) = "CURSOR_UPDATE"
```
To Reproduce - Login and it appears.

World of Warcraft Release and Version (Retail 9.2.7, etc) - WOTLK classic 

AdiBags Version - v1.9.36

Have you tried disabling all your other addons to ensure only this addon causes the issue? Yes

**Comment by Cidan** [comment] 2022-09-03 07:29
This is a duplicate of #686 -- please update to the newest version manually. For some reason, Curse isn't auto-pushing the updated version, but you can get it from the release page here in Github. The same zip file works for all versions of WoW.

**Closed by Cidan** 2022-09-03 07:29 UTC
Labels: Bug, Pending
