### ISSUE TITLE
Bags not displaying.

### ISSUE THREAD

**Issue by maguilu** [AdiAddons/AdiBags#787] opened 2022-11-17 18:04 UTC
### Addon Version

1.9.46

### World of Warcraft Version

Retail

### Describe the bug

I can access the addon config and other configuration-related items but when trying to open the bags, all that happens is the sound of the bags opening but can't see the bags
 Once I disable the addon the bags display again 

### Steps to reproduce

just open the bag

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by Spinum** [comment] 2022-11-17 19:01
I can confirm/repeat the above behavior. Disabled all addons except AdiBags v1.9.46.

**Comment by lunamoth** [comment] 2022-11-17 20:20
I'm also having a problem with the AdiBags bag not opening. (1.9.46)

**Comment by NoahDavidATL** [comment] 2022-11-18 00:36
Same. Addon doesn't work on 10.0.2

**Comment by Elboufda** [comment] 2022-11-18 04:04
same for me

**Comment by SpareSimian** [comment] 2022-11-18 11:26
Duplicate of #782. I recommend closing this and continuing there.

**Closed** 2022-11-18 18:16 UTC
Labels: Bug, Pending
