### ISSUE TITLE
Clicking on "S" crashed wow

### ISSUE THREAD

**Issue by orlith** [AdiAddons/AdiBags#137] opened 2016-11-03 12:49 UTC
Hello

I'm pretty sure it has already been reported but wasn't able to find it, but When I open my bags (wherever I am)  and click on "s" to sort my bag, the game stall, I have to simply kill wow process, or hard reboot the computer if wow is set to run in full screen mode (can't show the task list to kill the process).
I can't paste error code or else as they can't be retrieved.

Any idea on how to "solve" this or get a workaround that remove the crash issue (i don't care if there's a lag i can live with but not with a crash)

Feel free to request any information that can be useful to you.

Wow runs on W10 pro FR.

Thx

**Comment by nanrector** [comment] 2016-11-03 13:07
I'm haivng WoW crash too when I try to sort.

**Comment by Talyrius** [comment] 2016-11-03 13:08
The sort function being ran is the same one Blizzard uses in the default bags. Yes, it's processing intensive, but it will not crash the client. You have to wait for the client to regain responsiveness. If you'd like Blizzard to improve it, you'll have to post about it on the official forums.

**Comment by orlith** [comment] 2016-11-03 16:13
1. Thx for a so quick answer and closure.. 
2. I waited around 20 mn, thinking that it's enough no ? tested on 2 different computers and one that got the latest cpu/gc
3. disabling adibag and sorting give me a very short lag, not a unresponsiveness as I have with this addon.

I love this addon as this is the only one doing intelligent filtering and sorting by itself
Can't you implement an option that gives the capability to remove the "s" button if the user don't want to have it ?
I really don't need that option of manual sorting, so that would be a pitty to get rid of this addon just because this button is there and clickable by mistake (to close to the "n" button)

That will be very helpful if you can do that

Thx for listening to us.
have a nice evening

**Comment by Talyrius** [comment] 2016-11-03 17:28
I tested this and it was slower than it had been in the past, but the client became responsive again in seconds, not minutes. Like I said before, this is Blizzard's sort function.

**Comment by zarevucky** [comment] 2016-11-03 19:09
I can see three distinct possibilities why this happens:
- You are using a very old version of the addon.
- You are using other addons that cause the problems.
- There's a bug in the code that handles bag changes in AdiBags, one that only manifests in particular circumstance.

**Comment by Adirelle** [comment] 2016-11-04 08:14
AdiBags disables all its event handlers while the sort function is running and catch up afterwards, to avoid doing too many useless updates.

**Comment by zarevucky** [comment] 2016-11-04 12:03
Hypothetically, it is possible that it's this part that got broken. Either by recent fixes to AdiBags, or in Blizzard UI itself. Not very likely, but in case my first two proposed causes are false, it sounds like the most plausible explanation.

**Comment by orlith** [comment] 2016-11-04 13:10
Finally I found where the issue comes from.
I disabled all other addon -> Wow was still crashing when sorting
I disabled one by one all option on adibags and found that if the "Item level"  plugin is enabled then Wow crash while sorting the bags. Disabling that option solve the issue, i get the short lag as you said (2s).
I will not get deeper into troubleshooting, that's maybe only one option on that plugin settings that causes the trouble,  but i have no more time to test.

Thx

**Comment by blemmelin** [comment] 2016-11-15 06:26
Excellent work to those who created this addon. If you want to simply remove the "S" from adibags you can edit the "ContainerFrame.lua" and comment out the section related to that button. 
Once the addon is re-installed or updated these changes of course are overridden and the "S" button will reappear.  I don't find myself using the button as the addon sorts everything beautifully, and more often was mistakenly clicking it by accident. 
-- self:CreateModuleButton(
		-- "S",
		-- 10,
		-- function()
			-- self.bagObject:Sort()
			-- self.forceLayout = true
		-- end,
		-- L["(Blizzard's) Sort items"]
	-- )

**Comment by LunaEclipse73** [comment] 2016-11-20 04:08
orlith's fix is correct, simply disabling the item level plugin makes this problem go away, it was always causing WoW to go "Not Responding" for me and would never recover, I disabled the item level plug in and now it takes like 2 seconds to sort.

**Comment by OUGHT** [comment] 2016-11-24 18:39
Okay, so I disabled this plugin and sorting started to work.
But I really, **really** liked the item level functionality. And in previous expansions the "Blizzard" sort worked perfectly with ilvl enabled.

So, @Talyrius, are you certain that you will not fix the ItemLevel plugin?

**Comment by Talyrius** [comment] 2016-11-24 18:53
I use the item level plugin and can't reproduce the issue you're experiencing with Blizzard's sort function. It takes a couple of seconds and the client doesn't hang.

**Comment by OUGHT** [comment] 2016-11-24 21:23
Ok, how I can help you with pinpointing the problem? Maybe some logs, or experimental builds, or anything?
Btw, I tried this with only 1 addon enabled - AdiBags, so we can eliminate another addon interference.

**Comment by orlith** [comment] 2016-11-25 09:51
Thx @OUGHT taking the lead on helping to solve that issue. Unfortunatly I don't have enough time to do so. I really appreciate. Hope Talyrius and you will sort that out.
If you need me to do some tests with a dev version feel free to ask.

Thx to you!

**Comment by OUGHT** [comment] 2016-11-25 12:04
Np, tnx to you for reporting this problem =-)

**Comment by OUGHT** [comment] 2016-12-02 08:28
Is there any progress/information/request for testing? =-)

**Comment by iRodent** [comment] 2016-12-05 18:15
I get this freeze when I turn on item stack grouping for items that don't normally stack. With that on, pressing sort freezes WoW.

**Comment by wixbit** [comment] 2016-12-12 17:11
After testing a bit it seems the problem is a combination of the item level plugin and virtual stacks.

With item level plugin enabled:
- Merge free space: no problem
- Merge stackable items: no problem (but slower)
- ... including incomplete: crashes
- Merge unstackable (without the other): crashes

If item level plugin is disabled it works with all the virtual stacking options enable although it's a lot slower.

If you're still unable to reproduce this problem I can try looking into the code and see if I can find out more specifically where it goes wrong.

**Comment by Talyrius** [comment] 2016-12-13 01:09
Unfortunately, I've been too busy to play the game or work on addons as of late. I'm hoping that'll change soon, but in the meantime, if you find a solution, open a pull request.

**Comment by Cidan** [comment] 2016-12-13 05:56
Hey everyone,

I finally got around to looking at this one tonight, and fixed it on master. (Sorry I didn't make a PR, I thought I was working off a branch.)

The only file that changed was widgets\ItemButton.lua, so feel free to nab that file and replace it. One thing to note is that if you sort right after start up/load, the UI will still freeze for a second, but it won't crash the game. If you wait a few seconds until the game can load item data, sorting should be pretty speedy.

That being said, the entire event and draw system really needs to be overhauled. Unfortunately, my time is extremely limited. If anyone wants to look refining these bits, let me know.

Thanks.

**Comment by Cidan** [comment] 2016-12-15 06:35
I'm going to go ahead and close this since it seems to be fixed and no one has commented otherwise. If anyone else runs into this issue after you tried the fix, let me know.

**Closed by Cidan** 2016-12-15 06:35 UTC

**Comment by wfmarcum** [comment] 2017-01-08 16:00
I'm still experiencing the problem intermittently, sometimes it works as intended, other times it just completely crashes the game.

**Comment by Sephiroth018** [comment] 2017-03-05 15:40
I'm also experiencing this problem. As was said in a previous comment, disabling the Item Level plugin stops the crashing. So it is definitely a problem of AdiBags and should be fixable.

**Comment by Talyrius** [comment] 2017-03-31 17:42
Fixed in b4c8337.
