### ISSUE TITLE
Prepatch Phase 2 Bugs on starting the game

### ISSUE THREAD

**Issue by richyvee** [AdiAddons/AdiBags#781] opened 2022-11-16 09:01 UTC
### Addon Version

-v1.9.46.zip

### World of Warcraft Version

Retail

### Describe the bug

When I start the game i get 10+ error messages from bugsack/buggrabber and i cant open my bags.
I have disabled all addons and when i start the game I get the 24 errors in the attatchment.
[AdiBags Errors.txt](https://github.com/AdiAddons/AdiBags/files/10019881/AdiBags.Errors.txt)

### Steps to reproduce

Have patch -v1.9.46.zip and log into the game

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by Cidan** [comment] 2022-11-18 18:18
Duplicate of #782

**Closed by Cidan** 2022-11-18 18:18 UTC
Labels: Bug, Pending
