### ISSUE TITLE
Currency not being tracked on Wrath

### ISSUE THREAD

**Issue by PunkROC01** [AdiAddons/AdiBags#929] opened 2023-02-08 07:28 UTC
### Addon Version

v1.10.7

### World of Warcraft Version

Wrath

### Describe the bug

Even though I am tracking the currency in the currency tab, it won't show up at the bottom of my bags

### Steps to reproduce

Open bag, look at bottom area while currency is tracked

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by Talyrius** [comment] 2023-02-08 10:41
This issue is a duplicate of #707.

**Closed by Talyrius** 2023-02-08 10:41 UTC
Labels: Duplicate

**Comment by PunkROC01** [comment] 2023-02-08 22:01
> This issue is a duplicate of #707.

I see that, but that was posted back in September of 2022. I had working currency on my AdiBags for ant least a month and an half until 3.4.1 released. So this seems like a new problem

**Comment by Talyrius** [comment] 2023-02-09 01:19
I don't know what to tell you, but you're mistaken. Other than superficial changes with the new theme engine implementation (#880), the [CurrencyFrame module](https://github.com/AdiAddons/AdiBags/commits/master/modules/CurrencyFrame.lua) hasn't seen any updates since issue #707 was opened. Currently, AdiBags only supports currencies on retail, not classic/WotLK.
