### ISSUE TITLE
New Fork

### ISSUE THREAD

**Issue by apedley** [AdiAddons/AdiBags#75] opened 2016-05-21 08:02 UTC
Since this project is abandoned, is there anyone who has thought of making a new fork to continue Adirelle's work?

**Comment by Adirelle** [comment] 2016-05-22 09:26
If some people volunteer to maintain the project, I can add them to the wowace project some they could push new versions. I also accept push requests.

**Comment by tmmgeekette** [comment] 2016-07-19 20:26
Adirelle,  Has anyone volunteered to maintain this?  I have never developed for wow but I have developed other addons in the the last few years and am willing to learn what I must to keep it going.  I love adibags and didn't realize until it broke with this Legion pre-patch that it was on hold project.

thanks!
-Tania

**Comment by Adirelle** [comment] 2016-07-19 21:07
Not that I am aware.

**Comment by Adirelle** [comment] 2016-07-23 00:51
That said, if some people, like you, @Cidan or @Talyrius would like to co-maintain the addon, I could  give you the permission to do so, both no wowace and here. I have already handed down the maintenance of AdiButtonAuras and LibDualSpec-1.0. I am still hanging around anyway.

**Comment by Cidan** [comment] 2016-07-23 01:59
I wouldn't mind helping around and making sure the add-on continues to work as intended; my changes wouldn't really be that major, just enough to make sure it works error free for as long as I play WoW.

**Comment by tmmgeekette** [comment] 2016-07-23 04:16
It looks like there are many people like me who love adibags and are willing to help keep it going.   I have some enhancement ideas of my own so I might contribute as time passes.   co-maintain is good.

**Comment by Talyrius** [comment] 2016-07-23 11:20
Yes, I'm willing to lend a hand.

**Comment by Adirelle** [comment] 2016-07-25 22:10
You have been invited. I'll soon setup a system to push master and tags to wowace (and the curse client) from github.

**Comment by Adirelle** [comment] 2016-07-25 22:40
Just a few guidelines:
* Please respect the coding style (soon to be enforced by a check):
  * indentation with tabs only,
  * alignment with spaces only,  
  * no trailing space at end of lines,
  * variable names are camelCased whereas function and method  names are CamelCased.
  * "long" variable names.
* Code the new features in dedicated branches, and merge them when they are almost finished. Ideally, I'd like someone else than the branch author reviewed the code.
* Beware of feature bloat: do not include every features asked bu the users. I already felt for this, which is what makes AdiBags quite complicated to maintain.

**Comment by Cidan** [comment] 2016-07-25 22:50
I don't particularly think (much) feature expansion should happen with the current iteration of AdiBags. At best, we should work to stabilize any issues that may appear. Once issues are stable and bugs are eliminated, we can take a real look at refactoring large sections of code and removing a lot of the complexity behind AdiBags.

**Comment by zarevucky** [comment] 2016-07-26 11:31
>  Ideally, I'd like someone else than the branch author reviewed the code.

Heya. I haven't done any real work on AdiBags except for some small personal hacks, but if you need another set of eyes for reviewing changes, I'd be happy to help.

**Comment by Adirelle** [comment] 2016-07-26 20:36
I have setup continuous integration with travis-ci. It mainly tests the syntax and the code styling for now. It also push working builds to wowace.

I have created a chat room on gitter. Its uses is not mandatory but it can be handy to discuss. You can use your github account.

**Comment by Cidan** [comment] 2016-07-26 21:22
I'm going to go ahead and close this to keep the issue log clear. Join us on Gitter!

**Closed by Cidan** 2016-07-26 21:22 UTC
