### ISSUE TITLE
7.2 update Error

### ISSUE THREAD

**Issue by Perkynips** [AdiAddons/AdiBags#179] opened 2017-03-31 22:45 UTC
I'm not sure what is causing it - I grabbed the code I hope it says way more than I could. 

Date: 2017-03-31 17:32:43
ID: 2
Error occured in: Global
Count: 1
Message: Usage: local itemIDs = C_EquipmentSet.GetItemIDs(equipmentSetID)
Debug:
   [C]: GetItemIDs()
   ...face\AddOns\Blizzard_Deprecated\Deprecated_7_2_0.lua:152:
      ...face\AddOns\Blizzard_Deprecated\Deprecated_7_2_0.lua:149
   AdiBags\core\DefaultFilters.lua:108: UpdateSlots()
   AdiBags\core\DefaultFilters.lua:145: ?()
   ...ags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:145:
      ...ags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:145
   [string "safecall Dispatcher[2]"]:4:
      [string "safecall Dispatcher[2]"]:4
   [C]: ?
   [string "safecall Dispatcher[2]"]:13: ?()
   ...ags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90: SendMessage()
   AdiBags\widgets\ContainerFrame.lua:908: RedispatchAllItems()
   AdiBags\widgets\ContainerFrame.lua:1054: FullUpdate()
   AdiBags\widgets\ContainerFrame.lua:563:
      AdiBags\widgets\ContainerFrame.lua:549
   [C]: ?
   AdiBags\core\Utility.lua:89:
      AdiBags\core\Utility.lua:81
   AdiBags\widgets\LayeredRegion.lua:119:
      AdiBags\widgets\LayeredRegion.lua:108
Locals:
None
AddOns:
  Swatter, v7.3a.5701 (TasmanianThylacine)
  AdiBags, vv1.9.5
  Altoholic, vr178
  AucAdvanced, v7.3a.5701 (TasmanianThylacine)
  AucFilterBasic, v7.3a.5701 (TasmanianThylacine)
  AucFilterOutlier, v7.3a.5701.5459(7.3a/embedded)
  AucMatchUndercut, v7.3a.5701.5585(7.3a/embedded)
  AucStatHistogram, v7.3a.5701 (TasmanianThylacine)
  AucStatiLevel, v7.3a.5701 (TasmanianThylacine)
  AucStatPurchased, v7.3a.5701 (TasmanianThylacine)
  AucStatSales, v7.3a.5701.5598(7.3a/embedded)
  AucStatSimple, v7.3a.5701 (TasmanianThylacine)
  AucStatStdDev, v7.3a.5701 (TasmanianThylacine)
  AucStatWOWEcon, v7.3a.5701.5613(7.3a/embedded)
  AucUtilAHWindowControl, v7.3a.5701.5575(7.3a/embedded)
  AucUtilAppraiser, v7.3a.5701.5666(7.3a/embedded)
  AucUtilAskPrice, v7.3a.5701.5599(7.3a/embedded)
  AucUtilAutoMagic, v7.3a.5701.5686(7.3a/embedded)
  AucUtilCompactUI, v7.3a.5701.5694(7.3a/embedded)
  AucUtilEasyBuyout, v7.3a.5701.5576(7.3a/embedded)
  AucUtilFixAH, v7.3a.5701 (TasmanianThylacine)
  AucUtilItemSuggest, v7.3a.5701.5651(7.3a/embedded)
  AucUtilPriceLevel, v7.3a.5701.5633(7.3a/embedded)
  AucUtilScanButton, v7.3a.5701.5631(7.3a/embedded)
  AucUtilScanFinish, v7.3a.5701.5588(7.3a/embedded)
  AucUtilScanProgress, v7.3a.5701.4979(7.3a/embedded)
  AucUtilScanStart, v7.3a.5701.5347(7.3a/embedded)
  AucUtilSearchUI, v7.3a.5701.5672(7.3a/embedded)
  AucUtilSimpleAuction, v7.3a.5701.5654(7.3a/embedded)
  AucUtilVendMarkup, v7.3a.5701.4828(7.3a/embedded)
  Babylonian, v5.1.DEV.332(/embedded)
  BeanCounter, v7.3a.5701 (TasmanianThylacine)
  Castbars, v
  Clique, vv70100-1.1.0
  Configator, v5.1.DEV.406(/embedded)
  DataStore, vr62
  DataStoreAchievements, vr45
  DataStoreAgenda, vr25
  DataStoreAuctions, vr47
  DataStoreCharacters, vr38
  DataStoreContainers, vr55
  DataStoreCrafts, vr76
  DataStoreCurrencies, vr34
  DataStoreGarrisons, vr20
  DataStoreInventory, vr48
  DataStoreMails, vr48
  DataStorePets, vr41
  DataStoreQuests, vr40
  DataStoreReputations, vr39
  DataStoreSpells, vr29
  DataStoreStats, vr28
  DataStoreTalents, vr58
  DBMCore, v7.2.0
  DBMDefaultSkin, v
  DBMInterrupts, v6.2.0
  DBMStatusBarTimers, v
  DebugLib, v5.1.DEV.337(/embedded)
  DugisGuideViewerZ, v4.200
  EasyMail, v
  ElvUI, v10.46
  Enchantrix, v7.3a.5701 (TasmanianThylacine)
  EnchantrixBarker, v7.3a.5701 (TasmanianThylacine)
  FriendXP, v1.29
  FriendXPBar, v1.60.10
  Grail, v087
  GrailAchievements, v011
  GrailQuestsenUS, v22996
  GTFO, v4.42.9
  Informant, v7.3a.5701 (TasmanianThylacine)
  LibExtraTip, v5.12.DEV.423(/embedded)
  LightHeaded, vwowi:revision
  Loremaster, v007
  MikScrollingBattleText, v5.7.147
  MogIt, v3.8.0
  MogItCloth, v3.8.0
  MogItOneHanded, v3.8.0
  MogItOther, v3.8.0
  MogItRanged, v3.8.0
  MogItTwoHanded, v3.8.0
  OmniBar, vv7.2
  Recount, vv7.2.0a release
  SlideBar, v7.3a.5701 (TasmanianThylacine)
  SPTimers, v3.10.2
  Stubby, v7.3a.5701 (TasmanianThylacine)
  TidyPlates, v6.18.11
  TidyPlatesGraphite, v
  TidyPlatesGrey, v
  TidyPlatesNeon, v
  TidyPlatesQuatre, v
  TidyPlatesHub, v
  TidyPlatesWidgets, v
  TipHelper, v5.12.DEV.405(/embedded)
  TomTom, vv70100-1.0.1
  TomTomPing, v1.3 r038
  WeakAuras, v2.3.8
  WorldQuestGroupFinder, v0.22.1
  WorldQuestTracker, v
  BlizRuntimeLib_enUS v7.2.0.70200 <none>
  (ck=cb8)

**Comment by Talyrius** [comment] 2017-04-01 19:40
Duplicate of #177.

**Closed by Talyrius** 2017-04-01 19:40 UTC
Labels: duplicate
