### ISSUE TITLE
AdiBags prevents closing windows with ESC key during combat

### ISSUE THREAD

**Issue by adrianhildebrandt** [AdiAddons/AdiBags#863] opened 2022-12-31 13:15 UTC
### Addon Version

v1.9.50

### World of Warcraft Version

Retail

### Describe the bug

When you are in combat and have certain windows open (e.g. Map, Spellbook or Dungeons & Raids) you cannot close it using the ESC key. "Interface action failed because of an AddOn" is shown in chat the first time you try it.

Not so annoying but maybe related: You cannot open the AdiBags configuration window during combat. Trying to open it freezes the game for a couple of seconds.

### Steps to reproduce

1. Start combat with anything.
2. Open window (e.g. World Map).
3. Press ESC.

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by Cidan** [comment] 2023-01-03 20:15
Duplicate of #831

**Closed by Cidan** 2023-01-03 20:15 UTC
Labels: Bug, Pending
