### ISSUE TITLE
Sorry for this BUT

### ISSUE THREAD

**Issue by d4kir92** [AdiAddons/AdiBags#688] opened 2022-09-03 08:18 UTC
you said the CURSOR_UPDATE bug was fixed in 1.9.37
but somehow something failed to upload to curse, there is still 1.9.36 after more then the 1 hour you said :D

hope you find the problem

maybe its in github action, the problem

Thanks for the addon! :D

**Comment by Cidan** [comment] 2022-09-03 08:21
Duplicate of #682.

The problem isn't the action -- Curse has a moderation queue for addon uploads/updates, and it's "in review" on their end. You can download the addon via the Release page in this Github repo, or you can use another addon manager, like WowUp, to manage this install until Curse decides to update.

**Closed by Cidan** 2022-09-03 08:21 UTC
Labels: Bug, Pending
