### ISSUE TITLE
Filters Not Initially Working

### ISSUE THREAD

**Issue by lotsoftoons** [AdiAddons/AdiBags#252] opened 2017-12-11 21:39 UTC
This has been a bug with Adibags for a long time. After logging in or reloading my UI, the filters don't work after opening my bags 1 time. I have to open my bags then close them then open them again before the filters kick in. Before opening my bags twice, 90% of my inventory is crammed into the miscellaneous category. In my meager experience with WoW and Lua, you have to wait a few seconds after loading in before your addon can do certain things. Maybe this is one of those instances.

**Comment by m4xc4v413r4** [comment] 2017-12-14 14:17
I've seen this happen too. Closing and opening the bag again does "fix" it as also stated.

**Comment by Cidan** [comment] 2022-08-21 21:08
I am unable to reproduce this in 2022. Can anyone chime in here?

**Comment by Talyrius** [comment] 2022-08-22 02:36
I haven't tested this recently, but it was definitely still happening when I last logged in a number of months ago. The item classification information for the contents of the bags wasn't being fetched and cached from the server until after they had been opened at least once per session.

**Closed** 2023-11-26 03:14 UTC
Labels: Bug
