### ISSUE TITLE
Interface\AddOns\AdiBags\core\EventHandlers.lua:45: Attempt to unregister unknown event "CURSOR_UPDATE"

### ISSUE THREAD

**Issue by emanueol** [AdiAddons/AdiBags#686] opened 2022-09-02 22:18 UTC
NOTE: Bugs can sometimes be caused by conflicts with other addons. Please disable all other addons and try to reproduce your issue. You must answer below that you have tried disabling all your addons before this bug is accepted. If you have not tried disabling all your addons, your bug will be closed.

**Describe the bug**
Message: Interface\AddOns\AdiBags\core\EventHandlers.lua:45: Attempt to unregister unknown event "CURSOR_UPDATE"
Time: Fri Sep  2 23:14:44 2022
Count: 1
Stack: Interface\AddOns\AdiBags\core\EventHandlers.lua:45: Attempt to unregister unknown event "CURSOR_UPDATE"

Locals: <none>

**Comment by Cidan** [comment] 2022-09-02 22:21
Duplicate of #682

**Closed by Cidan** 2022-09-02 22:21 UTC
Labels: Bug, Pending
