### ISSUE TITLE
[Feature]: Show Crafted/Gathered item quality like default bags do.

### ISSUE THREAD

**Issue by SJPadbury** [AdiAddons/AdiBags#857] opened 2022-12-17 01:05 UTC
### Describe the feature

![Adibage-Screenshot 2022-12-16 195915](https://user-images.githubusercontent.com/22439631/208215015-ab71b9e3-88f0-4be5-a54a-4bf3c5f73fe4.png)
![Defaultbags-Screenshot 2022-12-16 200252](https://user-images.githubusercontent.com/22439631/208215016-ecb5764d-62de-412b-9f88-9b053ec717bd.png)
As you can see, with Adibags, there's no indication of the gathered/crafted item quality, but this is visible on the default blizzard bags.  Can we get this added please?

### Describe the implementation

Same/similar to default is fine, just not having to mouse over every item stack to see the quality of it.

**Comment by Talyrius** [comment] 2022-12-17 11:09
This is a duplicate of issue #840.

**Closed by Talyrius** 2022-12-17 11:09 UTC
Labels: Duplicate
