### ISSUE TITLE
Error Opening Bank

### ISSUE THREAD

**Issue by Larodis** [AdiAddons/AdiBags#184] opened 2017-04-01 19:01 UTC
An error pops up immediately when opening the bank, but all items are viewable. Switching to the Reagents tab will show a few items, but most are blank and can't be interacted with. Switching back to main bank view causes those items to also be blank and non-interactive.

EDIT: Rechecked issue with all addons disabled but this AddonControlPanel and Swatter. Still occurs. Swatter reported some additional info during the recheck. Appended to end of Issue report.

Date: 2017-04-01 11:51:25
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\AdiBags\widgets\ItemButton.lua line 352:
   attempt to index field 'UpgradeIcon' (a nil value)
Debug:
   [C]: ?
   AdiBags\widgets\ItemButton.lua:352: IsContainerItemAnUpgrade()
   AdiBags\widgets\ItemButton.lua:303: Update()
   AdiBags\widgets\ItemButton.lua:278: FullUpdate()
   AdiBags\widgets\ItemButton.lua:246:
      AdiBags\widgets\ItemButton.lua:234
   [C]: Show()
   AdiBags\widgets\Section.lua:112:
      AdiBags\widgets\Section.lua:110
   [C]: Show()
   AdiBags\widgets\ContainerFrame.lua:952: PrepareSections()
   AdiBags\widgets\ContainerFrame.lua:1058: FullUpdate()
   AdiBags\widgets\ContainerFrame.lua:563:
      AdiBags\widgets\ContainerFrame.lua:549
   [C]: ?
   AdiBags\core\Utility.lua:89:
      AdiBags\core\Utility.lua:81
   AdiBags\widgets\LayeredRegion.lua:119:
      AdiBags\widgets\LayeredRegion.lua:108
Locals:

AddOns:
  Swatter, v7.3a.5701 (TasmanianThylacine)
  ACP, v3.4.30 
  AdiBags, vv1.9.5
  AraBrokerXP, vr4
  AskMrRobot, v50
  BagSaver, v0.7.0
  Bartender4, v4.7.7
  BrokerMicroMenu, vv1.4.2
  CaerdonWardrobe, vv0.39.0
  CaerdonWardrobeAdiBags, vv0.4.0
  CanIMogIt, v7.2.0.01
  ChocolateBar, vv3.0.4
  DataStore, vr62
  DataStoreAchievements, vr45
  DataStoreAgenda, vr25
  DataStoreAuctions, vr47
  DataStoreCharacters, vr38
  DataStoreContainers, vr55
  DataStoreCrafts, vr76
  DataStoreCurrencies, vr34
  DataStoreGarrisons, vr20
  DataStoreInventory, vr48
  DataStoreMails, vr48
  DataStorePets, vr41
  DataStoreQuests, vr40
  DataStoreReputations, vr39
  DataStoreSpells, vr29
  DataStoreStats, vr28
  DataStoreTalents, vr58
  DBMCore, v7.2.2
  DBMDefaultSkin, v
  DBMLDB, v
  DBMStatusBarTimers, v
  DebugLib, v5.1.DEV.337(/embedded)
  Decursive, v2.7.5.2
  Geist, v70000.1
  GeistButtonFacade, v30200.1
  GoGoMount, v7.1.1
  Grid, v7.1.0.1
  GridManaBars, v1.11
  GrindLoot, v11.02
  HandyNotes, vv1.4.13
  HandyNotesDraenorTreasures, v1.20a
  HandyNotesLegionRaresTreasures, v1.01b
  HHTD, v2.4.5
  IceHUD, v1.10.15
  LibAboutPanel, v1.6.2
  LibSharedMedia30, v3.0-97
  MasterPlanA, vA
  MinimapButtonFrame, v3.1.10e
  MinimapButtonFrameSkinPack, v3.0.1b
  NomiCakes, v7.2.0.1
  NPCScan, v7.1.0.5
  Omen, v3.1.12
  OmniCC, v7.1.1
  Paste, v1.4.10
  Postal, vv3.5.8
  Quartz, v3.3.3
  RangeDisplay, vv4.6.0
  Raven, v
  SellJunk, v3.0.14
  SexyMap, vv7.2.0
  ShadowedUnitFrames, vv4.1.17
  Skada, v1.6.6
  Stubby, v7.3a.5701 (TasmanianThylacine)
  TidyPlates, v6.18.11
  TidyPlatesGraphite, v
  TidyPlatesGrey, v
  TidyPlatesNeon, v
  TidyPlatesQuatre, v
  TidyPlatesThreatPlates, v8.3.4
  TidyPlatesHub, v
  TidyPlatesWidgets, v
  TipTac, v16.10.27
  TipTacItemRef, v16.10.27
  TipTacTalents, v16.10.27
  TomTom, vv70100-1.0.1
  TurnIn, v2.1
  VendorBait, v6.0.0.10
  WIM, vr524
  WorldQuestTracker, v
  BlizRuntimeLib_enUS v7.2.0.70200 <none>
  (ck=797)

=== Swatter report during recheck with (most) other addons disabled ===
Date: 2017-04-01 12:19:07
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\AdiBags\widgets\ItemButton.lua line 352:
   attempt to index field 'UpgradeIcon' (a nil value)
Debug:
   AdiBags\widgets\ItemButton.lua:352: IsContainerItemAnUpgrade()
   AdiBags\widgets\ItemButton.lua:303: Update()
   AdiBags\widgets\ItemButton.lua:278: FullUpdate()
   AdiBags\widgets\ItemButton.lua:246:
      AdiBags\widgets\ItemButton.lua:234
   [C]: Show()
   AdiBags\widgets\Section.lua:112:
      AdiBags\widgets\Section.lua:110
   [C]: Show()
   AdiBags\widgets\ContainerFrame.lua:952: PrepareSections()
   AdiBags\widgets\ContainerFrame.lua:1058: FullUpdate()
   AdiBags\widgets\ContainerFrame.lua:563:
      AdiBags\widgets\ContainerFrame.lua:549
   [C]: ?
   AdiBags\core\Utility.lua:89:
      AdiBags\core\Utility.lua:81
   AdiBags\widgets\LayeredRegion.lua:119:
      AdiBags\widgets\LayeredRegion.lua:108
Locals:
self = AdiBagsBankItemButton17 {
 0 = <userdata>
 bag = -1
 inventorySlot = 56
 filterName = "Item category"
 IconBorder = <unnamed> {
 }
 IconQuestTexture = <unnamed> {
 }
 hasItem = true
 icon = AdiBagsBankItemButton17IconTexture {
 }
 container = AdiBagsContainer2 {
 }
 count = 3
 acquired = true
 UpdateTooltip = <function> defined @Interface\FrameXML\BankFrame.lua:40
 slot = 17
 section = AdiBagsSection25 {
 }
 IconTexture = AdiBagsBankItemButton17IconTexture {
 }
 texture = 237366
 itemLink = "[Dalaran Doughnut]"
 itemId = 42430
 Count = AdiBagsBankItemButton17Count {
 }
 NormalTexture = AdiBagsBankItemButton17NormalTexture {
 }
 Stock = AdiBagsBankItemButton17Stock {
 }
 searchOverlay = AdiBagsBankItemButton17SearchOverlay {
 }
 Cooldown = AdiBagsBankItemButton17Cooldown {
 }
 bagFamily = 0
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'UpgradeIcon' (a nil value)"

AddOns:
  Swatter, v7.3a.5701 (TasmanianThylacine)
  ACP, v3.4.30 
  AdiBags, vv1.9.5
  BlizRuntimeLib_enUS v7.2.0.70200 <none>
  (ck=78)

**Comment by Talyrius** [comment] 2017-04-01 19:25
Duplicate of #174.

**Closed by Talyrius** 2017-04-01 19:25 UTC
Labels: duplicate
