### ISSUE TITLE
8.1.5 bags dont open anymore

### ISSUE THREAD

**Issue by keltharthelegend** [AdiAddons/AdiBags#333] opened 2019-03-12 18:57 UTC
Like the title says, as of todays patch 8.1.5 the bags wont open. They make the sound of opening but nothing shows on screen.

**Comment by davidholland** [comment] 2019-03-12 19:03
This is a duplicate of #332

**Comment by samuraininja93** [comment] 2019-03-12 22:38
Error in AdiBags: Interface\addOns\AdiBags\widgets\ContainerFrame/lua:555:attempt to index field 'Title' (a nil value) -- details: [Error 0000020453681070]

Patch *8.1.5
AdiBags v1.9.13

**Comment by samuraininja93** [comment] 2019-03-12 22:42
3 errors actually when you use the addon.

Error in AdiBags: Interface\addOns\AdiBags\widgets\ContainerFrame/lua:714:attempt to index field 'BagSlotPanel' (a nil value) -- details: [Error 000002042144FF10]

Error in AdiBags: Interface\addOns\AdiBags\widgets\ContainerFrame/lua:97:attempt to index field 'Anchor' (a nil value) -- details: [Error 0000020453680F80]

Error in AdiBags: Interface\addOns\AdiBags\widgets\ContainerFrame/lua:555:attempt to index field 'Title' (a nil value) -- details: [Error 0000020453681070]

**Comment by Av8oR127** [comment] 2019-03-12 22:49
![AdiBagsError](https://user-images.githubusercontent.com/47282225/54241513-8fb31580-44f7-11e9-9c25-642909b9a51c.PNG)
Happens when trying to open bags via any source.

**Closed** 2019-03-13 16:24 UTC
Labels: Duplicate
