### ISSUE TITLE
LUA error every time i open bags

### ISSUE THREAD

**Issue by Wutname1** [AdiAddons/AdiBags#836] opened 2022-11-29 21:41 UTC
### Addon Version

1.9.49

### World of Warcraft Version

Retail

### Describe the bug

10x Interface/AddOns/AdiBags/modules/ItemLevel.lua:466: bad argument #1 to 'unpack' (table expected, got nil)
[string "=[C]"]: ?
[string "@Interface/AddOns/AdiBags/modules/ItemLevel.lua"]:466: in function `?'
[string "@Interface/AddOns/AdiBags/modules/ItemLevel.lua"]:170: in function `UpdateButton_Retail'
[string "@Interface/AddOns/AdiBags/modules/ItemLevel.lua"]:131: in function `?'
[string "@Interface/AddOns/AdiBags/libs/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:119: in function <...ags/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Interface/AddOns/AdiBags/libs/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:29: in function <...ags/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:25>
[string "@Interface/AddOns/AdiBags/libs/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:64: in function `SendMessage'
[string "@Interface/AddOns/AdiBags/widgets/ItemButton.lua"]:348: in function `Update'
[string "@Interface/AddOns/AdiBags/widgets/ItemButton.lua"]:315: in function `FullUpdate'
[string "@Interface/AddOns/AdiBags/widgets/ItemButton.lua"]:273: in function <Interface/AddOns/AdiBags/widgets/ItemButton.lua:261>
[string "=[C]"]: in function `Show'
[string "@Interface/AddOns/AdiBags/widgets/ContainerFrame.lua"]:1063: in function `PrepareSections'
[string "@Interface/AddOns/AdiBags/widgets/ContainerFrame.lua"]:1184: in function `FullUpdate'
[string "@Interface/AddOns/AdiBags/widgets/ContainerFrame.lua"]:616: in function <Interface/AddOns/AdiBags/widgets/ContainerFrame.lua:602>
[string "=[C]"]: ?
[string "@Interface/AddOns/AdiBags/core/Utility.lua"]:102: in function <Interface/AddOns/AdiBags/core/Utility.lua:94>
[string "@Interface/AddOns/AdiBags/widgets/LayeredRegion.lua"]:119: in function <Interface/AddOns/AdiBags/widgets/LayeredRegion.lua:108>

### Steps to reproduce

Open bags

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by Cidan** [comment] 2022-11-29 21:47
Fixed in .50, please update :)

**Closed by Cidan** 2022-11-29 21:47 UTC
Labels: Bug, Pending

**Comment by Talyrius** [comment] 2022-11-30 09:16
Duplicate of #818.
