### ISSUE TITLE
Lua erroer container Frame

### ISSUE THREAD

**Issue by p4sky** [AdiAddons/AdiBags#249] opened 2017-12-07 01:16 UTC
Irecive this error random when open the bag 

> 
Interface\AddOns\AdiBags\widgets\ContainerFrame.lua:996: AdiBagsSection3:SetPoint(): AdiBagsSection5 is dependent on this -- details: [Error 00000249FAAD42B0] 

>  
2x AdiBags\widgets\ContainerFrame.lua:996: AdiBagsSection3:SetPoint(): AdiBagsSection5 is dependent on this
[C]: in function `SetPoint'
AdiBags\widgets\ContainerFrame.lua:996: in function `LayoutSections'
AdiBags\widgets\ContainerFrame.lua:1067: in function <AdiBags\widgets\ContainerFrame.lua:1041>
(tail call): ?
AdiBags\widgets\ContainerFrame.lua:447: in function `RefreshContents'
AdiBags\widgets\ContainerFrame.lua:432: in function `ResumeUpdates'
AdiBags\widgets\ContainerFrame.lua:415: in function <AdiBags\widgets\ContainerFrame.lua:407>
[C]: in function `Show'
AdiBags\core\Bags.lua:89: in function `Open'
AdiBags\core\Hooks.lua:112: in function <AdiBags\core\Hooks.lua:109>
(tail call): ?
(tail call): ?
[string "OPENALLBAGS"]:1: in function <[string "OPENALLBAGS"]:1>

Locals:
(*temporary) = AdiBagsSection3 {
 0 = <userdata>
 acquired = true
 buttons = <table> {
 }
 Header = <unnamed> {
 }
 slots = <table> {
 }
 width = 4
 count = 4
 total = 4
 name = "Hearthstones"
 category = "Hearthstones"
 height = 1
 key = "Hearthstones#Hearthstones"
 freeSlots = <table> {
 }
 container = AdiBagsContainer1 {
 }
}
(*temporary) = "TOPLEFT"
(*temporary) = AdiBagsSection5 {
 0 = <userdata>
 acquired = true
 buttons = <table> {
 }
 Header = <unnamed> {
 }
 slots = <table> {
 }
 width = 1
 count = 1
 total = 1
 name = "Weapon"
 category = "Equipment"
 height = 1
 key = "Equipment#Weapon"
 freeSlots = <table> {
 }
 container = AdiBagsContainer1 {
 }
}
(*temporary) = "TOPRIGHT"
(*temporary) = 10.5
(*temporary) = 0

**Comment by SpareSimian** [comment] 2018-01-08 01:40
Looks like a duplicate of #237.

**Closed** 2022-08-21 02:28 UTC
