### ISSUE TITLE
LUA error message

### ISSUE THREAD

**Issue by kaseyd24** [AdiAddons/AdiBags#611] opened 2021-10-19 16:07 UTC
Getting the following.
Message: Interface\AddOns\AdiBags\core\Filters.lua:126: Usage: NewModule(name, [prototype, [lib, lib, lib, ...]): 'name' - Module 'Anima' already exists.
Time: Tue Oct 19 12:04:31 2021
Count: 1
Stack: Interface\AddOns\AdiBags\core\Filters.lua:126: Usage: NewModule(name, [prototype, [lib, lib, lib, ...]): 'name' - Module 'Anima' already exists.
[string "=[C]"]: ?
[string "@Interface\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua"]:239: in function `NewModule'
[string "@Interface\AddOns\AdiBags\core\Filters.lua"]:126: in function `RegisterFilter'
[string "@Interface\AddOns\AdiBags_Shadowlands\AdiBags_Shadowlands.lua"]:32: in main chunk

Locals: (*temporary) = "Usage: NewModule(name, [prototype, [lib, lib, lib, ...]): 'name' - Module 'Anima' already exists."

**Comment by Talyrius** [comment] 2022-02-08 03:26
This error is due to conflicting module names being used by other AdiBags addons. I suggest you remove one of them.

Duplicate of https://github.com/AdiAddons/AdiBags/issues/51.

**Closed by Talyrius** 2022-02-08 03:26 UTC
Labels: Duplicate
