### ISSUE TITLE
Module error

### ISSUE THREAD

**Issue by richyvee** [AdiAddons/AdiBags#837] opened 2022-11-30 00:03 UTC
### Addon Version

v1.9.49

### World of Warcraft Version

Retail

### Describe the bug

not too sure what caused the bug, but after killing and looting the raremob "Vakrill" i got this lua error

21x AdiBags/modules/ItemLevel.lua:466: bad argument #1 to 'unpack' (table expected, got nil)
[string "=[C]"]: ?
[string "@AdiBags/modules/ItemLevel.lua"]:466: in function `?'
[string "@AdiBags/modules/ItemLevel.lua"]:170: in function `UpdateButton_Retail'
[string "@AdiBags/modules/ItemLevel.lua"]:131: in function `?'
[string "@LibSharedMedia-3.0-8020003/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:119: in function <...edia-3.0/CallbackHandler-1.0/CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@LibSharedMedia-3.0-8020003/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:29: in function <...edia-3.0/CallbackHandler-1.0/CallbackHandler-1.0.lua:25>
[string "@LibSharedMedia-3.0-8020003/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:64: in function `SendMessage'
[string "@AdiBags/widgets/ItemButton.lua"]:348: in function `Update'
[string "@AdiBags/widgets/ItemButton.lua"]:315: in function `FullUpdate'
[string "@AdiBags/widgets/ItemButton.lua"]:273: in function <AdiBags/widgets/ItemButton.lua:261>
[string "=[C]"]: in function `Show'
[string "@AdiBags/core/Bags.lua"]:96: in function `Open'
[string "@AdiBags/core/Hooks.lua"]:115: in function <AdiBags/core/Hooks.lua:112>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "OPENALLBAGS"]:1: in function <[string "OPENALLBAGS"]:1>

### Steps to reproduce

1. since the bug showed up after killing the mob, i suggest kill that mob? 
2. open bags

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by Talyrius** [comment] 2022-11-30 09:17
Duplicate of #818.

**Closed by Talyrius** 2022-11-30 09:17 UTC
Labels: Duplicate
