### ISSUE TITLE
[Bug]: Bank Bag Slot 1 not visible.

### ISSUE THREAD

**Issue by Nefram56** [AdiAddons/AdiBags#754] opened 2022-10-29 22:20 UTC
### Addon Version

v1.9.46zip

### World of Warcraft Version

Retail

### Describe the bug

When opening the bank, the first bag slot can't be equipped while the addon is enabled.  The slot shows as blank and when you try to equip a bag in that slot you get an error saying, "this item cannot stack."  When clicking on the v button on the bank frame it only shows bags 2-7 in the drop down menu after bank.
![2022-10-29](https://user-images.githubusercontent.com/116981642/198854289-da5824de-1d08-413f-acec-b37f4e080032.png)

### Steps to reproduce

I don't know.  I didn't notice this issue until after pre-patch dropped on OCT 25th.  I've disabled the addon completely and the bag is still there.  It's just not visible while the addon is enabled. I've checked on multiple characters and it's the same even with different bag types.

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by Cidan** [comment] 2022-10-29 22:32
I've noticed this too, actually, and I'm pretty sure I know what the cause is. I'll try to get this fix in on the next release.

**Comment by zalidthebur** [comment] 2022-11-06 03:16
Still an issue and it hides the contents of the bags. Was thinking I'd gone mad when I knew there was a load of Skystone in my bank as the proff window was showing them, but I could not find them. I tried with a new savedvariables to see if was a setting I'd changed somehow. But still the same.

**Comment by ryankhart** [comment] 2022-11-07 08:11
I'm experiencing this too.

I had a completely empty bank with no bags installed. I tried to put a bag in the first slot, and it gave a "no equipment slot available for that item" error.

So, I tried deactivating Adibags, and tried it again in the vanilla UI, and it worked. Then, when I re-enabled Adibags, that bag I had put into the 1st slot visually was in the 2nd slot in Adibags.

**Comment by Cidan** [comment] 2022-11-07 08:17
Hi.

We do know what the bug is -- there was an undocumented change in the Blizzard API that kept track of bank bag offsets. As mentioned above, this will be fixed in the next release (this week).

**Comment by Talyrius** [comment] 2022-11-24 07:18
This should be fixed. If not, please open a new issue.

**Closed by Talyrius** 2022-11-24 07:18 UTC
Labels: Bug, Fixed/Implemented
