### ISSUE TITLE
Artifact Item level does not reflect Netherlight Crucible

### ISSUE THREAD

**Issue by kdubato** [AdiAddons/AdiBags#255] opened 2017-12-31 18:47 UTC
When viewing the artifacts in your bag, the item level does not reflect the +15 ilvls that come with the Netherlight crucible. 

Here is a screenshot highlighting the difference.

![image](https://user-images.githubusercontent.com/987601/34463642-8d2a5b74-ee28-11e7-8763-0ad66dc67f9e.png)

**Comment by Talyrius** [comment] 2018-01-01 03:13
Can you confirm whether installing the latest version of [LibItemUpgradeInfo-1.0](https://www.curseforge.com/wow/addons/libitemupgradeinfo-1-0) fixes the issue?

It appears that [GetDetailedItemLevelInfo](https://wow.gamepedia.com/API_GetDetailedItemLevelInfo) now makes it much easier to determine iLvl.

**Comment by SpareSimian** [comment] 2018-01-01 03:57
I confirmed the issue and I'm not seeing a change with the new library. So it seems like the API isn't factoring in the crucible upgrades, either. I wonder what the code for the standard tooltip looks like, since that displays the correct value?

**Comment by SpareSimian** [comment] 2018-01-01 04:13
I dug through the new lib and see a /checkslot command for debugging. I'll see what that has to say.

**Comment by SpareSimian** [comment] 2018-01-01 04:43
Alas, it's worse than expected: GetDetailedItemLevelInfo is returning 750,false,750 for my main hand (slot 16) so it's not even showing the results of applied Artifact Power. The bag shows 909 and the tooltip shows 914. 

I found I had to patch the library, adding this sequence to the start of the /checkslot function to force the Blizzard debug library to load:

`    if not DevTools_Dump then
        LoadAddOn("Blizzard_DebugTools")
    end
    if not DevTools_Dump then
	    _G.print("No DevTools_Dump!")
		return
	end
`

**Comment by jec324** [comment] 2018-08-03 12:21
This is no longer an issue because the NLC was removed.  Might be a similar issue with the azerite pieces in bfa but this should be closed for now.

**Comment by Talyrius** [comment] 2018-08-15 10:29
Fixed via 2d532c8.

**Closed by Talyrius** 2018-08-15 10:29 UTC
Labels: Bug
