### ISSUE TITLE
Bags will not open / multiple lua errors

### ISSUE THREAD

**Issue by FelixFTW** [AdiAddons/AdiBags#789] opened 2022-11-18 00:45 UTC
### Addon Version

1.9.46

### World of Warcraft Version

Retail

### Describe the bug

Bags are:
1x Backpack (20 slots)
4x Lightless Silk Pouch (32 slots ea)
1x Storm-Batterred Reagent Bag (20 Slot)

Only running Addons are:
AdiBags
AdiBags Configuration
BugGrabber
BugSack

Error Messages:
4x FrameXML\Bindings.xml:1 Interface/AddOns/AdiBags/modules/Junk.lua:1 (null)

18x Interface/AddOns/AdiBags/widgets/ContainerFrame.lua:599: attempt to call method 'FullUpdate' (a nil value)
[string "=(tail call)"]: ?
[string "@Interface/AddOns/AdiBags/widgets/LayeredRegion.lua"]:119: in function <Interface/AddOns/AdiBags/widgets/LayeredRegion.lua:108>

40x Interface/AddOns/AdiBags/core/Layout.lua:62: attempt to index field 'anchor' (a nil value)
[string "@Interface/AddOns/AdiBags/core/Layout.lua"]:62: in function <Interface/AddOns/AdiBags/core/Layout.lua:61>
[string "@Interface/AddOns/AdiBags/core/Layout.lua"]:111: in function `LayoutBags'
[string "@Interface/AddOns/AdiBags/core/Layout.lua"]:130: in function `UpdatePositionMode'
[string "@Interface/AddOns/AdiBags/core/Core.lua"]:179: in function <Interface/AddOns/AdiBags/core/Core.lua:122>
[string "=[C]"]: ?
[string "@Interface/AddOns/AdiBags/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <...ce/AddOns/AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Interface/AddOns/AdiBags/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Interface/AddOns/AdiBags/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:626: in function <...ce/AddOns/AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:611>

### Steps to reproduce

(1) Login to character
(2) Clicking on the "Bag" icon
(3) Typing "b"

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by mwm23** [comment] 2022-11-18 02:26
I am having the same issue, addon doesn't show any bags. Disabled all addons and when I hit bags I see nothing but my currency
![WoWScrnShot_111722_212557](https://user-images.githubusercontent.com/118496551/202602611-c831df6f-177d-4686-9fb7-19c0bd76c29c.jpg)

**Comment by mwm23** [comment] 2022-11-18 03:01
This is a list of all the errors with just the default UI and adibags and bug sack installed 



1x Interface/AddOns/AdiBags/core/Utility.lua:334: Usage: GetItemSubClassInfo(itemClassID, itemSubClassID)
[string "=[C]"]: in function `GetItemSubClassInfo'
[string "@Interface/AddOns/AdiBags/core/Utility.lua"]:334: in main chunk

Locals:
(*temporary) = nil
(*temporary) = 0

-----------------

1x Interface/AddOns/AdiBags/widgets/ContainerFrame.lua:783: Usage: GetItemClassInfo(itemClassID)
[string "=[C]"]: in function `GetItemClassInfo'
[string "@Interface/AddOns/AdiBags/widgets/ContainerFrame.lua"]:783: in main chunk

Locals:
(*temporary) = nil

----------------------------------

1x Interface/AddOns/AdiBags/modules/FilterOverride.lua:57: Usage: GetItemSubClassInfo(itemClassID, itemSubClassID)
[string "=[C]"]: in function `GetItemSubClassInfo'
[string "@Interface/AddOns/AdiBags/modules/FilterOverride.lua"]:57: in main chunk

Locals:
(*temporary) = nil
(*temporary) = 0

----------------------------------------------

1x Interface/AddOns/AdiBags/modules/Junk.lua:50: Usage: GetItemSubClassInfo(itemClassID, itemSubClassID)
[string "=[C]"]: in function `GetItemSubClassInfo'
[string "@Interface/AddOns/AdiBags/modules/Junk.lua"]:50: in main chunk

Locals:
(*temporary) = nil
(*temporary) = 0

---------------------------------------

1x Interface/AddOns/AdiBags/core/DefaultFilters.lua:44: Usage: GetItemClassInfo(itemClassID)
[string "=[C]"]: in function `GetItemClassInfo'
[string "@Interface/AddOns/AdiBags/core/DefaultFilters.lua"]:44: in function `SetupDefaultFilters'
[string "@Interface/AddOns/AdiBags/core/Filters.lua"]:65: in function `InitializeFilters'
[string "@Interface/AddOns/AdiBags/core/Core.lua"]:97: in function <Interface/AddOns/AdiBags/core/Core.lua:81>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@Interface/AddOns/AdiBags/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <...ce/AddOns/AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Interface/AddOns/AdiBags/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:494: in function `InitializeAddon'
[string "@Interface/AddOns/AdiBags/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:619: in function <...ce/AddOns/AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:611>

----------------------------------

1x Interface/AddOns/AdiBags/modules/TooltipInfo.lua:55: GameTooltip doesn't have a "OnTooltipSetItem" script
[string "=[C]"]: in function `HookScript'
[string "@Interface/AddOns/AdiBags/modules/TooltipInfo.lua"]:55: in function <Interface/AddOns/AdiBags/modules/TooltipInfo.lua:53>
[string "=[C]"]: ?
[string "@Interface/AddOns/AdiBags/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <...ce/AddOns/AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Interface/AddOns/AdiBags/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Interface/AddOns/AdiBags/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:536: in function `EnableAddon'
[string "@Interface/AddOns/AdiBags/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:626: in function <...ce/AddOns/AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:611>

----------------------

3x Interface/AddOns/AdiBags/modules/DataSource.lua:123: attempt to call upvalue 'GetContainerNumSlots' (a nil value)
[string "@Interface/AddOns/AdiBags/modules/DataSource.lua"]:123: in function <Interface/AddOns/AdiBags/modules/DataSource.lua:119>
[string "@Interface/AddOns/AdiBags/modules/DataSource.lua"]:152: in function `Update'
[string "@Interface/AddOns/AdiBags/modules/DataSource.lua"]:78: in function <Interface/AddOns/AdiBags/modules/DataSource.lua:70>
[string "=[C]"]: ?
[string "@Interface/AddOns/AdiBags/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <...ce/AddOns/AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Interface/AddOns/AdiBags/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Interface/AddOns/AdiBags/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:536: in function `EnableAddon'
[string "@Interface/AddOns/AdiBags/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:626: in function <...ce/AddOns/AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:611>

---------------------

4x Interface/AddOns/AdiBags/widgets/BagSlots.lua:227: attempt to call upvalue 'ContainerIDToInventoryID' (a nil value)
[string "=(tail call)"]: ?
[string "@Interface/AddOns/AdiBags/core/OO.lua"]:60: in function `Create'
[string "@Interface/AddOns/AdiBags/widgets/BagSlots.lua"]:464: in function `CreateBagSlotPanel'
[string "@Interface/AddOns/AdiBags/widgets/ContainerFrame.lua"]:172: in function <Interface/AddOns/AdiBags/widgets/ContainerFrame.lua:98>
[string "=[C]"]: ?
[string "@Interface/AddOns/AdiBags/core/Utility.lua"]:100: in function <Interface/AddOns/AdiBags/core/Utility.lua:92>
[string "@Interface/AddOns/AdiBags/core/OO.lua"]:60: in function <Interface/AddOns/AdiBags/core/OO.lua:52>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "@Interface/AddOns/AdiBags/core/Bags.lua"]:129: in function `GetFrame'
[string "@Interface/AddOns/AdiBags/core/Bags.lua"]:83: in function `Open'
[string "@Interface/AddOns/AdiBags/core/Hooks.lua"]:112: in function <Interface/AddOns/AdiBags/core/Hooks.lua:109>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "OPENALLBAGS"]:1: in function <[string "OPENALLBAGS"]:1>

----------------------
1x Interface/AddOns/AdiBags/widgets/ContainerFrame.lua:264: Usage: RegisterMessage("eventname", "methodname"): self was not a table?
[string "=(tail call)"]: ?
[string "@Interface/AddOns/AdiBags/core/OO.lua"]:60: in function <Interface/AddOns/AdiBags/core/OO.lua:52>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "@Interface/AddOns/AdiBags/core/Bags.lua"]:129: in function `GetFrame'
[string "@Interface/AddOns/AdiBags/core/Bags.lua"]:83: in function `Open'
[string "@Interface/AddOns/AdiBags/core/Hooks.lua"]:112: in function <Interface/AddOns/AdiBags/core/Hooks.lua:109>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "OPENALLBAGS"]:1: in function <[string "OPENALLBAGS"]:1>

--------------------


2x Interface/AddOns/AdiBags/widgets/ContainerFrame.lua:638: attempt to call upvalue 'GetContainerNumSlots' (a nil value)
[string "@Interface/AddOns/AdiBags/widgets/ContainerFrame.lua"]:638: in function `UpdateContent'
[string "@Interface/AddOns/AdiBags/widgets/ContainerFrame.lua"]:481: in function `RefreshContents'
[string "@Interface/AddOns/AdiBags/widgets/ContainerFrame.lua"]:468: in function `ResumeUpdates'
[string "@Interface/AddOns/AdiBags/widgets/ContainerFrame.lua"]:451: in function <Interface/AddOns/AdiBags/widgets/ContainerFrame.lua:443>
[string "=[C]"]: in function `Show'
[string "@Interface/AddOns/AdiBags/core/Bags.lua"]:89: in function `Open'
[string "@Interface/AddOns/AdiBags/core/Hooks.lua"]:112: in function <Interface/AddOns/AdiBags/core/Hooks.lua:109>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "OPENALLBAGS"]:1: in function <[string "OPENALLBAGS"]:1>

Locals:
self = AdiBagsContainer1 {
 0 = <userdata>
 firstLoad = true
 HeaderLeftRegion = AdiBagsSimpleLayeredRegion1 {
 }
 isBank = false
 OnBackdropLoaded = <function> defined @Interface/SharedXML/Backdrop.lua:152
 GetBackdropColor = <function> defined @Interface/SharedXML/Backdrop.lua:390
 SetBackdropBorderColor = <function> defined @Interface/SharedXML/Backdrop.lua:422
 BagSlotButton = CheckButton {
 }
 BottomLeftRegion = AdiBagsSimpleLayeredRegion3 {
 }
 sameChanged = <table> {
 }
 forceLayout = true
 isReagentBank = false
 ApplyBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:294
 SetBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:329
 ClearBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:282
 paused = false
 GetBackdropBorderColor = <function> defined @Interface/SharedXML
Backdrop.lua:409
 GetBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:347
 Center = Texture {
 }
 RightEdge = Texture {
 }
 LeftEdge = Texture {
 }
 content = <table> {
 }
 BottomEdge = Texture {
 }
 removed = <table> {
 }
 Anchor = AdiBagsBagAnchor1 {
 }
 itemGUIDtoItem = <table> {
 }
 sections = <table> {
 }
 BottomRightCorner = Texture {
 }
 changed = <table> {
 }
 added = <table> {
 }
 ToSortSection = AdiBagsSection1 {
 }
 BottomLeftCorner = Texture {
 }
 stacks = <table> {
 }
 SetupTextureCoordinates = <function> defined @Interface/SharedXML/Backdrop.lua:214
 OnBackdropSizeChanged = <function> defined @Interface/SharedXML/Backdrop.lua:182
 HasBackdropInfo = <function> defined @Interface/SharedXML/Backdrop.lua:278
 TopRightCorner = Texture {
 }
 TopLeftCorner = Texture {
 }
 backdropInfo = <table> {
 }
 dirtyLayout = true
 GetEdgeSize = <function> defined @Interface/SharedXML/Backdrop.lua:188
 Content = Frame {
 }
 buttons = <table> {
 }
 TopEdge = Texture {
 }
 HeaderRightRegion = AdiBagsSimpleLayeredRegion2 {
 }
 BottomRightRegion = AdiBagsSimpleLayeredRegion4 {
 }
 widgets = <table> {
 }
 SetBorderBlendMode = <function> defined @Interface/SharedXML/Backdrop.lua:266
 CloseButton = Button {
 }
 Title = AdiBagsContainer1Title {
 }
 bagObject = <table> {
 }
 SetupPieceVisuals = <function> defined @Interface/SharedXML/Backdrop.lua:246
 SetBackdropColor = <function> defined @Interface/SharedXML/Backdrop.lua:399
 BagSlotPanel = AdiBagsContainer1Bags {
 }
 name = "Backpack"
}
bag = 1
added = <table> {
}
removed = <table> {
}
changed = <table> {
}
sameChanged = <table> {
}
content = <table> {
 size = 0
}
(*temporary) = nil
(*temporary) = 1
(*temporary) = "attempt to call upvalue 'GetContainerNumSlots' (a nil value)"
GetContainerNumSlots = nil
GetContainerNumFreeSlots = nil
GetContainerItemID = nil
GetContainerItemLink = nil
addon = <table> {
 AcquireItemButton = <function> defined @Interface/AddOns/AdiBags/widgets/ItemButton.lua:173
 FAMILY_TAGS = <table> {
 }
 UpdateFilters = <function> defined @Interface/AddOns/AdiBags/core/Filters.lua:83
 SecureHook = <function> defined @Interface/AddOns/AdiBags/libs/AceHook-3.0/AceHook-3.0.lua:335
 GetInteractingWindow = <function> defined @Interface/AddOns/AdiBags/core/Core.lua:440
 ConfigChanged = <function> defined @Interface/AddOns/AdiBags/core/Core.lua:360
 SetDefaultModulePrototype = <function> defined @Interface/AddOns/AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:405
 Filter = <function> defined @Interface/AddOns/AdiBags/core/Filters.lua:144
 IsEnabled = <function> defined @Interface/AddOns/AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:447
 Reconfigure = <function> defined @Interface/AddOns/AdiBags/core/Core.lua:190
 SetupTooltip = <function> defined @Interface/AddOns/AdiBags/core/Utility.lua:125
 RegisterMessage = <function> defined @Interface/AddOns/AdiBags/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:90
 UnregisterMessage = <function> defined @Interface/AddOns/AdiBags/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:153
 hooks = <table> {
 }
 GetDistinctItemID = <function> defined @Interface/AddOns/AdiBags/core/Utility.lua:301
 CreateFont = <function> defined @Interface/AddOns/AdiBags/core/Fonts.lua:122
 isClassic = false
 db = <table> {
 }
 OpenOpti


-----

4x Interface/AddOns/AdiBags/core/Layout.lua:62: attempt to index field 'anchor' (a nil value)
[string "@Interface/AddOns/AdiBags/core/Layout.lua"]:62: in function <Interface/AddOns/AdiBags/core/Layout.lua:61>
[string "@Interface/AddOns/AdiBags/core/Layout.lua"]:111: in function `LayoutBags'
[string "@Interface/AddOns/AdiBags/core/Layout.lua"]:130: in function `UpdatePositionMode'
[string "@Interface/AddOns/AdiBags/core/Core.lua"]:179: in function <Interface/AddOns/AdiBags/core/Core.lua:122>
[string "=[C]"]: ?
[string "@Interface/AddOns/AdiBags/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <...ce/AddOns/AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Interface/AddOns/AdiBags/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Interface/AddOns/AdiBags/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:626: in function <...ce/AddOns/AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:611>


-------------

2x Interface/AddOns/AdiBags/widgets/ContainerFrame.lua:599: attempt to call method 'FullUpdate' (a nil value)
[string "=(tail call)"]: ?
[string "@Interface/AddOns/AdiBags/widgets/LayeredRegion.lua"]:119: in function <Interface/AddOns/AdiBags/widgets/LayeredRegion.lua:108>

**Comment by Elboufda** [comment] 2022-11-18 04:04
same for me

**Comment by Rycia** [comment] 2022-11-18 04:16
I get the same issue. Adibags won't work period right now; bags aren't openable.

**Comment by mkh67465** [comment] 2022-11-18 07:58
Same issue here, cant open bags

**Comment by SpareSimian** [comment] 2022-11-18 11:32
Duplicate of bug #782. I recommend closing this one and continuing there, where an interim release is available.

**Closed** 2022-11-18 18:17 UTC
Labels: Bug, Pending
