### ISSUE TITLE
302x AdiBags\core\Filters-Filters.lua:126: Usage: NewModule(name, [prototype, [lib, lib, lib, ...]): 'name' - Module 'Bound' already exists.

### ISSUE THREAD

**Issue by als30334** [AdiAddons/AdiBags#69] opened 2015-12-25 00:18 UTC
The rest is

302x AdiBags\core\Filters-Filters.lua:126: Usage: NewModule(name, [prototype, [lib, lib, lib, ...]): 'name' - Module 'Bound' already exists.
[C]: ?
...ceAdiBags\libs\AceAddon-3.0\AceAddon-3.0-12.lua:270: in function `NewModule'
AdiBags\core\Filters-Filters.lua:126: in function `RegisterFilter'
AdiBags_Bound\AdiBags_Bound-v1.1.lua:52: in main chunk

Locals:
self = <table> {
 AcquireItemButton = <function> defined @AdiBags\widgets\ItemButton.lua:149
 modules = <table> {
 }
 UpdateFilters = <function> defined @AdiBags\core\Filters.lua:83
 SecureHook = <function> defined @AdiBags\libs\AceHook-3.0\AceHook-3.0.lua:336
 GetInteractingWindow = <function> defined @AdiBags\core\Core.lua:451
 ConfigChanged = <function> defined @AdiBags\core\Core.lua:371
 GetSlotId = <function> defined @AdiBags\core\Utility.lua:57
 Filter = <function> defined @AdiBags\core\Filters.lua:144
 IsEnabled = <function> defined @AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:482
 Reconfigure = <function> defined @AdiBags\core\Core.lua:183
 SetupTooltip = <function> defined @AdiBags\core\Utility.lua:114
 RegisterMessage = <function> defined @CallbackHandler-1.0\CallbackHandler-1.0\CallbackHandler-1.0.lua:116
 UnregisterMessage = <function> defined @CallbackHandler-1.0\CallbackHandler-1.0\CallbackHandler-1.0.lua:179
 hooks = <table> {
 }
 GetDistinctItemID = <function> defined @AdiBags\core\Utility.lua:187
 CreateFont = <function> defined @AdiBags\core\Fonts.lua:122
 filterProto = <table> {
 }
 db = <table> {
 }
 OpenOptions = <function> defined @AdiBags\core\Core.lua:289
 SetEnabledState = <function> defined @AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:455
 Hook = <function> defined @AdiBags\libs\AceHook-3.0\AceHook-3.0.lua:274
 IterateBags = <function> defined @AdiBags\core\Bags.lua:183
 OnEnable = <function> defined @AdiBags\core\Core.lua:115
 HookBagFrameCreation = <function> defined @AdiBags\core\Bags.lua:304
 NewBag = <function> defined @AdiBags\core\Bags.lua:150
 GetClass = <function> defined @AdiBags\core\OO.lua:128
 RegisterFilter = <function> defined @AdiBags\core\Filters.lua:120
 BACKDROP = <table> {
 }
 OnInitialize = <function> defined =[C]:-1
 NewModule = <function> defined @AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:266
 InitializeFilters = <function> defined @AdiBags\core\Filters.lua:64
 IterateFilters = <function> defined @AdiBags\core\Filters.lua:116
 ReagentBankUpdated = <function> defined @AdiBags\core\Core.lua:362
 CreateBagSlotPanel = <function> defined @AdiBags\widgets\BagSlots.lua:437
 TOP_PADDING = 32
 BI = <table> {
 }
 hookedBags = <table> {
 }
 OpenBag = <function> defined @AdiBags\core\Hooks.lua:137
 ToggleAllBags = <function> defined @AdiBags\core\Hooks.lua:86
 OnProfileChanged = <function> defined @AdiBags\core\Core.lua:191
 GetName = <function> defined @AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:310
 name = "AdiBags"
 OpenBackpack = <function> defined @AdiBags\core\Hooks.lua:168
 LayoutBags = <function> defined @AdiBags\core\Layout.lua:101
 Disable = <function> defined @AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:345
 SetGlobalLock = <function> defined @AdiBags\core\Core.lua:419
 Unhook = <function> defined @AdiBags\libs\AceHook-3.0\AceHook-3.0.lua:418
 Print = <function> defined @AdiBags\libs\AceConsole-3.0\AceConsole-3.0.lua:54
 OpenAllBags = <function> defined @AdiBags\core\Hooks.lua:109
 L = <table> {
 }
 safecall = <function> defined @AdiBags\core\Utility.lua:81
 Debug = <function> defined @AdiBags\core\Core.lua:61
 CreateAnchorWidget = <function> defined @AdiBags\widgets\AnchorWidget.lua:37
 CompareSectionKeys = <function> defined @AdiBags\core\Utility.lua:220
 DEFAULT_SETTINGS = <table> {
 }
 CreateBagAnchorWidget = <function> defined @AdiBags\

**Comment by Cidan** [comment] 2016-07-25 22:56
I am closing this issue unless you run into it again.

**Closed by Cidan** 2016-07-25 22:56 UTC

**Comment by Talyrius** [comment] 2018-03-14 11:24
This error is due to conflicting module names being used by other AdiBags addons. I suggest you remove one of them.

Duplicate of #51.
