### ISSUE TITLE
[Feature]: Option to Show Crafted Quality

### ISSUE THREAD

**Issue by ZyRage** [AdiAddons/AdiBags#855] opened 2022-12-14 00:20 UTC
### Describe the feature

The crafting materials and crafted items in the bags does not show the quality they have. Like Bronze, Silver, Gold and so on.
I could not find a option for that in AdiBags.
Would be nice if you can add this option so I can see again at the first glance what quality they have.
![Quality](https://user-images.githubusercontent.com/97050229/207473322-5f89b831-258a-4ecc-9706-c0136b928b81.png)

They are showing in my crafting window and where also in my bags before installing AdiBags. (Screenshot just to show what I'm talking about)
![Quality2](https://user-images.githubusercontent.com/97050229/207473414-aaa9dc4f-6cf9-49df-98c4-9e14c7fe2eb7.png)

### Describe the implementation

Option to enable "Crafted Quality" to show on the item icon again.

**Comment by Talyrius** [comment] 2022-12-14 12:13
This is a duplicate of issue #840.

**Closed by Talyrius** 2022-12-14 12:13 UTC
Labels: Duplicate
