### ISSUE TITLE
Pawn Upgrade Advisor icons not showing

### ISSUE THREAD

**Issue by trininja2k** [AdiAddons/AdiBags#156] opened 2016-12-27 19:10 UTC
In WoW 7.1 there is a new API feature, IsContainerItemAnUpgrade that can display green arrows on upgrades on your item icons. The vanilla wow client doesn't use that feature atm, but Pawn uses that API feature to display the green arrows and AdiBags seems to not allow Pawn to modify the icon display to show the green arrow. Can you implement that feature in any way or better allow Pawn to modify the item icon?

**Comment by p5hema2** [comment] 2017-01-26 08:16
add to widgets\ItemButton.lua

after Line 305:
```
self:IsContainerItemAnUpgrade()
```

and after 335:
```
function buttonProto:IsContainerItemAnUpgrade()	
	local itemIsUpgrade = IsContainerItemAnUpgrade(self:GetParent():GetID(), self:GetID());
	if ( itemIsUpgrade == nil ) then -- nil means not all the data was available to determine if this is an upgrade.
		self.UpgradeIcon:SetShown(false);
	else
		self.UpgradeIcon:SetShown(itemIsUpgrade);
	end
end
```

**Comment by trininja2k** [comment] 2017-01-27 03:35
Thank you very much, I found out how I can change the iLvL text position too and now it looks okay for me. ;)

**Comment by p5hema2** [comment] 2017-01-27 19:14
use this funtion, the above crashed on resource depod

```
function buttonProto:IsContainerItemAnUpgrade()	
	local itemIsUpgrade = IsContainerItemAnUpgrade(self:GetParent():GetID(), self:GetID());
	if ( itemIsUpgrade == nil and self.UpgradeIcon) then -- nil means not all the data was available to determine if this is an upgrade.
		self.UpgradeIcon:SetShown(false);
	elseif (self.UpgradeIcon) then
		self.UpgradeIcon:SetShown(itemIsUpgrade);
	end
end
```

**Comment by muxen** [comment] 2017-02-07 00:37
Please help. Mind you, I'm a complete newbie and know absolutely nothing about coding, so I've managed to mess it up several times. Where exactly should I paste that code?

Am I looking at the correct part when you mention line 305?
```

local bag, slot = self.bag, self.slot
	self.itemId = GetContainerItemID(bag, slot)
	self.itemLink = GetContainerItemLink(bag, slot)
	self.hasItem = not not self.itemId
	self.texture = GetContainerItemInfo(bag, slot)
	self.bagFamily = select(2, GetContainerNumFreeSlots(bag))
	self:Update()

```

and second part - after buttonProto:UpdateCount function? I honestly don't know what I'm doing, thanks for help

**Comment by Xelosy** [comment] 2017-02-12 11:07
How to change the ilvl text position?

**Comment by reddmond** [comment] 2017-02-24 06:49
@Xelosy: 
In modules/ItemLevel.lua, Line 105:
Replace "TOPLEFT" with "BOTTOMLEFT"

Alternatively you can mess with the numbers on that line to move it to wherever you like.

**Comment by lorddev** [comment] 2017-03-09 01:26
Can we get this fix merged into the next release please?

**Comment by Mrhgb** [comment] 2017-03-11 14:03
How do I change where the green arrow is positioned? It's currently behind the ilevel text, I'd like it to be in the middle at the bottom.

**Comment by Talyrius** [comment] 2017-03-31 17:34
This is a duplicate of #151.

**Closed by Talyrius** 2017-03-31 17:34 UTC
Labels: duplicate
