### ISSUE TITLE
Closing bags with 'esc' sometimes closes the bag AND opens the menu [FIX Included]

### ISSUE THREAD

**Issue by cloverpi** [AdiAddons/AdiBags#924] opened 2023-01-28 01:01 UTC
### Addon Version

v1.10.7

### World of Warcraft Version

Classic

### Describe the bug

When adibags is the only 'closeable' window you have open, pressing 'esc' to close it will close adibags AND open the in-game menu.

### Steps to reproduce

See above

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by cloverpi** [comment] 2023-01-28 01:03
AdiBags/core/Bags.lua
```
function bagProto:CreateFrame()
	frame = addon:CreateContainerFrame(self.bagName, self.isBank, self) 
	_G[addonName .. self.bagName] = 
    {
      Hide = function() frame:Hide() end,
      IsShown = function() return frame:IsShown() end
    }
  	tinsert(UISpecialFrames, addonName .. self.bagName)
	return frame
end
```

AdiBags/core/Core.lua
```
function addon:EnableHooks()
	self:RawHook("OpenAllBags", true)
	self:SecureHook("CloseAllBags")
	self:RawHook("ToggleAllBags", true)
	self:RawHook("ToggleBackpack", true)
	self:RawHook("ToggleBag", true)
	self:RawHook("OpenBag", true)
	self:SecureHook("CloseBag")
	self:RawHook("OpenBackpack", true)
	self:SecureHook("CloseBackpack")
	-- self:SecureHook('CloseSpecialWindows')
end

function addon:DisableHooks()
	self:Unhook("OpenAllBags")
	self:Unhook("CloseAllBags")
	self:Unhook("ToggleAllBags")
	self:Unhook("ToggleBackpack")
	self:Unhook("ToggleBag")
	self:Unhook("OpenBag")
	self:Unhook("CloseBag")
	self:Unhook("OpenBackpack")
	self:Unhook("CloseBackpack")
	-- self:Unhook('CloseSpecialWindows')
end
```

**Comment by pompyy89** [comment] 2023-02-07 08:33
This fix does not seem to work for me.
Retail: 10.0.5 (47967)
Addon: v1.10.7 (not the nolib)

**Comment by sam1amos** [comment] 2023-02-25 23:58
Addon Version: v1.10.7
World of Warcraft Retail Version 10.0.5 (48069)

Describe the bug:
I applied the provided fix and AdiBags ceased to display when the bags were opened.

Steps to reproduce
When AdiBags is the only 'closeable' window open, pressing 'esc' to close it will close AdiBags and open the in-game menu.

Verification
- [x]  I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by XtroTheArctic** [comment] 2023-03-09 23:37
I have the same bug. Didn't try the suggested fix here.

**Comment by Tealc-1899** [comment] 2023-05-30 05:53
I have been having this annoying issue in Retail since the fix for the bug that prevented closing the bags with esc was applied.

Have tried making the suggested changes above with no effect.

Any chance we may be able to see a resolution to this issue please?

**Comment by Rudecraft** [comment] 2023-06-28 05:19
I have disabled all other addons and have applied the fix and am still having this issue.

**Comment by XtroTheArctic** [comment] 2023-07-13 04:48
This doesn't happen sometimes. It happens always. Is the author of the addon not able to reproduce in any way? Very annoying  bug :(

**Comment by XtroTheArctic** [comment] 2023-07-13 05:19
I finally have time to try the suggested fix but it doesn't work :(

**Comment by XtroTheArctic** [comment] 2023-07-23 16:01
Please prioritize this very annoying bug :(

**Closed** 2023-11-26 03:12 UTC
Labels: Bug, Pending

**Comment by XtroTheArctic** [comment] 2023-11-26 03:44
I apologize for asking if it the answer is obvious but... was this closed because it was fixed?

**Comment by Cidan** [comment] 2023-11-26 03:45
No worries.

Please read the only bug left open on the issues page for more information.

**Comment by XtroTheArctic** [comment] 2023-11-26 03:49
Ouch. Sad to see the end of AdiBags. I loved it so much over the years. I hope BetterBags will be a "better" replacement. Thank you very much for all your efforts.

**Comment by Cidan** [comment] 2023-11-26 04:32
It's definitely a better replacement -- it's pretty far along already. Give it a shot :)
