### ISSUE TITLE
Module 'Shadowlands' already exists.

### ISSUE THREAD

**Issue by Frurox** [AdiAddons/AdiBags#626] opened 2022-02-07 19:32 UTC
Getting this error.

```
Message: Interface\AddOns\AdiBags\core\Filters.lua:126: Usage: NewModule(name, [prototype, [lib, lib, lib, ...]): 'name' - Module 'Shadowlands' already exists.
Time: Mon Feb  7 11:30:04 2022
Count: 1
Stack: Interface\AddOns\AdiBags\core\Filters.lua:126: Usage: NewModule(name, [prototype, [lib, lib, lib, ...]): 'name' - Module 'Shadowlands' already exists.
[string "=[C]"]: ?
[string "@Interface\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua"]:239: in function `NewModule'
[string "@Interface\AddOns\AdiBags\core\Filters.lua"]:126: in function `?'
[string "@Interface\AddOns\AdiBags_Shadowlands\AdiBags_Shadowlands.lua"]:1696: in main chunk

Locals: (*temporary) = "Usage: NewModule(name, [prototype, [lib, lib, lib, ...]): 'name' - Module 'Shadowlands' already exists."
```

What would you need from me to fix this?

**Comment by Talyrius** [comment] 2022-02-08 03:26
This error is due to conflicting module names being used by other AdiBags addons. I suggest you remove one of them.

Duplicate of https://github.com/AdiAddons/AdiBags/issues/51.

**Closed by Talyrius** 2022-02-08 03:26 UTC
Labels: Duplicate

**Comment by Frurox** [comment] 2022-02-08 03:29
> This error is due to conflicting module names being used by other AdiBags addons. I suggest you remove one of them.
> 
> Duplicate of #51.

Is there a way to know which one?

**Comment by Talyrius** [comment] 2022-02-08 03:37
AdiBags_Shadowlands is the addon that triggered the error, but that just means that it wasn't the first to load a module named 'Shadowlands'.

**Comment by Frurox** [comment] 2022-02-08 03:41
Cool thanks will try disabling AdiBags_Shadowlands, 1st and see. Wish it would tell you which one :)

**Comment by Frurox** [comment] 2022-02-08 05:46
it was AdiBags_Shadowlands disabled it, Thank you!!
